"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:186B  (274 instructions, 89 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x186B)
SIGNATURE = bytes.fromhex('c80a000056578b46048b560639061896')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x186B, 1: 0x187D, 2: 0x1880, 3: 0x1886, 4: 0x1889, 5: 0x1892, 6: 0x1895, 7: 0x189E, 8: 0x18A1, 9: 0x18A4, 10: 0x18AA, 11: 0x18EC, 12: 0x18F9, 13: 0x1906, 14: 0x190E, 15: 0x1911, 16: 0x1914, 17: 0x1917, 18: 0x191C, 19: 0x191F, 20: 0x193C, 21: 0x1949, 22: 0x198E, 23: 0x1991, 24: 0x199F, 25: 0x19B2, 26: 0x19B5, 27: 0x19B7, 28: 0x19BA, 29: 0x19BF, 30: 0x19C2, 31: 0x19DC, 32: 0x19E4, 33: 0x19E7, 34: 0x19EA, 35: 0x19FD, 36: 0x1A03, 37: 0x1A09, 38: 0x1A0C, 39: 0x1A12, 40: 0x1A15, 41: 0x1A1D, 42: 0x1A20, 43: 0x1A26, 44: 0x1A29, 45: 0x1A2E, 46: 0x1A31, 47: 0x1A37, 48: 0x1A43, 49: 0x1A46, 50: 0x1A50, 51: 0x1A59, 52: 0x1A61, 53: 0x1A64, 54: 0x1A69, 55: 0x1A6D, 56: 0x1A74, 57: 0x1A77, 58: 0x1A8D, 59: 0x1A95, 60: 0x1A98, 61: 0x1A9B, 62: 0x1AA5, 63: 0x1AAA, 64: 0x1AAD, 65: 0x1AB5, 66: 0x1AB8, 67: 0x1ABE, 68: 0x1AC1, 69: 0x1AC6, 70: 0x1AC9, 71: 0x1ACF, 72: 0x1ADB, 73: 0x1ADE, 74: 0x1AE8, 75: 0x1AF1, 76: 0x1AF9, 77: 0x1AFC, 78: 0x1B01, 79: 0x1B05, 80: 0x1B0C, 81: 0x1B0F, 82: 0x1B25, 83: 0x1B2D, 84: 0x1B30, 85: 0x1B33, 86: 0x1B3D, 87: 0x1B42, 88: 0x1B45}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:18EC": 11, "1010:18F9": 12, "1010:1906": 13, "1010:193C": 20, "1010:1949": 21, "1010:19DC": 31, "1010:19FD": 35, "1010:1A8D": 58, "1010:1B25": 82}


def lifted_1010_186b(cpu, bb=0):
    """Lifted replacement for 1010:186B."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x186B, SIGNATURE, 'lifted_1010_186b')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:186B  c80a0000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            s.sp = (s.sp - 0xA) & 0xFFFF
            # 1010:186F  56           push r16
            cpu.push(s.si)
            # 1010:1870  57           push r16
            cpu.push(s.di)
            # 1010:1871  8b4604       mov
            _o = (s.bp + 0x4) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1874  8b5606       mov
            _o = (s.bp + 0x6) & 0xFFFF
            s.dx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1877  39061896     cmp
            _o = 0x9618
            _a = mem.rw(s.ds, _o)
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:187B  7403         jz
            cpu.instruction_count += 7
            bb = 2 if cpu.condition(0x4) else 1
        elif bb == 1:
            # 1010:187D  e92400       jmp
            cpu.instruction_count += 1
            bb = 9
        elif bb == 2:
            # 1010:1880  39161a96     cmp
            _o = 0x961A
            _a = mem.rw(s.ds, _o)
            _b = s.dx
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1884  7403         jz
            cpu.instruction_count += 2
            bb = 4 if cpu.condition(0x4) else 3
        elif bb == 3:
            # 1010:1886  e91b00       jmp
            cpu.instruction_count += 1
            bb = 9
        elif bb == 4:
            # 1010:1889  8b4608       mov
            _o = (s.bp + 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:188C  39061caf     cmp
            _o = 0xAF1C
            _a = mem.rw(s.ds, _o)
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1890  7403         jz
            cpu.instruction_count += 3
            bb = 6 if cpu.condition(0x4) else 5
        elif bb == 5:
            # 1010:1892  e90f00       jmp
            cpu.instruction_count += 1
            bb = 9
        elif bb == 6:
            # 1010:1895  8b460a       mov
            _o = (s.bp + 0xA) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1898  39062caf     cmp
            _o = 0xAF2C
            _a = mem.rw(s.ds, _o)
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:189C  7403         jz
            cpu.instruction_count += 3
            bb = 8 if cpu.condition(0x4) else 7
        elif bb == 7:
            # 1010:189E  e90300       jmp
            cpu.instruction_count += 1
            bb = 9
        elif bb == 8:
            # 1010:18A1  e9a102       jmp
            cpu.instruction_count += 1
            bb = 88
        elif bb == 9:
            # 1010:18A4  be0100       mov r16,imm16
            s.si = 0x1
            # 1010:18A7  e96d00       jmp
            cpu.instruction_count += 2
            bb = 17
        elif bb == 10:
            # 1010:18AA  8b460a       mov
            _o = (s.bp + 0xA) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:18AD  2b062caf     sub
            _o = 0xAF2C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:18B1  f7ee         grp3 rm16
            _v = s.si
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:18B3  b90500       mov r16,imm16
            s.cx = 0x5
            # 1010:18B6  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:18B7  f7f9         grp3 rm16
            _v = s.cx
            if _v == 0:
                raise ZeroDivisionError('idiv by zero')
            _dividend = ((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF)
            if _dividend & 0x80000000:
                _dividend -= 0x100000000
            _divisor = cpu.sign16(_v & 0xFFFF)
            _q = int(_dividend / _divisor)
            _r = _dividend - _q * _divisor
            if _q < -32768 or _q > 32767:
                raise OverflowError('16-bit idiv quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:18B9  03062caf     add
            _o = 0xAF2C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:18BD  50           push r16
            cpu.push(s.ax)
            # 1010:18BE  8b4608       mov
            _o = (s.bp + 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:18C1  2b061caf     sub
            _o = 0xAF1C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:18C5  f7ee         grp3 rm16
            _v = s.si
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:18C7  b90500       mov r16,imm16
            s.cx = 0x5
            # 1010:18CA  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:18CB  f7f9         grp3 rm16
            _v = s.cx
            if _v == 0:
                raise ZeroDivisionError('idiv by zero')
            _dividend = ((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF)
            if _dividend & 0x80000000:
                _dividend -= 0x100000000
            _divisor = cpu.sign16(_v & 0xFFFF)
            _q = int(_dividend / _divisor)
            _r = _dividend - _q * _divisor
            if _q < -32768 or _q > 32767:
                raise OverflowError('16-bit idiv quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:18CD  03061caf     add
            _o = 0xAF1C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:18D1  50           push r16
            cpu.push(s.ax)
            # 1010:18D2  8b4604       mov
            _o = (s.bp + 0x4) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:18D5  8b5606       mov
            _o = (s.bp + 0x6) & 0xFFFF
            s.dx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:18D8  2b061896     sub
            _o = 0x9618
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:18DC  1b161a96     sbb
            _o = 0x961A
            _a = s.dx
            _b = mem.rw(s.ds, _o)
            _c = 1 if s.flags & CF else 0
            _r = _a - _b - _c
            cpu.set_sub_flags(_a, _b, _r, 16, _c)
            s.dx = (_r & 0xFFFF) & 0xFFFF
            # 1010:18E0  8bce         mov
            s.cx = (s.si) & 0xFFFF
            # 1010:18E2  bb0000       mov r16,imm16
            s.bx = 0x0
            # 1010:18E5  53           push r16
            cpu.push(s.bx)
            # 1010:18E6  51           push r16
            cpu.push(s.cx)
            # 1010:18E7  52           push r16
            cpu.push(s.dx)
            # 1010:18E8  50           push r16
            cpu.push(s.ax)
            # 1010:18E9  e86044       call
            cpu.instruction_count += 27
            emulate_call(cpu, 0x1010, 0x5D4C, 0x18EC)
            bb = 11
        elif bb == 11:
            # 1010:18EC  b90500       mov r16,imm16
            s.cx = 0x5
            # 1010:18EF  bb0000       mov r16,imm16
            s.bx = 0x0
            # 1010:18F2  53           push r16
            cpu.push(s.bx)
            # 1010:18F3  51           push r16
            cpu.push(s.cx)
            # 1010:18F4  52           push r16
            cpu.push(s.dx)
            # 1010:18F5  50           push r16
            cpu.push(s.ax)
            # 1010:18F6  e86145       call
            cpu.instruction_count += 7
            emulate_call(cpu, 0x1010, 0x5E5A, 0x18F9)
            bb = 12
        elif bb == 12:
            # 1010:18F9  03061896     add
            _o = 0x9618
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:18FD  13161a96     adc
            _o = 0x961A
            _a = s.dx
            _b = mem.rw(s.ds, _o)
            _c = 1 if s.flags & CF else 0
            _r = _a + _b + _c
            cpu.set_add_flags(_a, _b, _r, 16, _c)
            s.dx = (_r & 0xFFFF) & 0xFFFF
            # 1010:1901  52           push r16
            cpu.push(s.dx)
            # 1010:1902  50           push r16
            cpu.push(s.ax)
            # 1010:1903  e82cfe       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x1732, 0x1906)
            bb = 13
        elif bb == 13:
            # 1010:1906  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:1909  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:190C  7503         jnz
            cpu.instruction_count += 3
            bb = 15 if cpu.condition(0x5) else 14
        elif bb == 14:
            # 1010:190E  e90300       jmp
            cpu.instruction_count += 1
            bb = 16
        elif bb == 15:
            # 1010:1911  e90b00       jmp
            cpu.instruction_count += 1
            bb = 19
        elif bb == 16:
            # 1010:1914  83c601       grp1 rm16,imm8sx
            _a = s.si
            _b = 0x1
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.si = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 1
            bb = 17
        elif bb == 17:
            # 1010:1917  83fe05       grp1 rm16,imm8sx
            _a = s.si
            _b = 0x5
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:191A  7703         ja
            cpu.instruction_count += 2
            bb = 19 if cpu.condition(0x7) else 18
        elif bb == 18:
            # 1010:191C  e98bff       jmp
            cpu.instruction_count += 1
            bb = 10
        elif bb == 19:
            # 1010:191F  8b4604       mov
            _o = (s.bp + 0x4) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1922  8b5606       mov
            _o = (s.bp + 0x6) & 0xFFFF
            s.dx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1925  2b061896     sub
            _o = 0x9618
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1929  1b161a96     sbb
            _o = 0x961A
            _a = s.dx
            _b = mem.rw(s.ds, _o)
            _c = 1 if s.flags & CF else 0
            _r = _a - _b - _c
            cpu.set_sub_flags(_a, _b, _r, 16, _c)
            s.dx = (_r & 0xFFFF) & 0xFFFF
            # 1010:192D  8bce         mov
            s.cx = (s.si) & 0xFFFF
            # 1010:192F  83c1ff       grp1 rm16,imm8sx
            _a = s.cx
            _b = 0xFFFF
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:1932  bb0000       mov r16,imm16
            s.bx = 0x0
            # 1010:1935  53           push r16
            cpu.push(s.bx)
            # 1010:1936  51           push r16
            cpu.push(s.cx)
            # 1010:1937  52           push r16
            cpu.push(s.dx)
            # 1010:1938  50           push r16
            cpu.push(s.ax)
            # 1010:1939  e81044       call
            cpu.instruction_count += 12
            emulate_call(cpu, 0x1010, 0x5D4C, 0x193C)
            bb = 20
        elif bb == 20:
            # 1010:193C  b90500       mov r16,imm16
            s.cx = 0x5
            # 1010:193F  bb0000       mov r16,imm16
            s.bx = 0x0
            # 1010:1942  53           push r16
            cpu.push(s.bx)
            # 1010:1943  51           push r16
            cpu.push(s.cx)
            # 1010:1944  52           push r16
            cpu.push(s.dx)
            # 1010:1945  50           push r16
            cpu.push(s.ax)
            # 1010:1946  e81145       call
            cpu.instruction_count += 7
            emulate_call(cpu, 0x1010, 0x5E5A, 0x1949)
            bb = 21
        elif bb == 21:
            # 1010:1949  01061896     add
            _o = 0x9618
            _a = mem.rw(s.ds, _o)
            _b = s.ax
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            mem.ww(s.ds, _o, _r & 0xFFFF)
            # 1010:194D  11161a96     adc
            _o = 0x961A
            _a = mem.rw(s.ds, _o)
            _b = s.dx
            _c = 1 if s.flags & CF else 0
            _r = _a + _b + _c
            cpu.set_add_flags(_a, _b, _r, 16, _c)
            mem.ww(s.ds, _o, _r & 0xFFFF)
            # 1010:1951  8b4608       mov
            _o = (s.bp + 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1954  2b061caf     sub
            _o = 0xAF1C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1958  8bce         mov
            s.cx = (s.si) & 0xFFFF
            # 1010:195A  83c1ff       grp1 rm16,imm8sx
            _a = s.cx
            _b = 0xFFFF
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:195D  f7e9         grp3 rm16
            _v = s.cx
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:195F  b90500       mov r16,imm16
            s.cx = 0x5
            # 1010:1962  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:1963  f7f9         grp3 rm16
            _v = s.cx
            if _v == 0:
                raise ZeroDivisionError('idiv by zero')
            _dividend = ((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF)
            if _dividend & 0x80000000:
                _dividend -= 0x100000000
            _divisor = cpu.sign16(_v & 0xFFFF)
            _q = int(_dividend / _divisor)
            _r = _dividend - _q * _divisor
            if _q < -32768 or _q > 32767:
                raise OverflowError('16-bit idiv quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:1965  01061caf     add
            _o = 0xAF1C
            _a = mem.rw(s.ds, _o)
            _b = s.ax
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            mem.ww(s.ds, _o, _r & 0xFFFF)
            # 1010:1969  8b460a       mov
            _o = (s.bp + 0xA) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:196C  2b062caf     sub
            _o = 0xAF2C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1970  8bce         mov
            s.cx = (s.si) & 0xFFFF
            # 1010:1972  83c1ff       grp1 rm16,imm8sx
            _a = s.cx
            _b = 0xFFFF
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:1975  f7e9         grp3 rm16
            _v = s.cx
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:1977  b90500       mov r16,imm16
            s.cx = 0x5
            # 1010:197A  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:197B  f7f9         grp3 rm16
            _v = s.cx
            if _v == 0:
                raise ZeroDivisionError('idiv by zero')
            _dividend = ((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF)
            if _dividend & 0x80000000:
                _dividend -= 0x100000000
            _divisor = cpu.sign16(_v & 0xFFFF)
            _q = int(_dividend / _divisor)
            _r = _dividend - _q * _divisor
            if _q < -32768 or _q > 32767:
                raise OverflowError('16-bit idiv quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:197D  01062caf     add
            _o = 0xAF2C
            _a = mem.rw(s.ds, _o)
            _b = s.ax
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            mem.ww(s.ds, _o, _r & 0xFFFF)
            # 1010:1981  c746f80010   mov rm16,imm16
            _o = (s.bp - 0x8) & 0xFFFF
            mem.ww(s.ss, _o, 0x1000)
            # 1010:1986  c746fa0000   mov rm16,imm16
            _o = (s.bp - 0x6) & 0xFFFF
            mem.ww(s.ss, _o, 0x0)
            # 1010:198B  e97500       jmp
            cpu.instruction_count += 23
            bb = 36
        elif bb == 22:
            # 1010:198E  e90e00       jmp
            cpu.instruction_count += 1
            bb = 24
        elif bb == 23:
            # 1010:1991  8b46f8       mov
            _o = (s.bp - 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1994  8b56fa       mov
            _o = (s.bp - 0x6) & 0xFFFF
            s.dx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1997  01061896     add
            _o = 0x9618
            _a = mem.rw(s.ds, _o)
            _b = s.ax
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            mem.ww(s.ds, _o, _r & 0xFFFF)
            # 1010:199B  11161a96     adc
            _o = 0x961A
            _a = mem.rw(s.ds, _o)
            _b = s.dx
            _c = 1 if s.flags & CF else 0
            _r = _a + _b + _c
            cpu.set_add_flags(_a, _b, _r, 16, _c)
            mem.ww(s.ds, _o, _r & 0xFFFF)
            cpu.instruction_count += 4
            bb = 24
        elif bb == 24:
            # 1010:199F  8b4604       mov
            _o = (s.bp + 0x4) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:19A2  8b5606       mov
            _o = (s.bp + 0x6) & 0xFFFF
            s.dx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:19A5  2b061896     sub
            _o = 0x9618
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:19A9  1b161a96     sbb
            _o = 0x961A
            _a = s.dx
            _b = mem.rw(s.ds, _o)
            _c = 1 if s.flags & CF else 0
            _r = _a - _b - _c
            cpu.set_sub_flags(_a, _b, _r, 16, _c)
            s.dx = (_r & 0xFFFF) & 0xFFFF
            # 1010:19AD  3b56fa       cmp
            _o = (s.bp - 0x6) & 0xFFFF
            _a = s.dx
            _b = mem.rw(s.ss, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:19B0  7303         jnb
            cpu.instruction_count += 6
            bb = 26 if cpu.condition(0x3) else 25
        elif bb == 25:
            # 1010:19B2  e93500       jmp
            cpu.instruction_count += 1
            bb = 34
        elif bb == 26:
            # 1010:19B5  7603         jbe
            cpu.instruction_count += 1
            bb = 28 if cpu.condition(0x6) else 27
        elif bb == 27:
            # 1010:19B7  e90800       jmp
            cpu.instruction_count += 1
            bb = 30
        elif bb == 28:
            # 1010:19BA  3b46f8       cmp
            _o = (s.bp - 0x8) & 0xFFFF
            _a = s.ax
            _b = mem.rw(s.ss, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:19BD  7303         jnb
            cpu.instruction_count += 2
            bb = 30 if cpu.condition(0x3) else 29
        elif bb == 29:
            # 1010:19BF  e92800       jmp
            cpu.instruction_count += 1
            bb = 34
        elif bb == 30:
            # 1010:19C2  ff362caf     push rm16
            _o = 0xAF2C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:19C6  ff361caf     push rm16
            _o = 0xAF1C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:19CA  a11896       mov moffs
            s.ax = mem.rw(s.ds, 0x9618)
            # 1010:19CD  8b161a96     mov
            _o = 0x961A
            s.dx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:19D1  0346f8       add
            _o = (s.bp - 0x8) & 0xFFFF
            _a = s.ax
            _b = mem.rw(s.ss, _o)
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:19D4  1356fa       adc
            _o = (s.bp - 0x6) & 0xFFFF
            _a = s.dx
            _b = mem.rw(s.ss, _o)
            _c = 1 if s.flags & CF else 0
            _r = _a + _b + _c
            cpu.set_add_flags(_a, _b, _r, 16, _c)
            s.dx = (_r & 0xFFFF) & 0xFFFF
            # 1010:19D7  52           push r16
            cpu.push(s.dx)
            # 1010:19D8  50           push r16
            cpu.push(s.ax)
            # 1010:19D9  e856fd       call
            cpu.instruction_count += 9
            emulate_call(cpu, 0x1010, 0x1732, 0x19DC)
            bb = 31
        elif bb == 31:
            # 1010:19DC  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:19DF  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:19E2  7403         jz
            cpu.instruction_count += 3
            bb = 33 if cpu.condition(0x4) else 32
        elif bb == 32:
            # 1010:19E4  e90300       jmp
            cpu.instruction_count += 1
            bb = 34
        elif bb == 33:
            # 1010:19E7  e9a7ff       jmp
            cpu.instruction_count += 1
            bb = 23
        elif bb == 34:
            # 1010:19EA  b81000       mov r16,imm16
            s.ax = 0x10
            # 1010:19ED  ba0000       mov r16,imm16
            s.dx = 0x0
            # 1010:19F0  8b4ef8       mov
            _o = (s.bp - 0x8) & 0xFFFF
            s.cx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:19F3  8b5efa       mov
            _o = (s.bp - 0x6) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:19F6  52           push r16
            cpu.push(s.dx)
            # 1010:19F7  50           push r16
            cpu.push(s.ax)
            # 1010:19F8  53           push r16
            cpu.push(s.bx)
            # 1010:19F9  51           push r16
            cpu.push(s.cx)
            # 1010:19FA  e88f43       call
            cpu.instruction_count += 9
            emulate_call(cpu, 0x1010, 0x5D8C, 0x19FD)
            bb = 35
        elif bb == 35:
            # 1010:19FD  8946f8       mov
            _o = (s.bp - 0x8) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:1A00  8956fa       mov
            _o = (s.bp - 0x6) & 0xFFFF
            mem.ww(s.ss, _o, s.dx)
            cpu.instruction_count += 2
            bb = 36
        elif bb == 36:
            # 1010:1A03  837ef800     grp1 rm16,imm8sx
            _o = (s.bp - 0x8) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1A07  7403         jz
            cpu.instruction_count += 2
            bb = 38 if cpu.condition(0x4) else 37
        elif bb == 37:
            # 1010:1A09  e982ff       jmp
            cpu.instruction_count += 1
            bb = 22
        elif bb == 38:
            # 1010:1A0C  837efa00     grp1 rm16,imm8sx
            _o = (s.bp - 0x6) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1A10  7403         jz
            cpu.instruction_count += 2
            bb = 40 if cpu.condition(0x4) else 39
        elif bb == 39:
            # 1010:1A12  e979ff       jmp
            cpu.instruction_count += 1
            bb = 22
        elif bb == 40:
            # 1010:1A15  a11caf       mov moffs
            s.ax = mem.rw(s.ds, 0xAF1C)
            # 1010:1A18  394608       cmp
            _o = (s.bp + 0x8) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1A1B  7703         ja
            cpu.instruction_count += 3
            bb = 42 if cpu.condition(0x7) else 41
        elif bb == 41:
            # 1010:1A1D  e90600       jmp
            cpu.instruction_count += 1
            bb = 43
        elif bb == 42:
            # 1010:1A20  b87d00       mov r16,imm16
            s.ax = 0x7D
            # 1010:1A23  e90300       jmp
            cpu.instruction_count += 2
            bb = 44
        elif bb == 43:
            # 1010:1A26  b883ff       mov r16,imm16
            s.ax = 0xFF83
            cpu.instruction_count += 1
            bb = 44
        elif bb == 44:
            # 1010:1A29  8bf8         mov
            s.di = (s.ax) & 0xFFFF
            # 1010:1A2B  e97700       jmp
            cpu.instruction_count += 2
            bb = 62
        elif bb == 45:
            # 1010:1A2E  e90600       jmp
            cpu.instruction_count += 1
            bb = 47
        elif bb == 46:
            # 1010:1A31  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1A33  01061caf     add
            _o = 0xAF1C
            _a = mem.rw(s.ds, _o)
            _b = s.ax
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            mem.ww(s.ds, _o, _r & 0xFFFF)
            cpu.instruction_count += 2
            bb = 47
        elif bb == 47:
            # 1010:1A37  8b4608       mov
            _o = (s.bp + 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1A3A  2b061caf     sub
            _o = 0xAF1C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1A3E  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1A41  7f03         jg
            cpu.instruction_count += 4
            bb = 49 if cpu.condition(0xF) else 48
        elif bb == 48:
            # 1010:1A43  e90a00       jmp
            cpu.instruction_count += 1
            bb = 50
        elif bb == 49:
            # 1010:1A46  8b4608       mov
            _o = (s.bp + 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1A49  2b061caf     sub
            _o = 0xAF1C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1A4D  e90900       jmp
            cpu.instruction_count += 3
            bb = 51
        elif bb == 50:
            # 1010:1A50  8b4608       mov
            _o = (s.bp + 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1A53  2b061caf     sub
            _o = 0xAF1C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1A57  f7d8         grp3 rm16
            _v = s.ax
            cpu.set_sub_flags(0, _v, -_v, 16)
            s.ax = ((-_v) & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 3
            bb = 51
        elif bb == 51:
            # 1010:1A59  8946f6       mov
            _o = (s.bp - 0xA) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:1A5C  83ff00       grp1 rm16,imm8sx
            _a = s.di
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1A5F  7f03         jg
            cpu.instruction_count += 3
            bb = 53 if cpu.condition(0xF) else 52
        elif bb == 52:
            # 1010:1A61  e90500       jmp
            cpu.instruction_count += 1
            bb = 54
        elif bb == 53:
            # 1010:1A64  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1A66  e90400       jmp
            cpu.instruction_count += 2
            bb = 55
        elif bb == 54:
            # 1010:1A69  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1A6B  f7d8         grp3 rm16
            _v = s.ax
            cpu.set_sub_flags(0, _v, -_v, 16)
            s.ax = ((-_v) & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 2
            bb = 55
        elif bb == 55:
            # 1010:1A6D  8b4ef6       mov
            _o = (s.bp - 0xA) & 0xFFFF
            s.cx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1A70  3bc8         cmp
            _a = s.cx
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1A72  7d03         jge
            cpu.instruction_count += 3
            bb = 57 if cpu.condition(0xD) else 56
        elif bb == 56:
            # 1010:1A74  e92400       jmp
            cpu.instruction_count += 1
            bb = 61
        elif bb == 57:
            # 1010:1A77  ff362caf     push rm16
            _o = 0xAF2C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1A7B  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1A7D  03061caf     add
            _o = 0xAF1C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1A81  50           push r16
            cpu.push(s.ax)
            # 1010:1A82  ff361a96     push rm16
            _o = 0x961A
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1A86  ff361896     push rm16
            _o = 0x9618
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1A8A  e8a5fc       call
            cpu.instruction_count += 7
            emulate_call(cpu, 0x1010, 0x1732, 0x1A8D)
            bb = 58
        elif bb == 58:
            # 1010:1A8D  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:1A90  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1A93  7403         jz
            cpu.instruction_count += 3
            bb = 60 if cpu.condition(0x4) else 59
        elif bb == 59:
            # 1010:1A95  e90300       jmp
            cpu.instruction_count += 1
            bb = 61
        elif bb == 60:
            # 1010:1A98  e996ff       jmp
            cpu.instruction_count += 1
            bb = 46
        elif bb == 61:
            # 1010:1A9B  b90500       mov r16,imm16
            s.cx = 0x5
            # 1010:1A9E  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1AA0  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:1AA1  f7f9         grp3 rm16
            _v = s.cx
            if _v == 0:
                raise ZeroDivisionError('idiv by zero')
            _dividend = ((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF)
            if _dividend & 0x80000000:
                _dividend -= 0x100000000
            _divisor = cpu.sign16(_v & 0xFFFF)
            _q = int(_dividend / _divisor)
            _r = _dividend - _q * _divisor
            if _q < -32768 or _q > 32767:
                raise OverflowError('16-bit idiv quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:1AA3  8bf8         mov
            s.di = (s.ax) & 0xFFFF
            cpu.instruction_count += 5
            bb = 62
        elif bb == 62:
            # 1010:1AA5  83ff00       grp1 rm16,imm8sx
            _a = s.di
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1AA8  7403         jz
            cpu.instruction_count += 2
            bb = 64 if cpu.condition(0x4) else 63
        elif bb == 63:
            # 1010:1AAA  e981ff       jmp
            cpu.instruction_count += 1
            bb = 45
        elif bb == 64:
            # 1010:1AAD  a12caf       mov moffs
            s.ax = mem.rw(s.ds, 0xAF2C)
            # 1010:1AB0  39460a       cmp
            _o = (s.bp + 0xA) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1AB3  7703         ja
            cpu.instruction_count += 3
            bb = 66 if cpu.condition(0x7) else 65
        elif bb == 65:
            # 1010:1AB5  e90600       jmp
            cpu.instruction_count += 1
            bb = 67
        elif bb == 66:
            # 1010:1AB8  b87d00       mov r16,imm16
            s.ax = 0x7D
            # 1010:1ABB  e90300       jmp
            cpu.instruction_count += 2
            bb = 68
        elif bb == 67:
            # 1010:1ABE  b883ff       mov r16,imm16
            s.ax = 0xFF83
            cpu.instruction_count += 1
            bb = 68
        elif bb == 68:
            # 1010:1AC1  8bf8         mov
            s.di = (s.ax) & 0xFFFF
            # 1010:1AC3  e97700       jmp
            cpu.instruction_count += 2
            bb = 86
        elif bb == 69:
            # 1010:1AC6  e90600       jmp
            cpu.instruction_count += 1
            bb = 71
        elif bb == 70:
            # 1010:1AC9  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1ACB  01062caf     add
            _o = 0xAF2C
            _a = mem.rw(s.ds, _o)
            _b = s.ax
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            mem.ww(s.ds, _o, _r & 0xFFFF)
            cpu.instruction_count += 2
            bb = 71
        elif bb == 71:
            # 1010:1ACF  8b460a       mov
            _o = (s.bp + 0xA) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1AD2  2b062caf     sub
            _o = 0xAF2C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1AD6  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1AD9  7f03         jg
            cpu.instruction_count += 4
            bb = 73 if cpu.condition(0xF) else 72
        elif bb == 72:
            # 1010:1ADB  e90a00       jmp
            cpu.instruction_count += 1
            bb = 74
        elif bb == 73:
            # 1010:1ADE  8b460a       mov
            _o = (s.bp + 0xA) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1AE1  2b062caf     sub
            _o = 0xAF2C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1AE5  e90900       jmp
            cpu.instruction_count += 3
            bb = 75
        elif bb == 74:
            # 1010:1AE8  8b460a       mov
            _o = (s.bp + 0xA) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1AEB  2b062caf     sub
            _o = 0xAF2C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1AEF  f7d8         grp3 rm16
            _v = s.ax
            cpu.set_sub_flags(0, _v, -_v, 16)
            s.ax = ((-_v) & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 3
            bb = 75
        elif bb == 75:
            # 1010:1AF1  8946f6       mov
            _o = (s.bp - 0xA) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:1AF4  83ff00       grp1 rm16,imm8sx
            _a = s.di
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1AF7  7f03         jg
            cpu.instruction_count += 3
            bb = 77 if cpu.condition(0xF) else 76
        elif bb == 76:
            # 1010:1AF9  e90500       jmp
            cpu.instruction_count += 1
            bb = 78
        elif bb == 77:
            # 1010:1AFC  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1AFE  e90400       jmp
            cpu.instruction_count += 2
            bb = 79
        elif bb == 78:
            # 1010:1B01  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1B03  f7d8         grp3 rm16
            _v = s.ax
            cpu.set_sub_flags(0, _v, -_v, 16)
            s.ax = ((-_v) & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 2
            bb = 79
        elif bb == 79:
            # 1010:1B05  8b4ef6       mov
            _o = (s.bp - 0xA) & 0xFFFF
            s.cx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1B08  3bc8         cmp
            _a = s.cx
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1B0A  7d03         jge
            cpu.instruction_count += 3
            bb = 81 if cpu.condition(0xD) else 80
        elif bb == 80:
            # 1010:1B0C  e92400       jmp
            cpu.instruction_count += 1
            bb = 85
        elif bb == 81:
            # 1010:1B0F  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1B11  03062caf     add
            _o = 0xAF2C
            _a = s.ax
            _b = mem.rw(s.ds, _o)
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1B15  50           push r16
            cpu.push(s.ax)
            # 1010:1B16  ff361caf     push rm16
            _o = 0xAF1C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1B1A  ff361a96     push rm16
            _o = 0x961A
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1B1E  ff361896     push rm16
            _o = 0x9618
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1B22  e80dfc       call
            cpu.instruction_count += 7
            emulate_call(cpu, 0x1010, 0x1732, 0x1B25)
            bb = 82
        elif bb == 82:
            # 1010:1B25  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:1B28  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1B2B  7403         jz
            cpu.instruction_count += 3
            bb = 84 if cpu.condition(0x4) else 83
        elif bb == 83:
            # 1010:1B2D  e90300       jmp
            cpu.instruction_count += 1
            bb = 85
        elif bb == 84:
            # 1010:1B30  e996ff       jmp
            cpu.instruction_count += 1
            bb = 70
        elif bb == 85:
            # 1010:1B33  b90500       mov r16,imm16
            s.cx = 0x5
            # 1010:1B36  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1B38  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:1B39  f7f9         grp3 rm16
            _v = s.cx
            if _v == 0:
                raise ZeroDivisionError('idiv by zero')
            _dividend = ((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF)
            if _dividend & 0x80000000:
                _dividend -= 0x100000000
            _divisor = cpu.sign16(_v & 0xFFFF)
            _q = int(_dividend / _divisor)
            _r = _dividend - _q * _divisor
            if _q < -32768 or _q > 32767:
                raise OverflowError('16-bit idiv quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:1B3B  8bf8         mov
            s.di = (s.ax) & 0xFFFF
            cpu.instruction_count += 5
            bb = 86
        elif bb == 86:
            # 1010:1B3D  83ff00       grp1 rm16,imm8sx
            _a = s.di
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1B40  7403         jz
            cpu.instruction_count += 2
            bb = 88 if cpu.condition(0x4) else 87
        elif bb == 87:
            # 1010:1B42  e981ff       jmp
            cpu.instruction_count += 1
            bb = 69
        elif bb == 88:
            # 1010:1B45  5f           pop r16
            s.di = cpu.pop()
            # 1010:1B46  5e           pop r16
            s.si = cpu.pop()
            # 1010:1B47  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:1B48  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            cpu.call_depth = max(0, cpu.call_depth - 1)
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_186b.owns_time = True

