"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:5737  (32 instructions, 11 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x5737)
SIGNATURE = bytes.fromhex('c8020000565768fc0be83405')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x5737, 1: 0x5743, 2: 0x5754, 3: 0x575D, 4: 0x5767, 5: 0x576A, 6: 0x576D, 7: 0x5772, 8: 0x5775, 9: 0x577F, 10: 0x5782}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:5743": 1, "1010:5754": 2, "1010:575D": 3, "1010:576D": 6, "1010:577F": 9}


def lifted_1010_5737(cpu, bb=0):
    """Lifted replacement for 1010:5737."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x5737, SIGNATURE, 'lifted_1010_5737')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:5737  c8020000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            s.sp = (s.sp - 0x2) & 0xFFFF
            # 1010:573B  56           push r16
            cpu.push(s.si)
            # 1010:573C  57           push r16
            cpu.push(s.di)
            # 1010:573D  68fc0b       push imm16
            cpu.push(0xBFC)
            # 1010:5740  e83405       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x5C77, 0x5743)
            bb = 1
        elif bb == 1:
            # 1010:5743  83c402       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x2
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:5746  8946fe       mov
            _o = (s.bp - 0x2) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:5749  6a42         push imm8
            cpu.push(0x0042)
            # 1010:574B  681645       push imm16
            cpu.push(0x4516)
            # 1010:574E  ff76fe       push rm16
            _o = (s.bp - 0x2) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:5751  e82908       call
            cpu.instruction_count += 6
            emulate_call(cpu, 0x1010, 0x5F7D, 0x5754)
            bb = 2
        elif bb == 2:
            # 1010:5754  83c406       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x6
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:5757  ff76fe       push rm16
            _o = (s.bp - 0x2) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:575A  e8fc04       call
            cpu.instruction_count += 3
            emulate_call(cpu, 0x1010, 0x5C59, 0x575D)
            bb = 3
        elif bb == 3:
            # 1010:575D  83c402       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x2
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:5760  833eaa4100   grp1 rm16,imm8sx
            _o = 0x41AA
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:5765  7403         jz
            cpu.instruction_count += 3
            bb = 5 if cpu.condition(0x4) else 4
        elif bb == 4:
            # 1010:5767  e90b00       jmp
            cpu.instruction_count += 1
            bb = 8
        elif bb == 5:
            # 1010:576A  e872ff       call
            cpu.instruction_count += 1
            emulate_call(cpu, 0x1010, 0x56DF, 0x576D)
            bb = 6
        elif bb == 6:
            # 1010:576D  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:5770  7503         jnz
            cpu.instruction_count += 2
            bb = 8 if cpu.condition(0x5) else 7
        elif bb == 7:
            # 1010:5772  e90d00       jmp
            cpu.instruction_count += 1
            bb = 10
        elif bb == 8:
            # 1010:5775  6a42         push imm8
            cpu.push(0x0042)
            # 1010:5777  6a00         push imm8
            cpu.push(0x0000)
            # 1010:5779  681645       push imm16
            cpu.push(0x4516)
            # 1010:577C  e88805       call
            cpu.instruction_count += 4
            emulate_call(cpu, 0x1010, 0x5D07, 0x577F)
            bb = 9
        elif bb == 9:
            # 1010:577F  83c406       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x6
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 1
            bb = 10
        elif bb == 10:
            # 1010:5782  c706aa410000 mov rm16,imm16
            _o = 0x41AA
            mem.ww(s.ds, _o, 0x0)
            # 1010:5788  5f           pop r16
            s.di = cpu.pop()
            # 1010:5789  5e           pop r16
            s.si = cpu.pop()
            # 1010:578A  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:578B  c3           ret
            cpu.instruction_count += 5
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_5737.owns_time = True

