"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:1DFA  (170 instructions, 38 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x1DFA)
SIGNATURE = bytes.fromhex('c80800005657ff363693ff366845ff36')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x1DFA, 1: 0x1E23, 2: 0x1E2B, 3: 0x1E2E, 4: 0x1E31, 5: 0x1E48, 6: 0x1E77, 7: 0x1E7F, 8: 0x1E82, 9: 0x1E85, 10: 0x1EB7, 11: 0x1EBF, 12: 0x1EC2, 13: 0x1EC5, 14: 0x1ED9, 15: 0x1EE6, 16: 0x1EFA, 17: 0x1EFD, 18: 0x1EFF, 19: 0x1F02, 20: 0x1F0A, 21: 0x1F0D, 22: 0x1F30, 23: 0x1F38, 24: 0x1F3B, 25: 0x1F3E, 26: 0x1F56, 27: 0x1F63, 28: 0x1F8D, 29: 0x1F95, 30: 0x1F98, 31: 0x1F9B, 32: 0x1FAB, 33: 0x1FB0, 34: 0x1FB3, 35: 0x1FCC, 36: 0x1FCF, 37: 0x1FD5}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:1E23": 1, "1010:1E77": 6, "1010:1EB7": 10, "1010:1ED9": 14, "1010:1EE6": 15, "1010:1F30": 22, "1010:1F56": 26, "1010:1F63": 27, "1010:1F8D": 28}


def lifted_1010_1dfa(cpu, bb=0):
    """Lifted replacement for 1010:1DFA."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x1DFA, SIGNATURE, 'lifted_1010_1dfa')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:1DFA  c8080000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            s.sp = (s.sp - 0x8) & 0xFFFF
            # 1010:1DFE  56           push r16
            cpu.push(s.si)
            # 1010:1DFF  57           push r16
            cpu.push(s.di)
            # 1010:1E00  ff363693     push rm16
            _o = 0x9336
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E04  ff366845     push rm16
            _o = 0x4568
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E08  ff36ae54     push rm16
            _o = 0x54AE
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E0C  ff36ac54     push rm16
            _o = 0x54AC
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E10  ff362caf     push rm16
            _o = 0xAF2C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E14  ff361caf     push rm16
            _o = 0xAF1C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E18  ff361a96     push rm16
            _o = 0x961A
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E1C  ff361896     push rm16
            _o = 0x9618
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E20  e8aafe       call
            cpu.instruction_count += 12
            emulate_call(cpu, 0x1010, 0x1CCD, 0x1E23)
            bb = 1
        elif bb == 1:
            # 1010:1E23  83c410       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x10
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:1E26  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1E29  7503         jnz
            cpu.instruction_count += 3
            bb = 3 if cpu.condition(0x5) else 2
        elif bb == 2:
            # 1010:1E2B  e90300       jmp
            cpu.instruction_count += 1
            bb = 4
        elif bb == 3:
            # 1010:1E2E  e9a401       jmp
            cpu.instruction_count += 1
            bb = 37
        elif bb == 4:
            # 1010:1E31  a1ac54       mov moffs
            s.ax = mem.rw(s.ds, 0x54AC)
            # 1010:1E34  8b16ae54     mov
            _o = 0x54AE
            s.dx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:1E38  8946fc       mov
            _o = (s.bp - 0x4) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:1E3B  8956fe       mov
            _o = (s.bp - 0x2) & 0xFFFF
            mem.ww(s.ss, _o, s.dx)
            # 1010:1E3E  8b366845     mov
            _o = 0x4568
            s.si = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:1E42  bf0100       mov r16,imm16
            s.di = 0x1
            # 1010:1E45  e96301       jmp
            cpu.instruction_count += 7
            bb = 32
        elif bb == 5:
            # 1010:1E48  ff363693     push rm16
            _o = 0x9336
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E4C  8bc6         mov
            s.ax = (s.si) & 0xFFFF
            # 1010:1E4E  f7ef         grp3 rm16
            _v = s.di
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:1E50  b90a00       mov r16,imm16
            s.cx = 0xA
            # 1010:1E53  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:1E54  f7f9         grp3 rm16
            _v = s.cx
            if _v == 0:
                raise ZeroDivisionError('idiv by zero')
            _dividend = ((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF)
            if _dividend & 0x80000000:
                _dividend -= 0x100000000
            _divisor = cpu.sign16(_v & 0xFFFF)
            _q = int(_dividend / _divisor)
            _r = _dividend - _q * _divisor
            if _q < -32768 or _q > 32767:
                raise OverflowError('16-bit idiv quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:1E56  03c6         add
            _a = s.ax
            _b = s.si
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1E58  a36845       mov moffs
            mem.ww(s.ds, 0x4568, s.ax)
            # 1010:1E5B  50           push r16
            cpu.push(s.ax)
            # 1010:1E5C  ff36ae54     push rm16
            _o = 0x54AE
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E60  ff36ac54     push rm16
            _o = 0x54AC
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E64  ff362caf     push rm16
            _o = 0xAF2C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E68  ff361caf     push rm16
            _o = 0xAF1C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E6C  ff361a96     push rm16
            _o = 0x961A
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E70  ff361896     push rm16
            _o = 0x9618
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E74  e856fe       call
            cpu.instruction_count += 16
            emulate_call(cpu, 0x1010, 0x1CCD, 0x1E77)
            bb = 6
        elif bb == 6:
            # 1010:1E77  83c410       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x10
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:1E7A  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1E7D  7503         jnz
            cpu.instruction_count += 3
            bb = 8 if cpu.condition(0x5) else 7
        elif bb == 7:
            # 1010:1E7F  e90300       jmp
            cpu.instruction_count += 1
            bb = 9
        elif bb == 8:
            # 1010:1E82  e92e01       jmp
            cpu.instruction_count += 1
            bb = 34
        elif bb == 9:
            # 1010:1E85  ff363693     push rm16
            _o = 0x9336
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1E89  8bc6         mov
            s.ax = (s.si) & 0xFFFF
            # 1010:1E8B  f7ef         grp3 rm16
            _v = s.di
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:1E8D  b90a00       mov r16,imm16
            s.cx = 0xA
            # 1010:1E90  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:1E91  f7f9         grp3 rm16
            _v = s.cx
            if _v == 0:
                raise ZeroDivisionError('idiv by zero')
            _dividend = ((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF)
            if _dividend & 0x80000000:
                _dividend -= 0x100000000
            _divisor = cpu.sign16(_v & 0xFFFF)
            _q = int(_dividend / _divisor)
            _r = _dividend - _q * _divisor
            if _q < -32768 or _q > 32767:
                raise OverflowError('16-bit idiv quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:1E93  8bce         mov
            s.cx = (s.si) & 0xFFFF
            # 1010:1E95  2bc8         sub
            _a = s.cx
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:1E97  890e6845     mov
            _o = 0x4568
            mem.ww(s.ds, _o, s.cx)
            # 1010:1E9B  51           push r16
            cpu.push(s.cx)
            # 1010:1E9C  ff36ae54     push rm16
            _o = 0x54AE
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1EA0  ff36ac54     push rm16
            _o = 0x54AC
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1EA4  ff362caf     push rm16
            _o = 0xAF2C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1EA8  ff361caf     push rm16
            _o = 0xAF1C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1EAC  ff361a96     push rm16
            _o = 0x961A
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1EB0  ff361896     push rm16
            _o = 0x9618
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1EB4  e816fe       call
            cpu.instruction_count += 17
            emulate_call(cpu, 0x1010, 0x1CCD, 0x1EB7)
            bb = 10
        elif bb == 10:
            # 1010:1EB7  83c410       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x10
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:1EBA  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1EBD  7503         jnz
            cpu.instruction_count += 3
            bb = 12 if cpu.condition(0x5) else 11
        elif bb == 11:
            # 1010:1EBF  e90300       jmp
            cpu.instruction_count += 1
            bb = 13
        elif bb == 12:
            # 1010:1EC2  e9ee00       jmp
            cpu.instruction_count += 1
            bb = 34
        elif bb == 13:
            # 1010:1EC5  89366845     mov
            _o = 0x4568
            mem.ww(s.ds, _o, s.si)
            # 1010:1EC9  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1ECB  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:1ECC  8b4efc       mov
            _o = (s.bp - 0x4) & 0xFFFF
            s.cx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1ECF  8b5efe       mov
            _o = (s.bp - 0x2) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1ED2  52           push r16
            cpu.push(s.dx)
            # 1010:1ED3  50           push r16
            cpu.push(s.ax)
            # 1010:1ED4  53           push r16
            cpu.push(s.bx)
            # 1010:1ED5  51           push r16
            cpu.push(s.cx)
            # 1010:1ED6  e8733e       call
            cpu.instruction_count += 10
            emulate_call(cpu, 0x1010, 0x5D4C, 0x1ED9)
            bb = 14
        elif bb == 14:
            # 1010:1ED9  b90a00       mov r16,imm16
            s.cx = 0xA
            # 1010:1EDC  bb0000       mov r16,imm16
            s.bx = 0x0
            # 1010:1EDF  53           push r16
            cpu.push(s.bx)
            # 1010:1EE0  51           push r16
            cpu.push(s.cx)
            # 1010:1EE1  52           push r16
            cpu.push(s.dx)
            # 1010:1EE2  50           push r16
            cpu.push(s.ax)
            # 1010:1EE3  e8743f       call
            cpu.instruction_count += 7
            emulate_call(cpu, 0x1010, 0x5E5A, 0x1EE6)
            bb = 15
        elif bb == 15:
            # 1010:1EE6  0346fc       add
            _o = (s.bp - 0x4) & 0xFFFF
            _a = s.ax
            _b = mem.rw(s.ss, _o)
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1EE9  1356fe       adc
            _o = (s.bp - 0x2) & 0xFFFF
            _a = s.dx
            _b = mem.rw(s.ss, _o)
            _c = 1 if s.flags & CF else 0
            _r = _a + _b + _c
            cpu.set_add_flags(_a, _b, _r, 16, _c)
            s.dx = (_r & 0xFFFF) & 0xFFFF
            # 1010:1EEC  a3ac54       mov moffs
            mem.ww(s.ds, 0x54AC, s.ax)
            # 1010:1EEF  8916ae54     mov
            _o = 0x54AE
            mem.ww(s.ds, _o, s.dx)
            # 1010:1EF3  833eae5400   grp1 rm16,imm8sx
            _o = 0x54AE
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1EF8  7e03         jle
            cpu.instruction_count += 6
            bb = 17 if cpu.condition(0xE) else 16
        elif bb == 16:
            # 1010:1EFA  e94100       jmp
            cpu.instruction_count += 1
            bb = 25
        elif bb == 17:
            # 1010:1EFD  7d03         jge
            cpu.instruction_count += 1
            bb = 19 if cpu.condition(0xD) else 18
        elif bb == 18:
            # 1010:1EFF  e90b00       jmp
            cpu.instruction_count += 1
            bb = 21
        elif bb == 19:
            # 1010:1F02  813eac54aa2a grp1 rm16,imm16
            _o = 0x54AC
            _a = mem.rw(s.ds, _o)
            _b = 0x2AAA
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1F08  7203         jb
            cpu.instruction_count += 2
            bb = 21 if cpu.condition(0x2) else 20
        elif bb == 20:
            # 1010:1F0A  e93100       jmp
            cpu.instruction_count += 1
            bb = 25
        elif bb == 21:
            # 1010:1F0D  ff363693     push rm16
            _o = 0x9336
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F11  ff366845     push rm16
            _o = 0x4568
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F15  ff36ae54     push rm16
            _o = 0x54AE
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F19  ff36ac54     push rm16
            _o = 0x54AC
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F1D  ff362caf     push rm16
            _o = 0xAF2C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F21  ff361caf     push rm16
            _o = 0xAF1C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F25  ff361a96     push rm16
            _o = 0x961A
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F29  ff361896     push rm16
            _o = 0x9618
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F2D  e89dfd       call
            cpu.instruction_count += 9
            emulate_call(cpu, 0x1010, 0x1CCD, 0x1F30)
            bb = 22
        elif bb == 22:
            # 1010:1F30  83c410       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x10
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:1F33  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1F36  7503         jnz
            cpu.instruction_count += 3
            bb = 24 if cpu.condition(0x5) else 23
        elif bb == 23:
            # 1010:1F38  e90300       jmp
            cpu.instruction_count += 1
            bb = 25
        elif bb == 24:
            # 1010:1F3B  e97500       jmp
            cpu.instruction_count += 1
            bb = 34
        elif bb == 25:
            # 1010:1F3E  ff363693     push rm16
            _o = 0x9336
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F42  ff366845     push rm16
            _o = 0x4568
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F46  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1F48  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:1F49  8b4efc       mov
            _o = (s.bp - 0x4) & 0xFFFF
            s.cx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1F4C  8b5efe       mov
            _o = (s.bp - 0x2) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1F4F  52           push r16
            cpu.push(s.dx)
            # 1010:1F50  50           push r16
            cpu.push(s.ax)
            # 1010:1F51  53           push r16
            cpu.push(s.bx)
            # 1010:1F52  51           push r16
            cpu.push(s.cx)
            # 1010:1F53  e8f63d       call
            cpu.instruction_count += 11
            emulate_call(cpu, 0x1010, 0x5D4C, 0x1F56)
            bb = 26
        elif bb == 26:
            # 1010:1F56  b90a00       mov r16,imm16
            s.cx = 0xA
            # 1010:1F59  bb0000       mov r16,imm16
            s.bx = 0x0
            # 1010:1F5C  53           push r16
            cpu.push(s.bx)
            # 1010:1F5D  51           push r16
            cpu.push(s.cx)
            # 1010:1F5E  52           push r16
            cpu.push(s.dx)
            # 1010:1F5F  50           push r16
            cpu.push(s.ax)
            # 1010:1F60  e8f73e       call
            cpu.instruction_count += 7
            emulate_call(cpu, 0x1010, 0x5E5A, 0x1F63)
            bb = 27
        elif bb == 27:
            # 1010:1F63  8b4efc       mov
            _o = (s.bp - 0x4) & 0xFFFF
            s.cx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1F66  8b5efe       mov
            _o = (s.bp - 0x2) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1F69  2bc8         sub
            _a = s.cx
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:1F6B  1bda         sbb
            _a = s.bx
            _b = s.dx
            _c = 1 if s.flags & CF else 0
            _r = _a - _b - _c
            cpu.set_sub_flags(_a, _b, _r, 16, _c)
            s.bx = (_r & 0xFFFF) & 0xFFFF
            # 1010:1F6D  8bc1         mov
            s.ax = (s.cx) & 0xFFFF
            # 1010:1F6F  8bd3         mov
            s.dx = (s.bx) & 0xFFFF
            # 1010:1F71  a3ac54       mov moffs
            mem.ww(s.ds, 0x54AC, s.ax)
            # 1010:1F74  8916ae54     mov
            _o = 0x54AE
            mem.ww(s.ds, _o, s.dx)
            # 1010:1F78  52           push r16
            cpu.push(s.dx)
            # 1010:1F79  50           push r16
            cpu.push(s.ax)
            # 1010:1F7A  ff362caf     push rm16
            _o = 0xAF2C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F7E  ff361caf     push rm16
            _o = 0xAF1C
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F82  ff361a96     push rm16
            _o = 0x961A
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F86  ff361896     push rm16
            _o = 0x9618
            cpu.push(mem.rw(s.ds, _o))
            # 1010:1F8A  e840fd       call
            cpu.instruction_count += 15
            emulate_call(cpu, 0x1010, 0x1CCD, 0x1F8D)
            bb = 28
        elif bb == 28:
            # 1010:1F8D  83c410       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x10
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:1F90  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1F93  7503         jnz
            cpu.instruction_count += 3
            bb = 30 if cpu.condition(0x5) else 29
        elif bb == 29:
            # 1010:1F95  e90300       jmp
            cpu.instruction_count += 1
            bb = 31
        elif bb == 30:
            # 1010:1F98  e91800       jmp
            cpu.instruction_count += 1
            bb = 34
        elif bb == 31:
            # 1010:1F9B  8b46fc       mov
            _o = (s.bp - 0x4) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1F9E  8b56fe       mov
            _o = (s.bp - 0x2) & 0xFFFF
            s.dx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1FA1  a3ac54       mov moffs
            mem.ww(s.ds, 0x54AC, s.ax)
            # 1010:1FA4  8916ae54     mov
            _o = 0x54AE
            mem.ww(s.ds, _o, s.dx)
            # 1010:1FA8  83c701       grp1 rm16,imm8sx
            _a = s.di
            _b = 0x1
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.di = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 5
            bb = 32
        elif bb == 32:
            # 1010:1FAB  83ff06       grp1 rm16,imm8sx
            _a = s.di
            _b = 0x6
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1FAE  7f03         jg
            cpu.instruction_count += 2
            bb = 34 if cpu.condition(0xF) else 33
        elif bb == 33:
            # 1010:1FB0  e995fe       jmp
            cpu.instruction_count += 1
            bb = 5
        elif bb == 34:
            # 1010:1FB3  a1ac54       mov moffs
            s.ax = mem.rw(s.ds, 0x54AC)
            # 1010:1FB6  8b16ae54     mov
            _o = 0x54AE
            s.dx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:1FBA  2b46fc       sub
            _o = (s.bp - 0x4) & 0xFFFF
            _a = s.ax
            _b = mem.rw(s.ss, _o)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:1FBD  1b56fe       sbb
            _o = (s.bp - 0x2) & 0xFFFF
            _a = s.dx
            _b = mem.rw(s.ss, _o)
            _c = 1 if s.flags & CF else 0
            _r = _a - _b - _c
            cpu.set_sub_flags(_a, _b, _r, 16, _c)
            s.dx = (_r & 0xFFFF) & 0xFFFF
            # 1010:1FC0  a32eaf       mov moffs
            mem.ww(s.ds, 0xAF2E, s.ax)
            # 1010:1FC3  891630af     mov
            _o = 0xAF30
            mem.ww(s.ds, _o, s.dx)
            # 1010:1FC7  83ff06       grp1 rm16,imm8sx
            _a = s.di
            _b = 0x6
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:1FCA  7e03         jle
            cpu.instruction_count += 8
            bb = 36 if cpu.condition(0xE) else 35
        elif bb == 35:
            # 1010:1FCC  e90600       jmp
            cpu.instruction_count += 1
            bb = 37
        elif bb == 36:
            # 1010:1FCF  c7065a450100 mov rm16,imm16
            _o = 0x455A
            mem.ww(s.ds, _o, 0x1)
            cpu.instruction_count += 1
            bb = 37
        elif bb == 37:
            # 1010:1FD5  5f           pop r16
            s.di = cpu.pop()
            # 1010:1FD6  5e           pop r16
            s.si = cpu.pop()
            # 1010:1FD7  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:1FD8  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_1dfa.owns_time = True

