"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:5FEB  (11 instructions, 8 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x5FEB)
SIGNATURE = bytes.fromhex('b407cd21')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x5FEB, 1: 0x5FED, 2: 0x5FEF, 3: 0x5FF4, 4: 0x5FF8, 5: 0x5FFA, 6: 0x5FFC, 7: 0x6000}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:5FED": 1, "1010:5FEF": 2, "1010:5FFA": 5, "1010:5FFC": 6}


def lifted_1010_5feb(cpu, bb=0):
    """Lifted replacement for 1010:5FEB."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x5FEB, SIGNATURE, 'lifted_1010_5feb')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:5FEB  b407         mov r8,imm8
            cpu.set_reg8(4, 0x7)
            cpu.instruction_count += 1
            bb = 1
        elif bb == 1:
            # 1010:5FED  cd21         int
            cpu.instruction_count += 1
            emulate_int(cpu, 0x21, 0x1010, 0x5FEF)
            bb = 2
        elif bb == 2:
            # 1010:5FEF  25ff00       and
            _a = s.ax
            _b = 0xFF
            _r = _a & _b
            cpu.set_logic_flags(_r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:5FF2  7404         jz
            cpu.instruction_count += 2
            bb = 4 if cpu.condition(0x4) else 3
        elif bb == 3:
            # 1010:5FF4  3ce0         cmp
            _a = cpu.get_reg8(0)
            _b = 0xE0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:5FF6  7508         jnz
            cpu.instruction_count += 2
            bb = 7 if cpu.condition(0x5) else 4
        elif bb == 4:
            # 1010:5FF8  b407         mov r8,imm8
            cpu.set_reg8(4, 0x7)
            cpu.instruction_count += 1
            bb = 5
        elif bb == 5:
            # 1010:5FFA  cd21         int
            cpu.instruction_count += 1
            emulate_int(cpu, 0x21, 0x1010, 0x5FFC)
            bb = 6
        elif bb == 6:
            # 1010:5FFC  8ae0         mov
            cpu.set_reg8(4, cpu.get_reg8(0))
            # 1010:5FFE  b000         mov r8,imm8
            cpu.set_reg8(0, 0x0)
            cpu.instruction_count += 2
            bb = 7
        elif bb == 7:
            # 1010:6000  c3           ret
            cpu.instruction_count += 1
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_5feb.owns_time = True

