"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:4B8E  (57 instructions, 22 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x4B8E)
SIGNATURE = bytes.fromhex('c80c000056576800036a0068a831e868')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x4B8E, 1: 0x4B9F, 2: 0x4BA9, 3: 0x4BAC, 4: 0x4BAF, 5: 0x4BB9, 6: 0x4BC6, 7: 0x4BCF, 8: 0x4BD2, 9: 0x4BE0, 10: 0x4BE6, 11: 0x4BF4, 12: 0x4BF7, 13: 0x4BFA, 14: 0x4BFD, 15: 0x4C00, 16: 0x4C06, 17: 0x4C09, 18: 0x4C0F, 19: 0x4C12, 20: 0x4C16, 21: 0x4C1C}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:4B9F": 1, "1010:4BAF": 4, "1010:4BB9": 5, "1010:4BC6": 6, "1010:4BE0": 9, "1010:4BF4": 11, "1010:4BFA": 13, "1010:4C00": 15, "1010:4C16": 20, "1010:4C1C": 21}


def lifted_1010_4b8e(cpu, bb=0):
    """Lifted replacement for 1010:4B8E."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x4B8E, SIGNATURE, 'lifted_1010_4b8e')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:4B8E  c80c0000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            s.sp = (s.sp - 0xC) & 0xFFFF
            # 1010:4B92  56           push r16
            cpu.push(s.si)
            # 1010:4B93  57           push r16
            cpu.push(s.di)
            # 1010:4B94  680003       push imm16
            cpu.push(0x300)
            # 1010:4B97  6a00         push imm8
            cpu.push(0x0000)
            # 1010:4B99  68a831       push imm16
            cpu.push(0x31A8)
            # 1010:4B9C  e86811       call
            cpu.instruction_count += 7
            emulate_call(cpu, 0x1010, 0x5D07, 0x4B9F)
            bb = 1
        elif bb == 1:
            # 1010:4B9F  83c406       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x6
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:4BA2  833e3c0000   grp1 rm16,imm8sx
            _o = 0x003C
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:4BA7  7503         jnz
            cpu.instruction_count += 3
            bb = 3 if cpu.condition(0x5) else 2
        elif bb == 2:
            # 1010:4BA9  e95100       jmp
            cpu.instruction_count += 1
            bb = 14
        elif bb == 3:
            # 1010:4BAC  e871f3       call
            cpu.instruction_count += 1
            emulate_call(cpu, 0x1010, 0x3F20, 0x4BAF)
            bb = 4
        elif bb == 4:
            # 1010:4BAF  ff7604       push rm16
            _o = (s.bp + 0x4) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:4BB2  8d46fa       lea
            _o = (s.bp - 0x6) & 0xFFFF
            s.ax = _o
            # 1010:4BB5  50           push r16
            cpu.push(s.ax)
            # 1010:4BB6  e88aff       call
            cpu.instruction_count += 4
            emulate_call(cpu, 0x1010, 0x4B43, 0x4BB9)
            bb = 5
        elif bb == 5:
            # 1010:4BB9  83c404       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x4
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:4BBC  68a831       push imm16
            cpu.push(0x31A8)
            # 1010:4BBF  8d46f4       lea
            _o = (s.bp - 0xC) & 0xFFFF
            s.ax = _o
            # 1010:4BC2  50           push r16
            cpu.push(s.ax)
            # 1010:4BC3  e87dff       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x4B43, 0x4BC6)
            bb = 6
        elif bb == 6:
            # 1010:4BC6  83c404       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x4
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:4BC9  837e0600     grp1 rm16,imm8sx
            _o = (s.bp + 0x6) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:4BCD  7503         jnz
            cpu.instruction_count += 3
            bb = 8 if cpu.condition(0x5) else 7
        elif bb == 7:
            # 1010:4BCF  e91400       jmp
            cpu.instruction_count += 1
            bb = 10
        elif bb == 8:
            # 1010:4BD2  ff7608       push rm16
            _o = (s.bp + 0x8) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:4BD5  8d46fa       lea
            _o = (s.bp - 0x6) & 0xFFFF
            s.ax = _o
            # 1010:4BD8  50           push r16
            cpu.push(s.ax)
            # 1010:4BD9  8d46f4       lea
            _o = (s.bp - 0xC) & 0xFFFF
            s.ax = _o
            # 1010:4BDC  50           push r16
            cpu.push(s.ax)
            # 1010:4BDD  e851f7       call
            cpu.instruction_count += 6
            emulate_call(cpu, 0x1010, 0x4331, 0x4BE0)
            bb = 9
        elif bb == 9:
            # 1010:4BE0  83c406       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x6
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:4BE3  e91100       jmp
            cpu.instruction_count += 2
            bb = 12
        elif bb == 10:
            # 1010:4BE6  ff7608       push rm16
            _o = (s.bp + 0x8) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:4BE9  8d46f4       lea
            _o = (s.bp - 0xC) & 0xFFFF
            s.ax = _o
            # 1010:4BEC  50           push r16
            cpu.push(s.ax)
            # 1010:4BED  8d46fa       lea
            _o = (s.bp - 0x6) & 0xFFFF
            s.ax = _o
            # 1010:4BF0  50           push r16
            cpu.push(s.ax)
            # 1010:4BF1  e83df7       call
            cpu.instruction_count += 6
            emulate_call(cpu, 0x1010, 0x4331, 0x4BF4)
            bb = 11
        elif bb == 11:
            # 1010:4BF4  83c406       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x6
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 1
            bb = 12
        elif bb == 12:
            # 1010:4BF7  e841f3       call
            cpu.instruction_count += 1
            emulate_call(cpu, 0x1010, 0x3F3B, 0x4BFA)
            bb = 13
        elif bb == 13:
            # 1010:4BFA  e91f00       jmp
            cpu.instruction_count += 1
            bb = 21
        elif bb == 14:
            # 1010:4BFD  e80614       call
            cpu.instruction_count += 1
            emulate_call(cpu, 0x1010, 0x6006, 0x4C00)
            bb = 15
        elif bb == 15:
            # 1010:4C00  837e0600     grp1 rm16,imm8sx
            _o = (s.bp + 0x6) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:4C04  7503         jnz
            cpu.instruction_count += 2
            bb = 17 if cpu.condition(0x5) else 16
        elif bb == 16:
            # 1010:4C06  e90600       jmp
            cpu.instruction_count += 1
            bb = 18
        elif bb == 17:
            # 1010:4C09  b8e00b       mov r16,imm16
            s.ax = 0xBE0
            # 1010:4C0C  e90300       jmp
            cpu.instruction_count += 2
            bb = 19
        elif bb == 18:
            # 1010:4C0F  b8a831       mov r16,imm16
            s.ax = 0x31A8
            cpu.instruction_count += 1
            bb = 19
        elif bb == 19:
            # 1010:4C12  50           push r16
            cpu.push(s.ax)
            # 1010:4C13  e8ce15       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x61E4, 0x4C16)
            bb = 20
        elif bb == 20:
            # 1010:4C16  83c402       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x2
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:4C19  e8ea13       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x6006, 0x4C1C)
            bb = 21
        elif bb == 21:
            # 1010:4C1C  5f           pop r16
            s.di = cpu.pop()
            # 1010:4C1D  5e           pop r16
            s.si = cpu.pop()
            # 1010:4C1E  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:4C1F  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_4b8e.owns_time = True

