"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:1073  (64 instructions, 16 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x1073)
SIGNATURE = bytes.fromhex('c80c00005657833e3c00007503')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x1073, 1: 0x1080, 2: 0x1083, 3: 0x108C, 4: 0x1093, 5: 0x10A6, 6: 0x10CE, 7: 0x10D1, 8: 0x10D4, 9: 0x10E0, 10: 0x10EA, 11: 0x10F4, 12: 0x10F7, 13: 0x1103, 14: 0x110D, 15: 0x1110}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:10A6": 5, "1010:10D4": 8, "1010:10E0": 9, "1010:10EA": 10, "1010:1103": 13, "1010:110D": 14}


def lifted_1010_1073(cpu, bb=0):
    """Lifted replacement for 1010:1073."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x1073, SIGNATURE, 'lifted_1010_1073')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:1073  c80c0000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            s.sp = (s.sp - 0xC) & 0xFFFF
            # 1010:1077  56           push r16
            cpu.push(s.si)
            # 1010:1078  57           push r16
            cpu.push(s.di)
            # 1010:1079  833e3c0000   grp1 rm16,imm8sx
            _o = 0x003C
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:107E  7503         jnz
            cpu.instruction_count += 5
            bb = 2 if cpu.condition(0x5) else 1
        elif bb == 1:
            # 1010:1080  e90900       jmp
            cpu.instruction_count += 1
            bb = 3
        elif bb == 2:
            # 1010:1083  be6100       mov r16,imm16
            s.si = 0x61
            # 1010:1086  bf6200       mov r16,imm16
            s.di = 0x62
            # 1010:1089  e90700       jmp
            cpu.instruction_count += 3
            bb = 4
        elif bb == 3:
            # 1010:108C  bf0e00       mov r16,imm16
            s.di = 0xE
            # 1010:108F  8bc7         mov
            s.ax = (s.di) & 0xFFFF
            # 1010:1091  8bf0         mov
            s.si = (s.ax) & 0xFFFF
            cpu.instruction_count += 3
            bb = 4
        elif bb == 4:
            # 1010:1093  57           push r16
            cpu.push(s.di)
            # 1010:1094  56           push r16
            cpu.push(s.si)
            # 1010:1095  8b4608       mov
            _o = (s.bp + 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:1098  f76e0a       grp3 rm16
            _o = (s.bp + 0xA) & 0xFFFF
            _v = mem.rw(s.ss, _o)
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:109B  50           push r16
            cpu.push(s.ax)
            # 1010:109C  8b460c       mov
            _o = (s.bp + 0xC) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:109F  8cda         mov rm16,sreg
            s.dx = (s.ds) & 0xFFFF
            # 1010:10A1  52           push r16
            cpu.push(s.dx)
            # 1010:10A2  50           push r16
            cpu.push(s.ax)
            # 1010:10A3  e8bcfe       call
            cpu.instruction_count += 10
            emulate_call(cpu, 0x1010, 0x0F62, 0x10A6)
            bb = 5
        elif bb == 5:
            # 1010:10A6  83c40a       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0xA
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:10A9  a12aaf       mov moffs
            s.ax = mem.rw(s.ds, 0xAF2A)
            # 1010:10AC  8946f4       mov
            _o = (s.bp - 0xC) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:10AF  b84001       mov r16,imm16
            s.ax = 0x140
            # 1010:10B2  f76e06       grp3 rm16
            _o = (s.bp + 0x6) & 0xFFFF
            _v = mem.rw(s.ss, _o)
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:10B5  034604       add
            _o = (s.bp + 0x4) & 0xFFFF
            _a = s.ax
            _b = mem.rw(s.ss, _o)
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:10B8  8946f6       mov
            _o = (s.bp - 0xA) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:10BB  8b4608       mov
            _o = (s.bp + 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:10BE  8946fa       mov
            _o = (s.bp - 0x6) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:10C1  8b460a       mov
            _o = (s.bp + 0xA) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:10C4  8946f8       mov
            _o = (s.bp - 0x8) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:10C7  833e3c0000   grp1 rm16,imm8sx
            _o = 0x003C
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:10CC  7403         jz
            cpu.instruction_count += 13
            bb = 7 if cpu.condition(0x4) else 6
        elif bb == 6:
            # 1010:10CE  e90300       jmp
            cpu.instruction_count += 1
            bb = 8
        elif bb == 7:
            # 1010:10D1  e8c62b       call
            cpu.instruction_count += 1
            emulate_call(cpu, 0x1010, 0x3C9A, 0x10D4)
            bb = 8
        elif bb == 8:
            # 1010:10D4  6a00         push imm8
            cpu.push(0x0000)
            # 1010:10D6  6a00         push imm8
            cpu.push(0x0000)
            # 1010:10D8  6800a0       push imm16
            cpu.push(0xA000)
            # 1010:10DB  6a00         push imm8
            cpu.push(0x0000)
            # 1010:10DD  e89e30       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x417E, 0x10E0)
            bb = 9
        elif bb == 9:
            # 1010:10E0  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:10E3  8d46f4       lea
            _o = (s.bp - 0xC) & 0xFFFF
            s.ax = _o
            # 1010:10E6  50           push r16
            cpu.push(s.ax)
            # 1010:10E7  e81731       call
            cpu.instruction_count += 4
            emulate_call(cpu, 0x1010, 0x4201, 0x10EA)
            bb = 10
        elif bb == 10:
            # 1010:10EA  83c402       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x2
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:10ED  833e3c0000   grp1 rm16,imm8sx
            _o = 0x003C
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:10F2  7403         jz
            cpu.instruction_count += 3
            bb = 12 if cpu.condition(0x4) else 11
        elif bb == 11:
            # 1010:10F4  e91900       jmp
            cpu.instruction_count += 1
            bb = 15
        elif bb == 12:
            # 1010:10F7  6a00         push imm8
            cpu.push(0x0000)
            # 1010:10F9  6a00         push imm8
            cpu.push(0x0000)
            # 1010:10FB  6800a2       push imm16
            cpu.push(0xA200)
            # 1010:10FE  6a00         push imm8
            cpu.push(0x0000)
            # 1010:1100  e87b30       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x417E, 0x1103)
            bb = 13
        elif bb == 13:
            # 1010:1103  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:1106  8d46f4       lea
            _o = (s.bp - 0xC) & 0xFFFF
            s.ax = _o
            # 1010:1109  50           push r16
            cpu.push(s.ax)
            # 1010:110A  e8f430       call
            cpu.instruction_count += 4
            emulate_call(cpu, 0x1010, 0x4201, 0x110D)
            bb = 14
        elif bb == 14:
            # 1010:110D  83c402       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x2
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 1
            bb = 15
        elif bb == 15:
            # 1010:1110  5f           pop r16
            s.di = cpu.pop()
            # 1010:1111  5e           pop r16
            s.si = cpu.pop()
            # 1010:1112  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:1113  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_1073.owns_time = True

