"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:4084  (61 instructions, 12 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x4084)
SIGNATURE = bytes.fromhex('c806000056578b7604e8e624')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x4084, 1: 0x4090, 2: 0x409B, 3: 0x40AF, 4: 0x40BF, 5: 0x40CB, 6: 0x40D5, 7: 0x40D8, 8: 0x40FA, 9: 0x4100, 10: 0x4114, 11: 0x4117}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:4090": 1, "1010:409B": 2, "1010:40AF": 3, "1010:40BF": 4, "1010:40CB": 5, "1010:40FA": 8, "1010:4114": 10}


def lifted_1010_4084(cpu, bb=0):
    """Lifted replacement for 1010:4084."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x4084, SIGNATURE, 'lifted_1010_4084')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:4084  c8060000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            s.sp = (s.sp - 0x6) & 0xFFFF
            # 1010:4088  56           push r16
            cpu.push(s.si)
            # 1010:4089  57           push r16
            cpu.push(s.di)
            # 1010:408A  8b7604       mov
            _o = (s.bp + 0x4) & 0xFFFF
            s.si = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:408D  e8e624       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x6576, 0x4090)
            bb = 1
        elif bb == 1:
            # 1010:4090  6a08         push imm8
            cpu.push(0x0008)
            # 1010:4092  8bc6         mov
            s.ax = (s.si) & 0xFFFF
            # 1010:4094  8cda         mov rm16,sreg
            s.dx = (s.ds) & 0xFFFF
            # 1010:4096  52           push r16
            cpu.push(s.dx)
            # 1010:4097  50           push r16
            cpu.push(s.ax)
            # 1010:4098  e8fa24       call
            cpu.instruction_count += 6
            emulate_call(cpu, 0x1010, 0x6595, 0x409B)
            bb = 2
        elif bb == 2:
            # 1010:409B  83c406       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x6
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:409E  8b4404       mov
            _o = (s.si + 0x4) & 0xFFFF
            s.ax = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:40A1  f76c06       grp3 rm16
            _o = (s.si + 0x6) & 0xFFFF
            _v = mem.rw(s.ds, _o)
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:40A4  8946fe       mov
            _o = (s.bp - 0x2) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:40A7  ba0000       mov r16,imm16
            s.dx = 0x0
            # 1010:40AA  52           push r16
            cpu.push(s.dx)
            # 1010:40AB  50           push r16
            cpu.push(s.ax)
            # 1010:40AC  e845fe       call
            cpu.instruction_count += 8
            emulate_call(cpu, 0x1010, 0x3EF4, 0x40AF)
            bb = 3
        elif bb == 3:
            # 1010:40AF  83c404       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x4
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:40B2  8904         mov
            _o = (s.si) & 0xFFFF
            mem.ww(s.ds, _o, s.ax)
            # 1010:40B4  8946fc       mov
            _o = (s.bp - 0x4) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:40B7  c746fa0000   mov rm16,imm16
            _o = (s.bp - 0x6) & 0xFFFF
            mem.ww(s.ss, _o, 0x0)
            # 1010:40BC  e8aabf       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x0069, 0x40BF)
            bb = 4
        elif bb == 4:
            # 1010:40BF  ff76fe       push rm16
            _o = (s.bp - 0x2) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:40C2  ff76fc       push rm16
            _o = (s.bp - 0x4) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:40C5  ff76fa       push rm16
            _o = (s.bp - 0x6) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:40C8  e81b26       call
            cpu.instruction_count += 4
            emulate_call(cpu, 0x1010, 0x66E6, 0x40CB)
            bb = 5
        elif bb == 5:
            # 1010:40CB  83c406       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x6
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:40CE  833e3c0000   grp1 rm16,imm8sx
            _o = 0x003C
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:40D3  7403         jz
            cpu.instruction_count += 3
            bb = 7 if cpu.condition(0x4) else 6
        elif bb == 6:
            # 1010:40D5  e92800       jmp
            cpu.instruction_count += 1
            bb = 9
        elif bb == 7:
            # 1010:40D8  b94001       mov r16,imm16
            s.cx = 0x140
            # 1010:40DB  8b4402       mov
            _o = (s.si + 0x2) & 0xFFFF
            s.ax = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:40DE  2bd2         sub
            _a = s.dx
            _b = s.dx
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.dx = (_r & 0xFFFF) & 0xFFFF
            # 1010:40E0  f7f1         grp3 rm16
            _v = s.cx
            if _v == 0:
                raise ZeroDivisionError('div by zero')
            _q, _r = divmod(((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF), _v & 0xFFFF)
            if _q > 0xFFFF:
                raise OverflowError('16-bit div quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:40E2  250100       and
            _a = s.ax
            _b = 0x1
            _r = _a & _b
            cpu.set_logic_flags(_r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:40E5  8b4c02       mov
            _o = (s.si + 0x2) & 0xFFFF
            s.cx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:40E8  83e101       grp1 rm16,imm8sx
            _a = s.cx
            _b = 0x1
            _r = _a & _b
            cpu.set_logic_flags(_r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:40EB  33c8         xor
            _a = s.cx
            _b = s.ax
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:40ED  51           push r16
            cpu.push(s.cx)
            # 1010:40EE  ff7406       push rm16
            _o = (s.si + 0x6) & 0xFFFF
            cpu.push(mem.rw(s.ds, _o))
            # 1010:40F1  ff7404       push rm16
            _o = (s.si + 0x4) & 0xFFFF
            cpu.push(mem.rw(s.ds, _o))
            # 1010:40F4  8b04         mov
            _o = (s.si) & 0xFFFF
            s.ax = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:40F6  50           push r16
            cpu.push(s.ax)
            # 1010:40F7  e8a4fc       call
            cpu.instruction_count += 14
            emulate_call(cpu, 0x1010, 0x3D9E, 0x40FA)
            bb = 8
        elif bb == 8:
            # 1010:40FA  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:40FD  e91700       jmp
            cpu.instruction_count += 2
            bb = 11
        elif bb == 9:
            # 1010:4100  ff7606       push rm16
            _o = (s.bp + 0x6) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:4103  8b46fe       mov
            _o = (s.bp - 0x2) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:4106  ba0000       mov r16,imm16
            s.dx = 0x0
            # 1010:4109  52           push r16
            cpu.push(s.dx)
            # 1010:410A  50           push r16
            cpu.push(s.ax)
            # 1010:410B  ff76fc       push rm16
            _o = (s.bp - 0x4) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:410E  ff76fa       push rm16
            _o = (s.bp - 0x6) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:4111  e83eff       call
            cpu.instruction_count += 8
            emulate_call(cpu, 0x1010, 0x4052, 0x4114)
            bb = 10
        elif bb == 10:
            # 1010:4114  83c40a       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0xA
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 1
            bb = 11
        elif bb == 11:
            # 1010:4117  5f           pop r16
            s.di = cpu.pop()
            # 1010:4118  5e           pop r16
            s.si = cpu.pop()
            # 1010:4119  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:411A  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_4084.owns_time = True

