"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:61F3  (151 instructions, 38 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x61F3)
SIGNATURE = bytes.fromhex('bf86168edf8c06c00cb430cd21')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x61F3, 1: 0x61FE, 2: 0x6200, 3: 0x620A, 4: 0x620E, 5: 0x6214, 6: 0x6219, 7: 0x621B, 8: 0x621D, 9: 0x6238, 10: 0x623A, 11: 0x624C, 12: 0x6256, 13: 0x6290, 14: 0x629D, 15: 0x62A2, 16: 0x62A6, 17: 0x62AA, 18: 0x62AE, 19: 0x62AF, 20: 0x62B4, 21: 0x62B8, 22: 0x62BC, 23: 0x62C0, 24: 0x62C6, 25: 0x62D1, 26: 0x62D6, 27: 0x62DA, 28: 0x62DE, 29: 0x62E3, 30: 0x62E7, 31: 0x62EB, 32: 0x62F1, 33: 0x630B, 34: 0x630D, 35: 0x630F, 36: 0x631D, 37: 0x6321}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:61FE": 1, "1010:6200": 2, "1010:6219": 6, "1010:621B": 7, "1010:6238": 9, "1010:623A": 10, "1010:630B": 33, "1010:630D": 34, "1010:630F": 35, "1010:631D": 36, "1010:6321": 37}


def lifted_1010_61f3(cpu, bb=0):
    """Lifted replacement for 1010:61F3."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x61F3, SIGNATURE, 'lifted_1010_61f3')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:61F3  bf8616       mov r16,imm16
            s.di = 0x1686
            # 1010:61F6  8edf         mov sreg,rm16
            cpu.set_sreg(3, s.di)
            # 1010:61F8  8c06c00c     mov rm16,sreg
            _o = 0x0CC0
            mem.ww(s.ds, _o, s.es)
            # 1010:61FC  b430         mov r8,imm8
            cpu.set_reg8(4, 0x30)
            cpu.instruction_count += 4
            bb = 1
        elif bb == 1:
            # 1010:61FE  cd21         int
            cpu.instruction_count += 1
            emulate_int(cpu, 0x21, 0x1010, 0x6200)
            bb = 2
        elif bb == 2:
            # 1010:6200  86c4         xchg rm8,r8
            _a = cpu.get_reg8(0)
            _b = cpu.get_reg8(4)
            cpu.set_reg8(0, _b)
            cpu.set_reg8(4, _a)
            # 1010:6202  a3be0c       mov moffs
            mem.ww(s.ds, 0x0CBE, s.ax)
            # 1010:6205  80fc03       grp1 rm8,imm8
            _a = cpu.get_reg8(4)
            _b = 0x3
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:6208  7304         jnb
            cpu.instruction_count += 4
            bb = 4 if cpu.condition(0x3) else 3
        elif bb == 3:
            # 1010:620A  06           push es
            cpu.push(s.es)
            # 1010:620B  6a00         push imm8
            cpu.push(0x0000)
            # 1010:620D  cb           retf
            cpu.instruction_count += 3
            s.ip = cpu.pop()
            s.cs = cpu.pop()
            return
        elif bb == 4:
            # 1010:620E  b121         mov r8,imm8
            cpu.set_reg8(1, 0x21)
            # 1010:6210  d3e8         shift
            _r = cpu.shift(5, s.ax, s.cx & 0xFF, 16)
            s.ax = (_r) & 0xFFFF
            # 1010:6212  7509         jnz
            cpu.instruction_count += 3
            bb = 8 if cpu.condition(0x5) else 5
        elif bb == 5:
            # 1010:6214  ba0700       mov r16,imm16
            s.dx = 0x7
            # 1010:6217  b409         mov r8,imm8
            cpu.set_reg8(4, 0x9)
            cpu.instruction_count += 2
            bb = 6
        elif bb == 6:
            # 1010:6219  cd21         int
            cpu.instruction_count += 1
            emulate_int(cpu, 0x21, 0x1010, 0x621B)
            bb = 7
        elif bb == 7:
            # 1010:621B  ebed         jmp short
            cpu.instruction_count += 1
            bb = 3
        elif bb == 8:
            # 1010:621D  fa           cli
            cpu.set_flag(IF, False)
            # 1010:621E  8ed7         mov sreg,rm16
            cpu.set_sreg(2, s.di)
            # 1010:6220  81c440b1     grp1 rm16,imm16
            _a = s.sp
            _b = 0xB140
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:6224  fb           sti
            cpu.set_flag(IF, True)
            # 1010:6225  8bdc         mov
            s.bx = (s.sp) & 0xFFFF
            # 1010:6227  83c30f       grp1 rm16,imm8sx
            _a = s.bx
            _b = 0xF
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.bx = (_r & 0xFFFF) & 0xFFFF
            # 1010:622A  c1eb04       shift rm16,imm8
            _r = cpu.shift(5, s.bx, 0x04, 16)
            s.bx = (_r) & 0xFFFF
            # 1010:622D  03df         add
            _a = s.bx
            _b = s.di
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.bx = (_r & 0xFFFF) & 0xFFFF
            # 1010:622F  a1c00c       mov moffs
            s.ax = mem.rw(s.ds, 0x0CC0)
            # 1010:6232  2bd8         sub
            _a = s.bx
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.bx = (_r & 0xFFFF) & 0xFFFF
            # 1010:6234  8ec0         mov sreg,rm16
            cpu.set_sreg(0, s.ax)
            # 1010:6236  b44a         mov r8,imm8
            cpu.set_reg8(4, 0x4A)
            cpu.instruction_count += 12
            bb = 9
        elif bb == 9:
            # 1010:6238  cd21         int
            cpu.instruction_count += 1
            emulate_int(cpu, 0x21, 0x1010, 0x623A)
            bb = 10
        elif bb == 10:
            # 1010:623A  fc           cld
            cpu.set_flag(DF, False)
            # 1010:623B  fa           cli
            cpu.set_flag(IF, False)
            # 1010:623C  8e1ec00c     mov sreg,rm16
            _o = 0x0CC0
            cpu.set_sreg(3, mem.rw(s.ds, _o))
            # 1010:6240  a12c00       mov moffs
            s.ax = mem.rw(s.ds, 0x002C)
            # 1010:6243  8ec0         mov sreg,rm16
            cpu.set_sreg(0, s.ax)
            # 1010:6245  8ed8         mov sreg,rm16
            cpu.set_sreg(3, s.ax)
            # 1010:6247  33ff         xor
            _a = s.di
            _b = s.di
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 16)
            s.di = (_r & 0xFFFF) & 0xFFFF
            # 1010:6249  b90080       mov r16,imm16
            s.cx = 0x8000
            cpu.instruction_count += 8
            bb = 11
        elif bb == 11:
            # 1010:624C  33c0         xor
            _a = s.ax
            _b = s.ax
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:624E  f2ae         stos/lods/scas
            cpu.string_op(0xAE, 0xF2, None)
            # 1010:6250  47           inc r16
            _old = s.di
            _r = (_old + 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=False)
            s.di = _r
            # 1010:6251  3845ff       cmp
            _o = (s.di - 0x1) & 0xFFFF
            _a = mem.rb(s.ds, _o)
            _b = cpu.get_reg8(0)
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:6254  75f6         jnz
            cpu.instruction_count += 5
            bb = 11 if cpu.condition(0x5) else 12
        elif bb == 12:
            # 1010:6256  8d7502       lea
            _o = (s.di + 0x2) & 0xFFFF
            s.si = _o
            # 1010:6259  8bfe         mov
            s.di = (s.si) & 0xFFFF
            # 1010:625B  b90001       mov r16,imm16
            s.cx = 0x100
            # 1010:625E  32c0         xor
            _a = cpu.get_reg8(0)
            _b = cpu.get_reg8(0)
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 8)
            cpu.set_reg8(0, _r & 0xFF)
            # 1010:6260  f2ae         stos/lods/scas
            cpu.string_op(0xAE, 0xF2, None)
            # 1010:6262  2bfe         sub
            _a = s.di
            _b = s.si
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.di = (_r & 0xFFFF) & 0xFFFF
            # 1010:6264  8bcf         mov
            s.cx = (s.di) & 0xFFFF
            # 1010:6266  2be1         sub
            _a = s.sp
            _b = s.cx
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:6268  8bfc         mov
            s.di = (s.sp) & 0xFFFF
            # 1010:626A  8bef         mov
            s.bp = (s.di) & 0xFFFF
            # 1010:626C  16           push ss
            cpu.push(s.ss)
            # 1010:626D  07           pop es
            cpu.set_sreg(0, cpu.pop())
            # 1010:626E  f3a4         movs/cmps
            cpu.string_op(0xA4, 0xF3, None)
            # 1010:6270  16           push ss
            cpu.push(s.ss)
            # 1010:6271  1f           pop ds
            cpu.set_sreg(3, cpu.pop())
            # 1010:6272  8e1ec00c     mov sreg,rm16
            _o = 0x0CC0
            cpu.set_sreg(3, mem.rw(s.ds, _o))
            # 1010:6276  32ed         xor
            _a = cpu.get_reg8(5)
            _b = cpu.get_reg8(5)
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 8)
            cpu.set_reg8(5, _r & 0xFF)
            # 1010:6278  8bfc         mov
            s.di = (s.sp) & 0xFFFF
            # 1010:627A  be8100       mov r16,imm16
            s.si = 0x81
            # 1010:627D  8a0e8000     mov
            _o = 0x0080
            cpu.set_reg8(1, mem.rb(s.ds, _o))
            # 1010:6281  8bd1         mov
            s.dx = (s.cx) & 0xFFFF
            # 1010:6283  2bf9         sub
            _a = s.di
            _b = s.cx
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.di = (_r & 0xFFFF) & 0xFFFF
            # 1010:6285  4f           dec r16
            _old = s.di
            _r = (_old - 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=True)
            s.di = _r
            # 1010:6286  83e7fe       grp1 rm16,imm8sx
            _a = s.di
            _b = 0xFFFE
            _r = _a & _b
            cpu.set_logic_flags(_r, 16)
            s.di = (_r & 0xFFFF) & 0xFFFF
            # 1010:6289  8be7         mov
            s.sp = (s.di) & 0xFFFF
            # 1010:628B  fb           sti
            cpu.set_flag(IF, True)
            # 1010:628C  0bc9         or
            _a = s.cx
            _b = s.cx
            _r = _a | _b
            cpu.set_logic_flags(_r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:628E  7461         jz
            cpu.instruction_count += 28
            bb = 32 if cpu.condition(0x4) else 13
        elif bb == 13:
            # 1010:6290  8bdf         mov
            s.bx = (s.di) & 0xFFFF
            # 1010:6292  f3a4         movs/cmps
            cpu.string_op(0xA4, 0xF3, None)
            # 1010:6294  32c0         xor
            _a = cpu.get_reg8(0)
            _b = cpu.get_reg8(0)
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 8)
            cpu.set_reg8(0, _r & 0xFF)
            # 1010:6296  aa           stos/lods/scas
            cpu.string_op(0xAA, None, None)
            # 1010:6297  16           push ss
            cpu.push(s.ss)
            # 1010:6298  1f           pop ds
            cpu.set_sreg(3, cpu.pop())
            # 1010:6299  8bf3         mov
            s.si = (s.bx) & 0xFFFF
            # 1010:629B  33c9         xor
            _a = s.cx
            _b = s.cx
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 8
            bb = 14
        elif bb == 14:
            # 1010:629D  ac           stos/lods/scas
            cpu.string_op(0xAC, None, None)
            # 1010:629E  3c20         cmp
            _a = cpu.get_reg8(0)
            _b = 0x20
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:62A0  74fb         jz
            cpu.instruction_count += 3
            bb = 14 if cpu.condition(0x4) else 15
        elif bb == 15:
            # 1010:62A2  3c09         cmp
            _a = cpu.get_reg8(0)
            _b = 0x9
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:62A4  74f7         jz
            cpu.instruction_count += 2
            bb = 14 if cpu.condition(0x4) else 16
        elif bb == 16:
            # 1010:62A6  3c0d         cmp
            _a = cpu.get_reg8(0)
            _b = 0xD
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:62A8  741c         jz
            cpu.instruction_count += 2
            bb = 24 if cpu.condition(0x4) else 17
        elif bb == 17:
            # 1010:62AA  0ac0         or
            _a = cpu.get_reg8(0)
            _b = cpu.get_reg8(0)
            _r = _a | _b
            cpu.set_logic_flags(_r, 8)
            cpu.set_reg8(0, _r & 0xFF)
            # 1010:62AC  7418         jz
            cpu.instruction_count += 2
            bb = 24 if cpu.condition(0x4) else 18
        elif bb == 18:
            # 1010:62AE  41           inc r16
            _old = s.cx
            _r = (_old + 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=False)
            s.cx = _r
            cpu.instruction_count += 1
            bb = 19
        elif bb == 19:
            # 1010:62AF  ac           stos/lods/scas
            cpu.string_op(0xAC, None, None)
            # 1010:62B0  3c0d         cmp
            _a = cpu.get_reg8(0)
            _b = 0xD
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:62B2  7412         jz
            cpu.instruction_count += 3
            bb = 24 if cpu.condition(0x4) else 20
        elif bb == 20:
            # 1010:62B4  0ac0         or
            _a = cpu.get_reg8(0)
            _b = cpu.get_reg8(0)
            _r = _a | _b
            cpu.set_logic_flags(_r, 8)
            cpu.set_reg8(0, _r & 0xFF)
            # 1010:62B6  740e         jz
            cpu.instruction_count += 2
            bb = 24 if cpu.condition(0x4) else 21
        elif bb == 21:
            # 1010:62B8  3c20         cmp
            _a = cpu.get_reg8(0)
            _b = 0x20
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:62BA  7404         jz
            cpu.instruction_count += 2
            bb = 23 if cpu.condition(0x4) else 22
        elif bb == 22:
            # 1010:62BC  3c09         cmp
            _a = cpu.get_reg8(0)
            _b = 0x9
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:62BE  75ef         jnz
            cpu.instruction_count += 2
            bb = 19 if cpu.condition(0x5) else 23
        elif bb == 23:
            # 1010:62C0  c644ff00     mov rm8,imm8
            _o = (s.si - 0x1) & 0xFFFF
            mem.wb(s.ds, _o, 0x0)
            # 1010:62C4  ebd7         jmp short
            cpu.instruction_count += 2
            bb = 14
        elif bb == 24:
            # 1010:62C6  4e           dec r16
            _old = s.si
            _r = (_old - 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=True)
            s.si = _r
            # 1010:62C7  c60400       mov rm8,imm8
            _o = (s.si) & 0xFFFF
            mem.wb(s.ds, _o, 0x0)
            # 1010:62CA  fd           std
            cpu.set_flag(DF, True)
            # 1010:62CB  8bd1         mov
            s.dx = (s.cx) & 0xFFFF
            # 1010:62CD  0bc9         or
            _a = s.cx
            _b = s.cx
            _r = _a | _b
            cpu.set_logic_flags(_r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:62CF  7420         jz
            cpu.instruction_count += 6
            bb = 32 if cpu.condition(0x4) else 25
        elif bb == 25:
            # 1010:62D1  ac           stos/lods/scas
            cpu.string_op(0xAC, None, None)
            # 1010:62D2  3c20         cmp
            _a = cpu.get_reg8(0)
            _b = 0x20
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:62D4  74fb         jz
            cpu.instruction_count += 3
            bb = 25 if cpu.condition(0x4) else 26
        elif bb == 26:
            # 1010:62D6  3c09         cmp
            _a = cpu.get_reg8(0)
            _b = 0x9
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:62D8  74f7         jz
            cpu.instruction_count += 2
            bb = 25 if cpu.condition(0x4) else 27
        elif bb == 27:
            # 1010:62DA  0ac0         or
            _a = cpu.get_reg8(0)
            _b = cpu.get_reg8(0)
            _r = _a | _b
            cpu.set_logic_flags(_r, 8)
            cpu.set_reg8(0, _r & 0xFF)
            # 1010:62DC  74f3         jz
            cpu.instruction_count += 2
            bb = 25 if cpu.condition(0x4) else 28
        elif bb == 28:
            # 1010:62DE  ac           stos/lods/scas
            cpu.string_op(0xAC, None, None)
            # 1010:62DF  3c20         cmp
            _a = cpu.get_reg8(0)
            _b = 0x20
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:62E1  7408         jz
            cpu.instruction_count += 3
            bb = 31 if cpu.condition(0x4) else 29
        elif bb == 29:
            # 1010:62E3  3c09         cmp
            _a = cpu.get_reg8(0)
            _b = 0x9
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:62E5  7404         jz
            cpu.instruction_count += 2
            bb = 31 if cpu.condition(0x4) else 30
        elif bb == 30:
            # 1010:62E7  0ac0         or
            _a = cpu.get_reg8(0)
            _b = cpu.get_reg8(0)
            _r = _a | _b
            cpu.set_logic_flags(_r, 8)
            cpu.set_reg8(0, _r & 0xFF)
            # 1010:62E9  75f3         jnz
            cpu.instruction_count += 2
            bb = 28 if cpu.condition(0x5) else 31
        elif bb == 31:
            # 1010:62EB  8d5c02       lea
            _o = (s.si + 0x2) & 0xFFFF
            s.bx = _o
            # 1010:62EE  53           push r16
            cpu.push(s.bx)
            # 1010:62EF  e2e0         loop
            cpu.instruction_count += 3
            s.cx = (s.cx - 1) & 0xFFFF
            bb = 25 if (s.cx != 0) else 32
        elif bb == 32:
            # 1010:62F1  55           push r16
            cpu.push(s.bp)
            # 1010:62F2  8bc4         mov
            s.ax = (s.sp) & 0xFFFF
            # 1010:62F4  50           push r16
            cpu.push(s.ax)
            # 1010:62F5  42           inc r16
            _old = s.dx
            _r = (_old + 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=False)
            s.dx = _r
            # 1010:62F6  52           push r16
            cpu.push(s.dx)
            # 1010:62F7  16           push ss
            cpu.push(s.ss)
            # 1010:62F8  1f           pop ds
            cpu.set_sreg(3, cpu.pop())
            # 1010:62F9  fc           cld
            cpu.set_flag(DF, False)
            # 1010:62FA  bf1c0e       mov r16,imm16
            s.di = 0xE1C
            # 1010:62FD  b940b1       mov r16,imm16
            s.cx = 0xB140
            # 1010:6300  2bcf         sub
            _a = s.cx
            _b = s.di
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:6302  32c0         xor
            _a = cpu.get_reg8(0)
            _b = cpu.get_reg8(0)
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 8)
            cpu.set_reg8(0, _r & 0xFF)
            # 1010:6304  f3aa         stos/lods/scas
            cpu.string_op(0xAA, 0xF3, None)
            # 1010:6306  33ed         xor
            _a = s.bp
            _b = s.bp
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 16)
            s.bp = (_r & 0xFFFF) & 0xFFFF
            # 1010:6308  e8ad9e       call
            cpu.instruction_count += 15
            emulate_call(cpu, 0x1010, 0x01B8, 0x630B)
            bb = 33
        elif bb == 33:
            # 1010:630B  b44c         mov r8,imm8
            cpu.set_reg8(4, 0x4C)
            cpu.instruction_count += 1
            bb = 34
        elif bb == 34:
            # 1010:630D  cd21         int
            cpu.instruction_count += 1
            emulate_int(cpu, 0x21, 0x1010, 0x630F)
            bb = 35
        elif bb == 35:
            # 1010:630F  8bdc         mov
            s.bx = (s.sp) & 0xFFFF
            # 1010:6311  ff7704       push rm16
            _o = (s.bx + 0x4) & 0xFFFF
            cpu.push(mem.rw(s.ds, _o))
            # 1010:6314  ff7702       push rm16
            _o = (s.bx + 0x2) & 0xFFFF
            cpu.push(mem.rw(s.ds, _o))
            # 1010:6317  680700       push imm16
            cpu.push(0x7)
            # 1010:631A  e8effb       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x5F0C, 0x631D)
            bb = 36
        elif bb == 36:
            # 1010:631D  50           push r16
            cpu.push(s.ax)
            # 1010:631E  e861f9       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x5C82, 0x6321)
            bb = 37
        elif bb == 37:
            # 1010:6321  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:6324  c3           ret
            cpu.instruction_count += 2
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_61f3.owns_time = True

