"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:3ACC  (25 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x3ACC)
SIGNATURE = bytes.fromhex('6a000726a12000268b1622002ea3673b')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x3ACC}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches


def lifted_1010_3acc(cpu, bb=0):
    """Lifted replacement for 1010:3ACC."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x3ACC, SIGNATURE, 'lifted_1010_3acc')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:3ACC  6a00         push imm8
            cpu.push(0x0000)
            # 1010:3ACE  07           pop es
            cpu.set_sreg(0, cpu.pop())
            # 1010:3ACF  26a12000     mov moffs
            s.ax = mem.rw(s.es, 0x0020)
            # 1010:3AD3  268b162200   mov
            _o = 0x0022
            s.dx = (mem.rw(s.es, _o)) & 0xFFFF
            # 1010:3AD8  2ea3673b     mov moffs
            mem.ww(s.cs, 0x3B67, s.ax)
            # 1010:3ADC  2e8916693b   mov
            _o = 0x3B69
            mem.ww(s.cs, _o, s.dx)
            # 1010:3AE1  fa           cli
            cpu.set_flag(IF, False)
            # 1010:3AE2  26c7062000173b mov rm16,imm16
            _o = 0x0020
            mem.ww(s.es, _o, 0x3B17)
            # 1010:3AE9  268c0e2200   mov rm16,sreg
            _o = 0x0022
            mem.ww(s.es, _o, s.cs)
            # 1010:3AEE  26c7069000143b mov rm16,imm16
            _o = 0x0090
            mem.ww(s.es, _o, 0x3B14)
            # 1010:3AF5  268c0e9200   mov rm16,sreg
            _o = 0x0092
            mem.ww(s.es, _o, s.cs)
            # 1010:3AFA  b036         mov r8,imm8
            cpu.set_reg8(0, 0x36)
            # 1010:3AFC  e643         out imm8,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (0x43) & 0xFFFF, _val, 8)
            # 1010:3AFE  b0e4         mov r8,imm8
            cpu.set_reg8(0, 0xE4)
            # 1010:3B00  e640         out imm8,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (0x40) & 0xFFFF, _val, 8)
            # 1010:3B02  b019         mov r8,imm8
            cpu.set_reg8(0, 0x19)
            # 1010:3B04  e640         out imm8,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (0x40) & 0xFFFF, _val, 8)
            # 1010:3B06  b0b6         mov r8,imm8
            cpu.set_reg8(0, 0xB6)
            # 1010:3B08  e643         out imm8,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (0x43) & 0xFFFF, _val, 8)
            # 1010:3B0A  b002         mov r8,imm8
            cpu.set_reg8(0, 0x2)
            # 1010:3B0C  e642         out imm8,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (0x42) & 0xFFFF, _val, 8)
            # 1010:3B0E  b000         mov r8,imm8
            cpu.set_reg8(0, 0x0)
            # 1010:3B10  e642         out imm8,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (0x42) & 0xFFFF, _val, 8)
            # 1010:3B12  fb           sti
            cpu.set_flag(IF, True)
            # 1010:3B13  c3           ret
            cpu.instruction_count += 25
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_3acc.owns_time = True

