"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:5C77  (13 instructions, 8 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x5C77)
SIGNATURE = bytes.fromhex('8bdc8b5702b8003de976ff')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x5BF8, 1: 0x5BFF, 2: 0x5C01, 3: 0x5C03, 4: 0x5C0A, 5: 0x5C0D, 6: 0x5C10, 7: 0x5C77}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:5BFF": 1, "1010:5C01": 2}


def lifted_1010_5c77(cpu, bb=7):
    """Lifted replacement for 1010:5C77."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x5C77, SIGNATURE, 'lifted_1010_5c77')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:5BF8  833eaa4100   grp1 rm16,imm8sx
            _o = 0x41AA
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:5BFD  750e         jnz
            cpu.instruction_count += 2
            bb = 5 if cpu.condition(0x5) else 1
        elif bb == 1:
            # 1010:5BFF  cd21         int
            cpu.instruction_count += 1
            emulate_int(cpu, 0x21, 0x1010, 0x5C01)
            bb = 2
        elif bb == 2:
            # 1010:5C01  730d         jnb
            cpu.instruction_count += 1
            bb = 6 if cpu.condition(0x3) else 3
        elif bb == 3:
            # 1010:5C03  833eaa4100   grp1 rm16,imm8sx
            _o = 0x41AA
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:5C08  7503         jnz
            cpu.instruction_count += 2
            bb = 5 if cpu.condition(0x5) else 4
        elif bb == 4:
            # 1010:5C0A  a3aa41       mov moffs
            mem.ww(s.ds, 0x41AA, s.ax)
            cpu.instruction_count += 1
            bb = 5
        elif bb == 5:
            # 1010:5C0D  b8ffff       mov r16,imm16
            s.ax = 0xFFFF
            cpu.instruction_count += 1
            bb = 6
        elif bb == 6:
            # 1010:5C10  c3           ret
            cpu.instruction_count += 1
            s.ip = cpu.pop()
            return
        elif bb == 7:
            # 1010:5C77  8bdc         mov
            s.bx = (s.sp) & 0xFFFF
            # 1010:5C79  8b5702       mov
            _o = (s.bx + 0x2) & 0xFFFF
            s.dx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:5C7C  b8003d       mov r16,imm16
            s.ax = 0x3D00
            # 1010:5C7F  e976ff       jmp
            cpu.instruction_count += 4
            bb = 0
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_5c77.owns_time = True

