"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:4331  (101 instructions, 24 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x4331)
SIGNATURE = bytes.fromhex('c81600005657833e3c00007403')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x4331, 1: 0x433E, 2: 0x4341, 3: 0x4344, 4: 0x434A, 5: 0x434E, 6: 0x4350, 7: 0x4353, 8: 0x4365, 9: 0x436A, 10: 0x4370, 11: 0x4373, 12: 0x437A, 13: 0x437D, 14: 0x4382, 15: 0x43A9, 16: 0x43DB, 17: 0x43F1, 18: 0x43F4, 19: 0x4430, 20: 0x4446, 21: 0x444C, 22: 0x4452, 23: 0x4455}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:434A": 4, "1010:434E": 5, "1010:4446": 20, "1010:444C": 21}


def lifted_1010_4331(cpu, bb=0):
    """Lifted replacement for 1010:4331."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x4331, SIGNATURE, 'lifted_1010_4331')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:4331  c8160000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            s.sp = (s.sp - 0x16) & 0xFFFF
            # 1010:4335  56           push r16
            cpu.push(s.si)
            # 1010:4336  57           push r16
            cpu.push(s.di)
            # 1010:4337  833e3c0000   grp1 rm16,imm8sx
            _o = 0x003C
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:433C  7403         jz
            cpu.instruction_count += 5
            bb = 2 if cpu.condition(0x4) else 1
        elif bb == 1:
            # 1010:433E  e90300       jmp
            cpu.instruction_count += 1
            bb = 3
        elif bb == 2:
            # 1010:4341  e91101       jmp
            cpu.instruction_count += 1
            bb = 23
        elif bb == 3:
            # 1010:4344  c70600160000 mov rm16,imm16
            _o = 0x1600
            mem.ww(s.ds, _o, 0x0)
            cpu.instruction_count += 1
            bb = 4
        elif bb == 4:
            # 1010:434A  837e0800     grp1 rm16,imm8sx
            _o = (s.bp + 0x8) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            cpu.instruction_count += 1
            if cpu.boundary_hook is not None:
                cpu.boundary_hook(cpu, 0x1010, 0x434A, 0x434E)
            bb = 5
        elif bb == 5:
            # 1010:434E  7503         jnz
            cpu.instruction_count += 1
            bb = 7 if cpu.condition(0x5) else 6
        elif bb == 6:
            # 1010:4350  e91200       jmp
            cpu.instruction_count += 1
            bb = 8
        elif bb == 7:
            # 1010:4353  b86400       mov r16,imm16
            s.ax = 0x64
            # 1010:4356  f72e0016     grp3 rm16
            _o = 0x1600
            _v = mem.rw(s.ds, _o)
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:435A  2bd2         sub
            _a = s.dx
            _b = s.dx
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.dx = (_r & 0xFFFF) & 0xFFFF
            # 1010:435C  f77608       grp3 rm16
            _o = (s.bp + 0x8) & 0xFFFF
            _v = mem.rw(s.ss, _o)
            if _v == 0:
                raise ZeroDivisionError('div by zero')
            _q, _r = divmod(((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF), _v & 0xFFFF)
            if _q > 0xFFFF:
                raise OverflowError('16-bit div quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:435F  8946fc       mov
            _o = (s.bp - 0x4) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:4362  e90500       jmp
            cpu.instruction_count += 6
            bb = 9
        elif bb == 8:
            # 1010:4365  c746fc6400   mov rm16,imm16
            _o = (s.bp - 0x4) & 0xFFFF
            mem.ww(s.ss, _o, 0x64)
            cpu.instruction_count += 1
            bb = 9
        elif bb == 9:
            # 1010:436A  837efc64     grp1 rm16,imm8sx
            _o = (s.bp - 0x4) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x64
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:436E  7e03         jle
            cpu.instruction_count += 2
            bb = 11 if cpu.condition(0xE) else 10
        elif bb == 10:
            # 1010:4370  e90a00       jmp
            cpu.instruction_count += 1
            bb = 13
        elif bb == 11:
            # 1010:4373  833ea05400   grp1 rm16,imm8sx
            _o = 0x54A0
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:4378  7503         jnz
            cpu.instruction_count += 2
            bb = 13 if cpu.condition(0x5) else 12
        elif bb == 12:
            # 1010:437A  e90500       jmp
            cpu.instruction_count += 1
            bb = 14
        elif bb == 13:
            # 1010:437D  c746fc6400   mov rm16,imm16
            _o = (s.bp - 0x4) & 0xFFFF
            mem.ww(s.ss, _o, 0x64)
            cpu.instruction_count += 1
            bb = 14
        elif bb == 14:
            # 1010:4382  c746f2a831   mov rm16,imm16
            _o = (s.bp - 0xE) & 0xFFFF
            mem.ww(s.ss, _o, 0x31A8)
            # 1010:4387  8b5e04       mov
            _o = (s.bp + 0x4) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:438A  8b07         mov
            _o = (s.bx) & 0xFFFF
            s.ax = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:438C  8946fa       mov
            _o = (s.bp - 0x6) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:438F  c746f80000   mov rm16,imm16
            _o = (s.bp - 0x8) & 0xFFFF
            mem.ww(s.ss, _o, 0x0)
            # 1010:4394  8b5e06       mov
            _o = (s.bp + 0x6) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:4397  8b07         mov
            _o = (s.bx) & 0xFFFF
            s.ax = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:4399  8946f6       mov
            _o = (s.bp - 0xA) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:439C  c746f40000   mov rm16,imm16
            _o = (s.bp - 0xC) & 0xFFFF
            mem.ww(s.ss, _o, 0x0)
            # 1010:43A1  c746fe0000   mov rm16,imm16
            _o = (s.bp - 0x2) & 0xFFFF
            mem.ww(s.ss, _o, 0x0)
            # 1010:43A6  e93200       jmp
            cpu.instruction_count += 11
            bb = 16
        elif bb == 15:
            # 1010:43A9  8b46fe       mov
            _o = (s.bp - 0x2) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:43AC  8346fe01     grp1 rm16,imm8sx
            _o = (s.bp - 0x2) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x1
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            mem.ww(s.ss, _o, _r & 0xFFFF)
            # 1010:43B0  8946f0       mov
            _o = (s.bp - 0x10) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:43B3  8b46f2       mov
            _o = (s.bp - 0xE) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:43B6  8346f201     grp1 rm16,imm8sx
            _o = (s.bp - 0xE) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x1
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            mem.ww(s.ss, _o, _r & 0xFFFF)
            # 1010:43BA  8946ee       mov
            _o = (s.bp - 0x12) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:43BD  8b46f8       mov
            _o = (s.bp - 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:43C0  8e46fa       mov sreg,rm16
            _o = (s.bp - 0x6) & 0xFFFF
            cpu.set_sreg(0, mem.rw(s.ss, _o))
            # 1010:43C3  8346f801     grp1 rm16,imm8sx
            _o = (s.bp - 0x8) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x1
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            mem.ww(s.ss, _o, _r & 0xFFFF)
            # 1010:43C7  8cc2         mov rm16,sreg
            s.dx = (s.es) & 0xFFFF
            # 1010:43C9  8946ea       mov
            _o = (s.bp - 0x16) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:43CC  8956ec       mov
            _o = (s.bp - 0x14) & 0xFFFF
            mem.ww(s.ss, _o, s.dx)
            # 1010:43CF  8b46f4       mov
            _o = (s.bp - 0xC) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:43D2  8e46f6       mov sreg,rm16
            _o = (s.bp - 0xA) & 0xFFFF
            cpu.set_sreg(0, mem.rw(s.ss, _o))
            # 1010:43D5  8346f401     grp1 rm16,imm8sx
            _o = (s.bp - 0xC) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x1
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            mem.ww(s.ss, _o, _r & 0xFFFF)
            # 1010:43D9  8cc2         mov rm16,sreg
            s.dx = (s.es) & 0xFFFF
            cpu.instruction_count += 16
            bb = 16
        elif bb == 16:
            # 1010:43DB  8b46fe       mov
            _o = (s.bp - 0x2) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:43DE  8946f0       mov
            _o = (s.bp - 0x10) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:43E1  b80300       mov r16,imm16
            s.ax = 0x3
            # 1010:43E4  8b5e04       mov
            _o = (s.bp + 0x4) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:43E7  f76f04       grp3 rm16
            _o = (s.bx + 0x4) & 0xFFFF
            _v = mem.rw(s.ds, _o)
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:43EA  8b4ef0       mov
            _o = (s.bp - 0x10) & 0xFFFF
            s.cx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:43ED  3bc8         cmp
            _a = s.cx
            _b = s.ax
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:43EF  7203         jb
            cpu.instruction_count += 8
            bb = 18 if cpu.condition(0x2) else 17
        elif bb == 17:
            # 1010:43F1  e93c00       jmp
            cpu.instruction_count += 1
            bb = 19
        elif bb == 18:
            # 1010:43F4  c45ef8       les
            _o = (s.bp - 0x8) & 0xFFFF
            _off = mem.rw(s.ss, _o)
            _seg = mem.rw(s.ss, (_o + 2) & 0xFFFF)
            s.bx = _off
            s.es = _seg
            # 1010:43F7  268a07       mov
            _o = (s.bx) & 0xFFFF
            cpu.set_reg8(0, mem.rb(s.es, _o))
            # 1010:43FA  25ff00       and
            _a = s.ax
            _b = 0xFF
            _r = _a & _b
            cpu.set_logic_flags(_r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:43FD  c45ef4       les
            _o = (s.bp - 0xC) & 0xFFFF
            _off = mem.rw(s.ss, _o)
            _seg = mem.rw(s.ss, (_o + 2) & 0xFFFF)
            s.bx = _off
            s.es = _seg
            # 1010:4400  8946f0       mov
            _o = (s.bp - 0x10) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:4403  268a07       mov
            _o = (s.bx) & 0xFFFF
            cpu.set_reg8(0, mem.rb(s.es, _o))
            # 1010:4406  25ff00       and
            _a = s.ax
            _b = 0xFF
            _r = _a & _b
            cpu.set_logic_flags(_r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:4409  8b4ef0       mov
            _o = (s.bp - 0x10) & 0xFFFF
            s.cx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:440C  2bc1         sub
            _a = s.ax
            _b = s.cx
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:440E  f76efc       grp3 rm16
            _o = (s.bp - 0x4) & 0xFFFF
            _v = mem.rw(s.ss, _o)
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:4411  b96400       mov r16,imm16
            s.cx = 0x64
            # 1010:4414  99           cwd
            s.dx = 0xFFFF if s.ax & 0x8000 else 0x0000
            # 1010:4415  f7f9         grp3 rm16
            _v = s.cx
            if _v == 0:
                raise ZeroDivisionError('idiv by zero')
            _dividend = ((s.dx & 0xFFFF) << 16) | (s.ax & 0xFFFF)
            if _dividend & 0x80000000:
                _dividend -= 0x100000000
            _divisor = cpu.sign16(_v & 0xFFFF)
            _q = int(_dividend / _divisor)
            _r = _dividend - _q * _divisor
            if _q < -32768 or _q > 32767:
                raise OverflowError('16-bit idiv quotient overflow')
            s.ax = _q & 0xFFFF
            s.dx = _r & 0xFFFF
            # 1010:4417  c45ef8       les
            _o = (s.bp - 0x8) & 0xFFFF
            _off = mem.rw(s.ss, _o)
            _seg = mem.rw(s.ss, (_o + 2) & 0xFFFF)
            s.bx = _off
            s.es = _seg
            # 1010:441A  8946ee       mov
            _o = (s.bp - 0x12) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:441D  268a07       mov
            _o = (s.bx) & 0xFFFF
            cpu.set_reg8(0, mem.rb(s.es, _o))
            # 1010:4420  25ff00       and
            _a = s.ax
            _b = 0xFF
            _r = _a & _b
            cpu.set_logic_flags(_r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:4423  8b4eee       mov
            _o = (s.bp - 0x12) & 0xFFFF
            s.cx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:4426  03c1         add
            _a = s.ax
            _b = s.cx
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:4428  8b5ef2       mov
            _o = (s.bp - 0xE) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:442B  8807         mov
            _o = (s.bx) & 0xFFFF
            mem.wb(s.ds, _o, cpu.get_reg8(0))
            # 1010:442D  e979ff       jmp
            cpu.instruction_count += 22
            bb = 15
        elif bb == 19:
            # 1010:4430  b8a831       mov r16,imm16
            s.ax = 0x31A8
            # 1010:4433  8cda         mov rm16,sreg
            s.dx = (s.ds) & 0xFFFF
            # 1010:4435  52           push r16
            cpu.push(s.dx)
            # 1010:4436  50           push r16
            cpu.push(s.ax)
            # 1010:4437  8b5e04       mov
            _o = (s.bp + 0x4) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:443A  ff7704       push rm16
            _o = (s.bx + 0x4) & 0xFFFF
            cpu.push(mem.rw(s.ds, _o))
            # 1010:443D  8b5e04       mov
            _o = (s.bp + 0x4) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:4440  ff7702       push rm16
            _o = (s.bx + 0x2) & 0xFFFF
            cpu.push(mem.rw(s.ds, _o))
            # 1010:4443  e8221d       call
            cpu.instruction_count += 9
            emulate_call(cpu, 0x1010, 0x6168, 0x4446)
            bb = 20
        elif bb == 20:
            # 1010:4446  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:4449  e807fd       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x4153, 0x444C)
            bb = 21
        elif bb == 21:
            # 1010:444C  837efc64     grp1 rm16,imm8sx
            _o = (s.bp - 0x4) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x64
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:4450  7403         jz
            cpu.instruction_count += 2
            bb = 23 if cpu.condition(0x4) else 22
        elif bb == 22:
            # 1010:4452  e9f5fe       jmp
            cpu.instruction_count += 1
            bb = 4
        elif bb == 23:
            # 1010:4455  5f           pop r16
            s.di = cpu.pop()
            # 1010:4456  5e           pop r16
            s.si = cpu.pop()
            # 1010:4457  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:4458  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_4331.owns_time = True

