"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:63A3  (13 instructions, 1 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x63A3)
SIGNATURE = bytes.fromhex('a1b6418b1eb2412bc35053ff36ac41e8')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x63A3}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches


def lifted_1010_63a3(cpu, bb=0):
    """Lifted replacement for 1010:63A3."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x63A3, SIGNATURE, 'lifted_1010_63a3')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:63A3  a1b641       mov moffs
            s.ax = mem.rw(s.ds, 0x41B6)
            # 1010:63A6  8b1eb241     mov
            _o = 0x41B2
            s.bx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:63AA  2bc3         sub
            _a = s.ax
            _b = s.bx
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:63AC  50           push r16
            cpu.push(s.ax)
            # 1010:63AD  53           push r16
            cpu.push(s.bx)
            # 1010:63AE  ff36ac41     push rm16
            _o = 0x41AC
            cpu.push(mem.rw(s.ds, _o))
            # 1010:63B2  e8f6fc       call
            cpu.instruction_count += 7
            emulate_call(cpu, 0x1010, 0x60AB, 0x63B5)
            # 1010:63B5  5b           pop r16
            s.bx = cpu.pop()
            # 1010:63B6  5b           pop r16
            s.bx = cpu.pop()
            # 1010:63B7  5b           pop r16
            s.bx = cpu.pop()
            # 1010:63B8  e80400       call
            cpu.instruction_count += 4
            emulate_call(cpu, 0x1010, 0x63BF, 0x63BB)
            # 1010:63BB  a3b841       mov moffs
            mem.ww(s.ds, 0x41B8, s.ax)
            # 1010:63BE  c3           ret
            cpu.instruction_count += 2
            s.ip = cpu.pop()
            cpu.call_depth = max(0, cpu.call_depth - 1)
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_63a3.owns_time = True
