"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:4ACB  (23 instructions, 3 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x4ACB)
SIGNATURE = bytes.fromhex('c804000056578b4604d1e0d1e0d1e0b9')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x4ACB, 1: 0x4AF0, 2: 0x4AF7}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:4AF0": 1, "1010:4AF7": 2}


def lifted_1010_4acb(cpu, bb=0):
    """Lifted replacement for 1010:4ACB."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x4ACB, SIGNATURE, 'lifted_1010_4acb')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:4ACB  c8040000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            s.sp = (s.sp - 0x4) & 0xFFFF
            # 1010:4ACF  56           push r16
            cpu.push(s.si)
            # 1010:4AD0  57           push r16
            cpu.push(s.di)
            # 1010:4AD1  8b4604       mov
            _o = (s.bp + 0x4) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:4AD4  d1e0         shift
            _r = cpu.shift(4, s.ax, 1, 16)
            s.ax = (_r) & 0xFFFF
            # 1010:4AD6  d1e0         shift
            _r = cpu.shift(4, s.ax, 1, 16)
            s.ax = (_r) & 0xFFFF
            # 1010:4AD8  d1e0         shift
            _r = cpu.shift(4, s.ax, 1, 16)
            s.ax = (_r) & 0xFFFF
            # 1010:4ADA  b9c244       mov r16,imm16
            s.cx = 0x44C2
            # 1010:4ADD  03c8         add
            _a = s.cx
            _b = s.ax
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:4ADF  8bf1         mov
            s.si = (s.cx) & 0xFFFF
            # 1010:4AE1  6a01         push imm8
            cpu.push(0x0001)
            # 1010:4AE3  ff7606       push rm16
            _o = (s.bp + 0x6) & 0xFFFF
            cpu.push(mem.rw(s.ss, _o))
            # 1010:4AE6  6800a0       push imm16
            cpu.push(0xA000)
            # 1010:4AE9  ff3622af     push rm16
            _o = 0xAF22
            cpu.push(mem.rw(s.ds, _o))
            # 1010:4AED  e88ef6       call
            cpu.instruction_count += 15
            emulate_call(cpu, 0x1010, 0x417E, 0x4AF0)
            bb = 1
        elif bb == 1:
            # 1010:4AF0  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:4AF3  56           push r16
            cpu.push(s.si)
            # 1010:4AF4  e80af7       call
            cpu.instruction_count += 3
            emulate_call(cpu, 0x1010, 0x4201, 0x4AF7)
            bb = 2
        elif bb == 2:
            # 1010:4AF7  83c402       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x2
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:4AFA  5f           pop r16
            s.di = cpu.pop()
            # 1010:4AFB  5e           pop r16
            s.si = cpu.pop()
            # 1010:4AFC  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:4AFD  c3           ret
            cpu.instruction_count += 5
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_4acb.owns_time = True

