"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:2B3D  (143 instructions, 40 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x2B3D)
SIGNATURE = bytes.fromhex('c80a00005657b8a831050f00c1e8048c')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x2B3D, 1: 0x2B56, 2: 0x2B7E, 3: 0x2B81, 4: 0x2BA3, 5: 0x2BA9, 6: 0x2BB3, 7: 0x2BC0, 8: 0x2BC3, 9: 0x2BD9, 10: 0x2BE3, 11: 0x2BE6, 12: 0x2BEC, 13: 0x2BF3, 14: 0x2BF6, 15: 0x2BFC, 16: 0x2BFF, 17: 0x2C05, 18: 0x2C12, 19: 0x2C1E, 20: 0x2C4E, 21: 0x2C5B, 22: 0x2C61, 23: 0x2C6A, 24: 0x2C6D, 25: 0x2C76, 26: 0x2C7B, 27: 0x2C7E, 28: 0x2C81, 29: 0x2C87, 30: 0x2C8A, 31: 0x2C97, 32: 0x2C9D, 33: 0x2CA9, 34: 0x2CAC, 35: 0x2CB1, 36: 0x2CB4, 37: 0x2CBE, 38: 0x2CC4, 39: 0x2CC9}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:2B56": 1, "1010:2BA3": 4, "1010:2BB3": 6, "1010:2BC0": 7, "1010:2BD9": 9, "1010:2C12": 18, "1010:2C1E": 19, "1010:2C4E": 20, "1010:2C5B": 21, "1010:2C61": 22, "1010:2C76": 25, "1010:2C81": 28, "1010:2C97": 31, "1010:2CA9": 33, "1010:2CB1": 35, "1010:2CBE": 37, "1010:2CC4": 38}


def lifted_1010_2b3d(cpu, bb=0):
    """Lifted replacement for 1010:2B3D."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x2B3D, SIGNATURE, 'lifted_1010_2b3d')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:2B3D  c80a0000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            s.sp = (s.sp - 0xA) & 0xFFFF
            # 1010:2B41  56           push r16
            cpu.push(s.si)
            # 1010:2B42  57           push r16
            cpu.push(s.di)
            # 1010:2B43  b8a831       mov r16,imm16
            s.ax = 0x31A8
            # 1010:2B46  050f00       add
            _a = s.ax
            _b = 0xF
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:2B49  c1e804       shift rm16,imm8
            _r = cpu.shift(5, s.ax, 0x04, 16)
            s.ax = (_r) & 0xFFFF
            # 1010:2B4C  8cdb         mov rm16,sreg
            s.bx = (s.ds) & 0xFFFF
            # 1010:2B4E  03c3         add
            _a = s.ax
            _b = s.bx
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:2B50  a32aaf       mov moffs
            mem.ww(s.ds, 0xAF2A, s.ax)
            # 1010:2B53  e84710       call
            cpu.instruction_count += 10
            emulate_call(cpu, 0x1010, 0x3B9D, 0x2B56)
            bb = 1
        elif bb == 1:
            # 1010:2B56  c7061eaf0000 mov rm16,imm16
            _o = 0xAF1E
            mem.ww(s.ds, _o, 0x0)
            # 1010:2B5C  b80000       mov r16,imm16
            s.ax = 0x0
            # 1010:2B5F  a35c45       mov moffs
            mem.ww(s.ds, 0x455C, s.ax)
            # 1010:2B62  a30c96       mov moffs
            mem.ww(s.ds, 0x960C, s.ax)
            # 1010:2B65  a36c45       mov moffs
            mem.ww(s.ds, 0x456C, s.ax)
            # 1010:2B68  a3be41       mov moffs
            mem.ww(s.ds, 0x41BE, s.ax)
            # 1010:2B6B  c70620afffff mov rm16,imm16
            _o = 0xAF20
            mem.ww(s.ds, _o, 0xFFFF)
            # 1010:2B71  c70634930000 mov rm16,imm16
            _o = 0x9334
            mem.ww(s.ds, _o, 0x0)
            # 1010:2B77  833e3c0000   grp1 rm16,imm8sx
            _o = 0x003C
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:2B7C  7503         jnz
            cpu.instruction_count += 10
            bb = 3 if cpu.condition(0x5) else 2
        elif bb == 2:
            # 1010:2B7E  e92800       jmp
            cpu.instruction_count += 1
            bb = 5
        elif bb == 3:
            # 1010:2B81  a17051       mov moffs
            s.ax = mem.rw(s.ds, 0x5170)
            # 1010:2B84  8946fa       mov
            _o = (s.bp - 0x6) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:2B87  c746f80000   mov rm16,imm16
            _o = (s.bp - 0x8) & 0xFFFF
            mem.ww(s.ss, _o, 0x0)
            # 1010:2B8C  68804d       push imm16
            cpu.push(0x4D80)
            # 1010:2B8F  8b46f8       mov
            _o = (s.bp - 0x8) & 0xFFFF
            s.ax = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:2B92  8b56fa       mov
            _o = (s.bp - 0x6) & 0xFFFF
            s.dx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:2B95  0580ac       add
            _a = s.ax
            _b = 0xAC80
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:2B98  52           push r16
            cpu.push(s.dx)
            # 1010:2B99  50           push r16
            cpu.push(s.ax)
            # 1010:2B9A  6800a0       push imm16
            cpu.push(0xA000)
            # 1010:2B9D  6880ac       push imm16
            cpu.push(0xAC80)
            # 1010:2BA0  e8b034       call
            cpu.instruction_count += 12
            emulate_call(cpu, 0x1010, 0x6053, 0x2BA3)
            bb = 4
        elif bb == 4:
            # 1010:2BA3  83c40a       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0xA
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:2BA6  e91a00       jmp
            cpu.instruction_count += 2
            bb = 8
        elif bb == 5:
            # 1010:2BA9  ff367051     push rm16
            _o = 0x5170
            cpu.push(mem.rw(s.ds, _o))
            # 1010:2BAD  6800a0       push imm16
            cpu.push(0xA000)
            # 1010:2BB0  e85cff       call
            cpu.instruction_count += 3
            emulate_call(cpu, 0x1010, 0x2B0F, 0x2BB3)
            bb = 6
        elif bb == 6:
            # 1010:2BB3  83c404       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x4
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:2BB6  ff367051     push rm16
            _o = 0x5170
            cpu.push(mem.rw(s.ds, _o))
            # 1010:2BBA  6800a2       push imm16
            cpu.push(0xA200)
            # 1010:2BBD  e84fff       call
            cpu.instruction_count += 4
            emulate_call(cpu, 0x1010, 0x2B0F, 0x2BC0)
            bb = 7
        elif bb == 7:
            # 1010:2BC0  83c404       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x4
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 1
            bb = 8
        elif bb == 8:
            # 1010:2BC3  6a04         push imm8
            cpu.push(0x0004)
            # 1010:2BC5  a16245       mov moffs
            s.ax = mem.rw(s.ds, 0x4562)
            # 1010:2BC8  05fdff       add
            _a = s.ax
            _b = 0xFFFD
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:2BCB  b96400       mov r16,imm16
            s.cx = 0x64
            # 1010:2BCE  f7e9         grp3 rm16
            _v = s.cx
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:2BD0  50           push r16
            cpu.push(s.ax)
            # 1010:2BD1  689c00       push imm16
            cpu.push(0x9C)
            # 1010:2BD4  6a60         push imm8
            cpu.push(0x0060)
            # 1010:2BD6  e83be5       call
            cpu.instruction_count += 9
            emulate_call(cpu, 0x1010, 0x1114, 0x2BD9)
            bb = 9
        elif bb == 9:
            # 1010:2BD9  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:2BDC  833e3c0000   grp1 rm16,imm8sx
            _o = 0x003C
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:2BE1  7503         jnz
            cpu.instruction_count += 3
            bb = 11 if cpu.condition(0x5) else 10
        elif bb == 10:
            # 1010:2BE3  e90600       jmp
            cpu.instruction_count += 1
            bb = 12
        elif bb == 11:
            # 1010:2BE6  a17854       mov moffs
            s.ax = mem.rw(s.ds, 0x5478)
            # 1010:2BE9  e91900       jmp
            cpu.instruction_count += 2
            bb = 17
        elif bb == 12:
            # 1010:2BEC  833e349300   grp1 rm16,imm8sx
            _o = 0x9334
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:2BF1  7403         jz
            cpu.instruction_count += 2
            bb = 14 if cpu.condition(0x4) else 13
        elif bb == 13:
            # 1010:2BF3  e90600       jmp
            cpu.instruction_count += 1
            bb = 15
        elif bb == 14:
            # 1010:2BF6  b80100       mov r16,imm16
            s.ax = 0x1
            # 1010:2BF9  e90300       jmp
            cpu.instruction_count += 2
            bb = 16
        elif bb == 15:
            # 1010:2BFC  b80000       mov r16,imm16
            s.ax = 0x0
            cpu.instruction_count += 1
            bb = 16
        elif bb == 16:
            # 1010:2BFF  c1e009       shift rm16,imm8
            _r = cpu.shift(4, s.ax, 0x09, 16)
            s.ax = (_r) & 0xFFFF
            # 1010:2C02  0500a0       add
            _a = s.ax
            _b = 0xA000
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 2
            bb = 17
        elif bb == 17:
            # 1010:2C05  50           push r16
            cpu.push(s.ax)
            # 1010:2C06  6a00         push imm8
            cpu.push(0x0000)
            # 1010:2C08  6a01         push imm8
            cpu.push(0x0001)
            # 1010:2C0A  680028       push imm16
            cpu.push(0x2800)
            # 1010:2C0D  6a00         push imm8
            cpu.push(0x0000)
            # 1010:2C0F  e89ddf       call
            cpu.instruction_count += 6
            emulate_call(cpu, 0x1010, 0x0BAF, 0x2C12)
            bb = 18
        elif bb == 18:
            # 1010:2C12  83c404       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x4
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:2C15  8946f6       mov
            _o = (s.bp - 0xA) & 0xFFFF
            mem.ww(s.ss, _o, s.ax)
            # 1010:2C18  680080       push imm16
            cpu.push(0x8000)
            # 1010:2C1B  e8cbdf       call
            cpu.instruction_count += 4
            emulate_call(cpu, 0x1010, 0x0BE9, 0x2C1E)
            bb = 19
        elif bb == 19:
            # 1010:2C1E  83c402       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x2
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:2C21  b90300       mov r16,imm16
            s.cx = 0x3
            # 1010:2C24  f7e9         grp3 rm16
            _v = s.cx
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:2C26  8b4ef6       mov
            _o = (s.bp - 0xA) & 0xFFFF
            s.cx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:2C29  03c1         add
            _a = s.ax
            _b = s.cx
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:2C2B  b90300       mov r16,imm16
            s.cx = 0x3
            # 1010:2C2E  f7e9         grp3 rm16
            _v = s.cx
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:2C30  050e00       add
            _a = s.ax
            _b = 0xE
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:2C33  b9d002       mov r16,imm16
            s.cx = 0x2D0
            # 1010:2C36  f7e9         grp3 rm16
            _v = s.cx
            _result = cpu.sign16(s.ax) * cpu.sign16(_v)
            s.ax = _result & 0xFFFF
            s.dx = (_result >> 16) & 0xFFFF
            _carry = not (-32768 <= _result <= 32767)
            cpu.set_flag(CF, _carry)
            cpu.set_flag(OF, _carry)
            # 1010:2C38  8b0e34af     mov
            _o = 0xAF34
            s.cx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:2C3C  8b1636af     mov
            _o = 0xAF36
            s.dx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:2C40  03c8         add
            _a = s.cx
            _b = s.ax
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.cx = (_r & 0xFFFF) & 0xFFFF
            # 1010:2C42  52           push r16
            cpu.push(s.dx)
            # 1010:2C43  51           push r16
            cpu.push(s.cx)
            # 1010:2C44  6a50         push imm8
            cpu.push(0x0050)
            # 1010:2C46  6a18         push imm8
            cpu.push(0x0018)
            # 1010:2C48  680001       push imm16
            cpu.push(0x100)
            # 1010:2C4B  e8d100       call
            cpu.instruction_count += 19
            emulate_call(cpu, 0x1010, 0x2D1F, 0x2C4E)
            bb = 20
        elif bb == 20:
            # 1010:2C4E  83c410       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x10
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:2C51  6a24         push imm8
            cpu.push(0x0024)
            # 1010:2C53  6a01         push imm8
            cpu.push(0x0001)
            # 1010:2C55  68c241       push imm16
            cpu.push(0x41C2)
            # 1010:2C58  e8331f       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x4B8E, 0x2C5B)
            bb = 21
        elif bb == 21:
            # 1010:2C5B  83c406       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x6
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:2C5E  e878f3       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x1FD9, 0x2C61)
            bb = 22
        elif bb == 22:
            # 1010:2C61  8bf0         mov
            s.si = (s.ax) & 0xFFFF
            # 1010:2C63  833e349300   grp1 rm16,imm8sx
            _o = 0x9334
            _a = mem.rw(s.ds, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:2C68  7503         jnz
            cpu.instruction_count += 3
            bb = 24 if cpu.condition(0x5) else 23
        elif bb == 23:
            # 1010:2C6A  e90900       jmp
            cpu.instruction_count += 1
            bb = 25
        elif bb == 24:
            # 1010:2C6D  c70634930000 mov rm16,imm16
            _o = 0x9334
            mem.ww(s.ds, _o, 0x0)
            # 1010:2C73  e85ae2       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x0ED0, 0x2C76)
            bb = 25
        elif bb == 25:
            # 1010:2C76  83fe00       grp1 rm16,imm8sx
            _a = s.si
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:2C79  7403         jz
            cpu.instruction_count += 2
            bb = 27 if cpu.condition(0x4) else 26
        elif bb == 26:
            # 1010:2C7B  e93600       jmp
            cpu.instruction_count += 1
            bb = 36
        elif bb == 27:
            # 1010:2C7E  e81910       call
            cpu.instruction_count += 1
            emulate_call(cpu, 0x1010, 0x3C9A, 0x2C81)
            bb = 28
        elif bb == 28:
            # 1010:2C81  837e0400     grp1 rm16,imm8sx
            _o = (s.bp + 0x4) & 0xFFFF
            _a = mem.rw(s.ss, _o)
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:2C85  7503         jnz
            cpu.instruction_count += 2
            bb = 30 if cpu.condition(0x5) else 29
        elif bb == 29:
            # 1010:2C87  e91300       jmp
            cpu.instruction_count += 1
            bb = 32
        elif bb == 30:
            # 1010:2C8A  6a63         push imm8
            cpu.push(0x0063)
            # 1010:2C8C  683a0d       push imm16
            cpu.push(0xD3A)
            # 1010:2C8F  6a50         push imm8
            cpu.push(0x0050)
            # 1010:2C91  688400       push imm16
            cpu.push(0x84)
            # 1010:2C94  e88f18       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x4526, 0x2C97)
            bb = 31
        elif bb == 31:
            # 1010:2C97  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:2C9A  e90f00       jmp
            cpu.instruction_count += 2
            bb = 34
        elif bb == 32:
            # 1010:2C9D  6a63         push imm8
            cpu.push(0x0063)
            # 1010:2C9F  68420d       push imm16
            cpu.push(0xD42)
            # 1010:2CA2  6a50         push imm8
            cpu.push(0x0050)
            # 1010:2CA4  6a68         push imm8
            cpu.push(0x0068)
            # 1010:2CA6  e87d18       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x4526, 0x2CA9)
            bb = 33
        elif bb == 33:
            # 1010:2CA9  83c408       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x8
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 1
            bb = 34
        elif bb == 34:
            # 1010:2CAC  6a1b         push imm8
            cpu.push(0x001B)
            # 1010:2CAE  e8a817       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x4459, 0x2CB1)
            bb = 35
        elif bb == 35:
            # 1010:2CB1  83c402       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x2
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 1
            bb = 36
        elif bb == 36:
            # 1010:2CB4  6a24         push imm8
            cpu.push(0x0024)
            # 1010:2CB6  6a00         push imm8
            cpu.push(0x0000)
            # 1010:2CB8  68c241       push imm16
            cpu.push(0x41C2)
            # 1010:2CBB  e8d01e       call
            cpu.instruction_count += 4
            emulate_call(cpu, 0x1010, 0x4B8E, 0x2CBE)
            bb = 37
        elif bb == 37:
            # 1010:2CBE  83c406       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x6
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:2CC1  e83f0f       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x3C03, 0x2CC4)
            bb = 38
        elif bb == 38:
            # 1010:2CC4  8bc6         mov
            s.ax = (s.si) & 0xFFFF
            # 1010:2CC6  e90000       jmp
            cpu.instruction_count += 2
            bb = 39
        elif bb == 39:
            # 1010:2CC9  5f           pop r16
            s.di = cpu.pop()
            # 1010:2CCA  5e           pop r16
            s.si = cpu.pop()
            # 1010:2CCB  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:2CCC  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_2b3d.owns_time = True

