"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:64FF  (29 instructions, 9 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x64FF)
SIGNATURE = bytes.fromhex('8bdc8b4f0233c0eb37')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x64FF, 1: 0x6508, 2: 0x6516, 3: 0x652A, 4: 0x6530, 5: 0x6535, 6: 0x653B, 7: 0x653F, 8: 0x6542}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:6530": 4}


def lifted_1010_64ff(cpu, bb=0):
    """Lifted replacement for 1010:64FF."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x64FF, SIGNATURE, 'lifted_1010_64ff')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:64FF  8bdc         mov
            s.bx = (s.sp) & 0xFFFF
            # 1010:6501  8b4f02       mov
            _o = (s.bx + 0x2) & 0xFFFF
            s.cx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:6504  33c0         xor
            _a = s.ax
            _b = s.ax
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:6506  eb37         jmp short
            cpu.instruction_count += 4
            bb = 7
        elif bb == 1:
            # 1010:6508  33d2         xor
            _a = s.dx
            _b = s.dx
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 16)
            s.dx = (_r & 0xFFFF) & 0xFFFF
            # 1010:650A  d016b041     shift
            _o = 0x41B0
            _r = cpu.shift(2, mem.rb(s.ds, _o), 1, 8)
            mem.wb(s.ds, _o, _r)
            # 1010:650E  d1d2         shift
            _r = cpu.shift(2, s.dx, 1, 16)
            s.dx = (_r) & 0xFFFF
            # 1010:6510  ff0eae41     dec rm16
            _o = 0x41AE
            _old = mem.rw(s.ds, _o)
            _r = (_old - 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=True)
            mem.ww(s.ds, _o, _r)
            # 1010:6514  7525         jnz
            cpu.instruction_count += 5
            bb = 6 if cpu.condition(0x5) else 2
        elif bb == 2:
            # 1010:6516  c706ae410800 mov rm16,imm16
            _o = 0x41AE
            mem.ww(s.ds, _o, 0x8)
            # 1010:651C  8b1eb641     mov
            _o = 0x41B6
            s.bx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:6520  ff06b641     inc rm16
            _o = 0x41B6
            _old = mem.rw(s.ds, _o)
            _r = (_old + 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=False)
            mem.ww(s.ds, _o, _r)
            # 1010:6524  391eb441     cmp
            _o = 0x41B4
            _a = mem.rw(s.ds, _o)
            _b = s.bx
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:6528  750b         jnz
            cpu.instruction_count += 5
            bb = 5 if cpu.condition(0x5) else 3
        elif bb == 3:
            # 1010:652A  50           push r16
            cpu.push(s.ax)
            # 1010:652B  52           push r16
            cpu.push(s.dx)
            # 1010:652C  51           push r16
            cpu.push(s.cx)
            # 1010:652D  e820fe       call
            cpu.instruction_count += 4
            emulate_call(cpu, 0x1010, 0x6350, 0x6530)
            bb = 4
        elif bb == 4:
            # 1010:6530  59           pop r16
            s.cx = cpu.pop()
            # 1010:6531  5a           pop r16
            s.dx = cpu.pop()
            # 1010:6532  58           pop r16
            s.ax = cpu.pop()
            # 1010:6533  eb06         jmp short
            cpu.instruction_count += 4
            bb = 6
        elif bb == 5:
            # 1010:6535  8a1f         mov
            _o = (s.bx) & 0xFFFF
            cpu.set_reg8(3, mem.rb(s.ds, _o))
            # 1010:6537  881eb041     mov
            _o = 0x41B0
            mem.wb(s.ds, _o, cpu.get_reg8(3))
            cpu.instruction_count += 2
            bb = 6
        elif bb == 6:
            # 1010:653B  d3e2         shift
            _r = cpu.shift(4, s.dx, s.cx & 0xFF, 16)
            s.dx = (_r) & 0xFFFF
            # 1010:653D  0bc2         or
            _a = s.ax
            _b = s.dx
            _r = _a | _b
            cpu.set_logic_flags(_r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            cpu.instruction_count += 2
            bb = 7
        elif bb == 7:
            # 1010:653F  49           dec r16
            _old = s.cx
            _r = (_old - 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=True)
            s.cx = _r
            # 1010:6540  79c6         jns
            cpu.instruction_count += 2
            bb = 1 if cpu.condition(0x9) else 8
        elif bb == 8:
            # 1010:6542  c3           ret
            cpu.instruction_count += 1
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_64ff.owns_time = True

