"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:413C  (11 instructions, 3 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x413C)
SIGNATURE = bytes.fromhex('c80000005657ff36ac41e8101b')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x413C, 1: 0x4149, 2: 0x414F}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:4149": 1, "1010:414F": 2}


def lifted_1010_413c(cpu, bb=0):
    """Lifted replacement for 1010:413C."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x413C, SIGNATURE, 'lifted_1010_413c')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:413C  c8000000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            # 1010:4140  56           push r16
            cpu.push(s.si)
            # 1010:4141  57           push r16
            cpu.push(s.di)
            # 1010:4142  ff36ac41     push rm16
            _o = 0x41AC
            cpu.push(mem.rw(s.ds, _o))
            # 1010:4146  e8101b       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x5C59, 0x4149)
            bb = 1
        elif bb == 1:
            # 1010:4149  83c402       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x2
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:414C  e81abf       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x0069, 0x414F)
            bb = 2
        elif bb == 2:
            # 1010:414F  5f           pop r16
            s.di = cpu.pop()
            # 1010:4150  5e           pop r16
            s.si = cpu.pop()
            # 1010:4151  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:4152  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_413c.owns_time = True

