"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:6168  (65 instructions, 20 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x6168)
SIGNATURE = bytes.fromhex('8bdc1e06608b4f04c57706368b5f0233')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x6168, 1: 0x6183, 2: 0x618D, 3: 0x6195, 4: 0x619B, 5: 0x619F, 6: 0x61A3, 7: 0x61AB, 8: 0x61AD, 9: 0x61B4, 10: 0x61B9, 11: 0x61BA, 12: 0x61C0, 13: 0x61C5, 14: 0x61CD, 15: 0x61CF, 16: 0x61D4, 17: 0x61D7, 18: 0x61DE, 19: 0x61E0}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:61B9": 10, "1010:61CD": 14, "1010:61D4": 16, "1010:61DE": 18, "1010:61E0": 19}


def lifted_1010_6168(cpu, bb=0):
    """Lifted replacement for 1010:6168."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x6168, SIGNATURE, 'lifted_1010_6168')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:6168  8bdc         mov
            s.bx = (s.sp) & 0xFFFF
            # 1010:616A  1e           push ds
            cpu.push(s.ds)
            # 1010:616B  06           push es
            cpu.push(s.es)
            # 1010:616C  60           pusha
            _sp0 = s.sp
            cpu.push(s.ax)
            cpu.push(s.cx)
            cpu.push(s.dx)
            cpu.push(s.bx)
            cpu.push(_sp0)
            cpu.push(s.bp)
            cpu.push(s.si)
            cpu.push(s.di)
            # 1010:616D  8b4f04       mov
            _o = (s.bx + 0x4) & 0xFFFF
            s.cx = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:6170  c57706       lds
            _o = (s.bx + 0x6) & 0xFFFF
            _off = mem.rw(s.ds, _o)
            _seg = mem.rw(s.ds, (_o + 2) & 0xFFFF)
            s.si = _off
            s.ds = _seg
            # 1010:6173  368b5f02     mov
            _o = (s.bx + 0x2) & 0xFFFF
            s.bx = (mem.rw(s.ss, _o)) & 0xFFFF
            # 1010:6177  33c0         xor
            _a = s.ax
            _b = s.ax
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:6179  8ec0         mov sreg,rm16
            cpu.set_sreg(0, s.ax)
            # 1010:617B  26f606890406 grp3 rm8
            _o = 0x0489
            _v = mem.rb(s.es, _o)
            cpu.set_logic_flags(_v & 0x6, 8)
            # 1010:6181  7554         jnz
            cpu.instruction_count += 11
            bb = 17 if cpu.condition(0x5) else 1
        elif bb == 1:
            # 1010:6183  268b3e6304   mov
            _o = 0x0463
            s.di = (mem.rw(s.es, _o)) & 0xFFFF
            # 1010:6188  83c706       grp1 rm16,imm8sx
            _a = s.di
            _b = 0x6
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.di = (_r & 0xFFFF) & 0xFFFF
            # 1010:618B  eb2d         jmp short
            cpu.instruction_count += 3
            bb = 11
        elif bb == 2:
            # 1010:618D  8bc3         mov
            s.ax = (s.bx) & 0xFFFF
            # 1010:618F  bac803       mov r16,imm16
            s.dx = 0x3C8
            # 1010:6192  ee           out dx,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (s.dx) & 0xFFFF, _val, 8)
            # 1010:6193  eb00         jmp short
            cpu.instruction_count += 4
            bb = 3
        elif bb == 3:
            # 1010:6195  fec2         grp4
            _old = cpu.get_reg8(2)
            _r = (_old + 1) & 0xFF
            cpu.set_incdec_flags(_old, _r, 8, dec=False)
            cpu.set_reg8(2, _r)
            # 1010:6197  ac           stos/lods/scas
            cpu.string_op(0xAC, None, None)
            # 1010:6198  ee           out dx,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (s.dx) & 0xFFFF, _val, 8)
            # 1010:6199  eb00         jmp short
            cpu.instruction_count += 4
            bb = 4
        elif bb == 4:
            # 1010:619B  ac           stos/lods/scas
            cpu.string_op(0xAC, None, None)
            # 1010:619C  ee           out dx,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (s.dx) & 0xFFFF, _val, 8)
            # 1010:619D  eb00         jmp short
            cpu.instruction_count += 3
            bb = 5
        elif bb == 5:
            # 1010:619F  ac           stos/lods/scas
            cpu.string_op(0xAC, None, None)
            # 1010:61A0  ee           out dx,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (s.dx) & 0xFFFF, _val, 8)
            # 1010:61A1  eb00         jmp short
            cpu.instruction_count += 3
            bb = 6
        elif bb == 6:
            # 1010:61A3  43           inc r16
            _old = s.bx
            _r = (_old + 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=False)
            s.bx = _r
            # 1010:61A4  49           dec r16
            _old = s.cx
            _r = (_old - 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=True)
            s.cx = _r
            # 1010:61A5  f7c13f00     grp3 rm16
            _v = s.cx
            cpu.set_logic_flags(_v & 0x3F, 16)
            # 1010:61A9  75e2         jnz
            cpu.instruction_count += 4
            bb = 2 if cpu.condition(0x5) else 7
        elif bb == 7:
            # 1010:61AB  e322         jcxz
            cpu.instruction_count += 1
            bb = 15 if (s.cx == 0) else 8
        elif bb == 8:
            # 1010:61AD  8bd7         mov
            s.dx = (s.di) & 0xFFFF
            # 1010:61AF  ec           in al,dx
            _val = cpu.port_reader(cpu, (s.dx) & 0xFFFF, 8) if cpu.port_reader else 0
            cpu.set_reg8(0, _val)
            # 1010:61B0  a808         test al,imm8
            cpu.set_logic_flags(cpu.get_reg8(0) & 0x8, 8)
            # 1010:61B2  75d9         jnz
            cpu.instruction_count += 4
            bb = 2 if cpu.condition(0x5) else 9
        elif bb == 9:
            # 1010:61B4  b400         mov r8,imm8
            cpu.set_reg8(4, 0x0)
            # 1010:61B6  e898ff       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x6151, 0x61B9)
            bb = 10
        elif bb == 10:
            # 1010:61B9  9d           popf
            s.flags = cpu.pop() | 0x0002
            cpu.instruction_count += 1
            bb = 11
        elif bb == 11:
            # 1010:61BA  51           push r16
            cpu.push(s.cx)
            # 1010:61BB  8bd7         mov
            s.dx = (s.di) & 0xFFFF
            # 1010:61BD  b9ffff       mov r16,imm16
            s.cx = 0xFFFF
            cpu.instruction_count += 3
            bb = 12
        elif bb == 12:
            # 1010:61C0  ec           in al,dx
            _val = cpu.port_reader(cpu, (s.dx) & 0xFFFF, 8) if cpu.port_reader else 0
            cpu.set_reg8(0, _val)
            # 1010:61C1  a808         test al,imm8
            cpu.set_logic_flags(cpu.get_reg8(0) & 0x8, 8)
            # 1010:61C3  e1fb         loopz
            cpu.instruction_count += 3
            s.cx = (s.cx - 1) & 0xFFFF
            bb = 12 if (s.cx != 0 and (s.flags & ZF)) else 13
        elif bb == 13:
            # 1010:61C5  59           pop r16
            s.cx = cpu.pop()
            # 1010:61C6  9c           pushf
            cpu.push(s.flags)
            # 1010:61C7  fa           cli
            cpu.set_flag(IF, False)
            # 1010:61C8  b420         mov r8,imm8
            cpu.set_reg8(4, 0x20)
            # 1010:61CA  e884ff       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x6151, 0x61CD)
            bb = 14
        elif bb == 14:
            # 1010:61CD  ebbe         jmp short
            cpu.instruction_count += 1
            bb = 2
        elif bb == 15:
            # 1010:61CF  b400         mov r8,imm8
            cpu.set_reg8(4, 0x0)
            # 1010:61D1  e87dff       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x6151, 0x61D4)
            bb = 16
        elif bb == 16:
            # 1010:61D4  9d           popf
            s.flags = cpu.pop() | 0x0002
            # 1010:61D5  eb09         jmp short
            cpu.instruction_count += 2
            bb = 19
        elif bb == 17:
            # 1010:61D7  1e           push ds
            cpu.push(s.ds)
            # 1010:61D8  07           pop es
            cpu.set_sreg(0, cpu.pop())
            # 1010:61D9  b81210       mov r16,imm16
            s.ax = 0x1012
            # 1010:61DC  8bd6         mov
            s.dx = (s.si) & 0xFFFF
            cpu.instruction_count += 4
            bb = 18
        elif bb == 18:
            # 1010:61DE  cd10         int
            cpu.instruction_count += 1
            emulate_int(cpu, 0x10, 0x1010, 0x61E0)
            bb = 19
        elif bb == 19:
            # 1010:61E0  61           popa
            s.di = cpu.pop()
            s.si = cpu.pop()
            s.bp = cpu.pop()
            cpu.pop()  # discard the saved SP
            s.bx = cpu.pop()
            s.dx = cpu.pop()
            s.cx = cpu.pop()
            s.ax = cpu.pop()
            # 1010:61E1  07           pop es
            cpu.set_sreg(0, cpu.pop())
            # 1010:61E2  1f           pop ds
            cpu.set_sreg(3, cpu.pop())
            # 1010:61E3  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_6168.owns_time = True

