"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:4E2E  (16 instructions, 7 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x4E2E)
SIGNATURE = bytes.fromhex('c80000005657687c0de8e1f2')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x4E2E, 1: 0x4E3A, 2: 0x4E40, 3: 0x4E45, 4: 0x4E48, 5: 0x4E4B, 6: 0x4E4E}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:4E3A": 1, "1010:4E40": 2, "1010:4E4B": 5, "1010:4E4E": 6}


def lifted_1010_4e2e(cpu, bb=0):
    """Lifted replacement for 1010:4E2E."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x4E2E, SIGNATURE, 'lifted_1010_4e2e')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:4E2E  c8000000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            # 1010:4E32  56           push r16
            cpu.push(s.si)
            # 1010:4E33  57           push r16
            cpu.push(s.di)
            # 1010:4E34  687c0d       push imm16
            cpu.push(0xD7C)
            # 1010:4E37  e8e1f2       call
            cpu.instruction_count += 5
            emulate_call(cpu, 0x1010, 0x411B, 0x4E3A)
            bb = 1
        elif bb == 1:
            # 1010:4E3A  83c402       grp1 rm16,imm8sx
            _a = s.sp
            _b = 0x2
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 16)
            s.sp = (_r & 0xFFFF) & 0xFFFF
            # 1010:4E3D  e888ff       call
            cpu.instruction_count += 2
            emulate_call(cpu, 0x1010, 0x4DC8, 0x4E40)
            bb = 2
        elif bb == 2:
            # 1010:4E40  3d0000       cmp
            _a = s.ax
            _b = 0x0
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            # 1010:4E43  7503         jnz
            cpu.instruction_count += 2
            bb = 4 if cpu.condition(0x5) else 3
        elif bb == 3:
            # 1010:4E45  e90300       jmp
            cpu.instruction_count += 1
            bb = 5
        elif bb == 4:
            # 1010:4E48  e87dff       call
            cpu.instruction_count += 1
            emulate_call(cpu, 0x1010, 0x4DC8, 0x4E4B)
            bb = 5
        elif bb == 5:
            # 1010:4E4B  e8eef2       call
            cpu.instruction_count += 1
            emulate_call(cpu, 0x1010, 0x413C, 0x4E4E)
            bb = 6
        elif bb == 6:
            # 1010:4E4E  5f           pop r16
            s.di = cpu.pop()
            # 1010:4E4F  5e           pop r16
            s.si = cpu.pop()
            # 1010:4E50  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:4E51  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_4e2e.owns_time = True

