"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:0EEB  (12 instructions, 5 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x0EEB)
SIGNATURE = bytes.fromhex('c802000056578b360016e90000')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x0EEB, 1: 0x0EF8, 2: 0x0EFC, 3: 0x0EFE, 4: 0x0F01}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches
#: re-entry points into this body: every INT (a blocking host service
#: rewinds IP onto it and retries), plus -- when boundary observation
#: is on -- head successors and call-site continuations (the unwind
#: re-entry rule). address -> dispatch block index; the installer
#: registers a re-entry hook at each.
RESUME_ENTRIES = {"1010:0EF8": 1, "1010:0EFC": 2}


def lifted_1010_0eeb(cpu, bb=0):
    """Lifted replacement for 1010:0EEB."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x0EEB, SIGNATURE, 'lifted_1010_0eeb')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:0EEB  c8020000     enter
            cpu.push(s.bp & 0xFFFF)
            s.bp = s.sp & 0xFFFF
            s.sp = (s.sp - 0x2) & 0xFFFF
            # 1010:0EEF  56           push r16
            cpu.push(s.si)
            # 1010:0EF0  57           push r16
            cpu.push(s.di)
            # 1010:0EF1  8b360016     mov
            _o = 0x1600
            s.si = (mem.rw(s.ds, _o)) & 0xFFFF
            # 1010:0EF5  e90000       jmp
            cpu.instruction_count += 5
            bb = 1
        elif bb == 1:
            # 1010:0EF8  39360016     cmp
            _o = 0x1600
            _a = mem.rw(s.ds, _o)
            _b = s.si
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 16)
            cpu.instruction_count += 1
            if cpu.boundary_hook is not None:
                cpu.boundary_hook(cpu, 0x1010, 0x0EF8, 0x0EFC)
            bb = 2
        elif bb == 2:
            # 1010:0EFC  7503         jnz
            cpu.instruction_count += 1
            bb = 4 if cpu.condition(0x5) else 3
        elif bb == 3:
            # 1010:0EFE  e9f7ff       jmp
            cpu.instruction_count += 1
            bb = 1
        elif bb == 4:
            # 1010:0F01  5f           pop r16
            s.di = cpu.pop()
            # 1010:0F02  5e           pop r16
            s.si = cpu.pop()
            # 1010:0F03  c9           leave
            s.sp = s.bp
            s.bp = cpu.pop()
            # 1010:0F04  c3           ret
            cpu.instruction_count += 4
            s.ip = cpu.pop()
            return
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_0eeb.owns_time = True

