"""AUTOGENERATED by dos_re.lift -- literal lift. DO NOT hand-edit in place.

Function 1010:59EF  (26 instructions, 6 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet -- they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 stuck_error,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x59EF)
SIGNATURE = bytes.fromhex('8a64018ac425c03f02a53c0c80fc3f76')
MAX_ITERATIONS = 100000000  # backstop only -- the no-progress detector below is the real guard
#: dispatch block -> its leader address (for the stuck diagnosis)
BLOCK_ADDRS = {0: 0x5892, 1: 0x58A1, 2: 0x58A4, 3: 0x59EF, 4: 0x5A00, 5: 0x5A02}
PROGRESS_SAMPLE = 0xFFFF  # sample the state every 64K dispatches


def lifted_1010_59ef(cpu, bb=3):
    """Lifted replacement for 1010:59EF."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x59EF, SIGNATURE, 'lifted_1010_59ef')
    s, mem = cpu.s, cpu.mem
    # A lifted function runs SYNCHRONOUSLY to completion: the interpreter
    # interleaves the outside world between instructions, but nothing
    # external can happen inside a lifted body -- so a loop WAITING for the
    # world to change waits forever. Detect that precisely rather than
    # guessing from an iteration count: a spin returns to the same block
    # with IDENTICAL registers, which is provably no progress; a long but
    # honest loop (a decompressor) advances its registers and is never
    # reported. MAX_ITERATIONS remains only as a backstop.
    _last_snap = None
    for _guard in range(MAX_ITERATIONS):
        if not _guard & PROGRESS_SAMPLE:
            _snap = (bb, s.ax, s.bx, s.cx, s.dx, s.si, s.di,
                     s.bp, s.sp, s.ds, s.es, s.flags)
            if _snap == _last_snap:
                raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                                  iterations=_guard,
                                  no_progress=PROGRESS_SAMPLE + 1)
            _last_snap = _snap
        if bb == 0:
            # 1010:5892  ee           out dx,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (s.dx) & 0xFFFF, _val, 8)
            # 1010:5893  ec           in al,dx
            _val = cpu.port_reader(cpu, (s.dx) & 0xFFFF, 8) if cpu.port_reader else 0
            cpu.set_reg8(0, _val)
            # 1010:5894  ec           in al,dx
            _val = cpu.port_reader(cpu, (s.dx) & 0xFFFF, 8) if cpu.port_reader else 0
            cpu.set_reg8(0, _val)
            # 1010:5895  ec           in al,dx
            _val = cpu.port_reader(cpu, (s.dx) & 0xFFFF, 8) if cpu.port_reader else 0
            cpu.set_reg8(0, _val)
            # 1010:5896  ec           in al,dx
            _val = cpu.port_reader(cpu, (s.dx) & 0xFFFF, 8) if cpu.port_reader else 0
            cpu.set_reg8(0, _val)
            # 1010:5897  ec           in al,dx
            _val = cpu.port_reader(cpu, (s.dx) & 0xFFFF, 8) if cpu.port_reader else 0
            cpu.set_reg8(0, _val)
            # 1010:5898  ec           in al,dx
            _val = cpu.port_reader(cpu, (s.dx) & 0xFFFF, 8) if cpu.port_reader else 0
            cpu.set_reg8(0, _val)
            # 1010:5899  8ac4         mov
            cpu.set_reg8(0, cpu.get_reg8(4))
            # 1010:589B  42           inc r16
            _old = s.dx
            _r = (_old + 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=False)
            s.dx = _r
            # 1010:589C  ee           out dx,al
            _val = cpu.get_reg8(0)
            if cpu.port_writer:
                cpu.port_writer(cpu, (s.dx) & 0xFFFF, _val, 8)
            # 1010:589D  4a           dec r16
            _old = s.dx
            _r = (_old - 1) & 0xFFFF
            cpu.set_incdec_flags(_old, _r, 16, dec=True)
            s.dx = _r
            # 1010:589E  b92300       mov r16,imm16
            s.cx = 0x23
            cpu.instruction_count += 12
            bb = 1
        elif bb == 1:
            # 1010:58A1  ec           in al,dx
            _val = cpu.port_reader(cpu, (s.dx) & 0xFFFF, 8) if cpu.port_reader else 0
            cpu.set_reg8(0, _val)
            # 1010:58A2  e2fd         loop
            cpu.instruction_count += 2
            s.cx = (s.cx - 1) & 0xFFFF
            bb = 1 if (s.cx != 0) else 2
        elif bb == 2:
            # 1010:58A4  c3           ret
            cpu.instruction_count += 1
            s.ip = cpu.pop()
            return
        elif bb == 3:
            # 1010:59EF  8a6401       mov
            _o = (s.si + 0x1) & 0xFFFF
            cpu.set_reg8(4, mem.rb(s.ds, _o))
            # 1010:59F2  8ac4         mov
            cpu.set_reg8(0, cpu.get_reg8(4))
            # 1010:59F4  25c03f       and
            _a = s.ax
            _b = 0x3FC0
            _r = _a & _b
            cpu.set_logic_flags(_r, 16)
            s.ax = (_r & 0xFFFF) & 0xFFFF
            # 1010:59F7  02a53c0c     add
            _o = (s.di + 0xC3C) & 0xFFFF
            _a = cpu.get_reg8(4)
            _b = mem.rb(s.ds, _o)
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 8)
            cpu.set_reg8(4, _r & 0xFF)
            # 1010:59FB  80fc3f       grp1 rm8,imm8
            _a = cpu.get_reg8(4)
            _b = 0x3F
            _r = _a - _b
            cpu.set_sub_flags(_a, _b, _r, 8)
            # 1010:59FE  7602         jbe
            cpu.instruction_count += 6
            bb = 5 if cpu.condition(0x6) else 4
        elif bb == 4:
            # 1010:5A00  b43f         mov r8,imm8
            cpu.set_reg8(4, 0x3F)
            cpu.instruction_count += 1
            bb = 5
        elif bb == 5:
            # 1010:5A02  0ae0         or
            _a = cpu.get_reg8(4)
            _b = cpu.get_reg8(0)
            _r = _a | _b
            cpu.set_logic_flags(_r, 8)
            cpu.set_reg8(4, _r & 0xFF)
            # 1010:5A04  8a871b0c     mov
            _o = (s.bx + 0xC1B) & 0xFFFF
            cpu.set_reg8(0, mem.rb(s.ds, _o))
            # 1010:5A08  0440         add
            _a = cpu.get_reg8(0)
            _b = 0x40
            _r = _a + _b
            cpu.set_add_flags(_a, _b, _r, 8)
            cpu.set_reg8(0, _r & 0xFF)
            # 1010:5A0A  e985fe       jmp
            cpu.instruction_count += 4
            bb = 0
    raise stuck_error(__name__, cpu, bb, BLOCK_ADDRS,
                      iterations=MAX_ITERATIONS, no_progress=0)


# Virtual-time preservation: this function accounts its own
# instruction_count per block, so step() must not add its dispatch +1.
lifted_1010_59ef.owns_time = True

