"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:4331. DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from skyroads.recovered.func_1010_4153 import func_1010_4153
from skyroads.recovered.func_1010_6168 import func_1010_6168

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000


def func_1010_4331(mem, plat, *, _base=0, _df=0, _flags_in=2, ax=0, bp=0, bx=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compatibility input)
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 1010:4331 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:4331
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bp)
            bp = sp
            sp = (sp - 22) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            _a = mem.rw(ds, 0x3C)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 5
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 2
                continue
            bb = 1
            continue
        if bb == 1:  # 1010:433E
            _cost += 1
            bb = 3
            continue
        if bb == 2:  # 1010:4341
            _cost += 1
            bb = 20
            continue
        if bb == 3:  # 1010:4344
            mem.ww(ds, 0x1600, (0x0) & 0xFFFF)
            _cost += 1
            bb = 4
            continue
        if bb == 4:  # 1010:434A
            _a = mem.rw(ss, ((bp + 8) & 0xFFFF))
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            _bw = (_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)
            _bo = plat.boundary(0x1010, 0x434A, 0x434E, {'ax': ax, 'cx': cx, 'dx': dx, 'bx': bx, 'sp': sp, 'bp': bp, 'si': si, 'di': di, 'ds': ds, 'es': es, 'ss': ss, 'cs': 0x1010, '_df': (1 if df else 0), '_flags_in': _bw}, _base + _cost + 1)
            ax = _bo[0]['ax']
            cx = _bo[0]['cx']
            dx = _bo[0]['dx']
            bx = _bo[0]['bx']
            sp = _bo[0]['sp']
            bp = _bo[0]['bp']
            si = _bo[0]['si']
            di = _bo[0]['di']
            ds = _bo[0]['ds']
            es = _bo[0]['es']
            ss = _bo[0]['ss']
            _bf = _bo[1]
            cf = (_bf & 0x1) != 0
            pf = (_bf & 0x4) != 0
            af = (_bf & 0x10) != 0
            zf = (_bf & 0x40) != 0
            sf = (_bf & 0x80) != 0
            of = (_bf & 0x800) != 0
            intf = (_bf & 0x200) != 0
            df = (_bf & 0x400) != 0
            _fmask |= 0xED5
            _cost += _bo[2]
            _cost += 2
            if not zf:
                bb = 6
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:4350
            _cost += 1
            bb = 7
            continue
        if bb == 6:  # 1010:4353
            ax = 0x64
            _b = mem.rw(ds, 0x1600)
            _sa = ax - 0x10000 if ax & 0x8000 else ax
            _sb = _b - 0x10000 if _b & 0x8000 else _b
            _t = _sa * _sb
            ax = _t & 0xFFFF
            dx = (_t >> 16) & 0xFFFF
            cf = of = not (-32768 <= _t <= 32767)
            _a = dx
            _b = dx
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            dx = _t & 0xFFFF
            _b = mem.rw(ss, ((bp + 8) & 0xFFFF))
            if _b == 0:
                raise ZeroDivisionError('div by zero (recovered)')
            _q, _r = divmod((dx << 16) | ax, _b)
            if _q > 0xFFFF:
                raise OverflowError('16-bit div quotient overflow')
            ax = _q & 0xFFFF
            dx = _r & 0xFFFF
            mem.ww(ss, ((bp + -4) & 0xFFFF), (ax) & 0xFFFF)
            _cost += 6
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 8
            continue
        if bb == 7:  # 1010:4365
            mem.ww(ss, ((bp + -4) & 0xFFFF), (0x64) & 0xFFFF)
            _cost += 1
            bb = 8
            continue
        if bb == 8:  # 1010:436A
            _a = mem.rw(ss, ((bp + -4) & 0xFFFF))
            _b = 0x64
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf or (sf != of):
                bb = 10
                continue
            bb = 9
            continue
        if bb == 9:  # 1010:4370
            _cost += 1
            bb = 12
            continue
        if bb == 10:  # 1010:4373
            _a = mem.rw(ds, 0x54A0)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 12
                continue
            bb = 11
            continue
        if bb == 11:  # 1010:437A
            _cost += 1
            bb = 13
            continue
        if bb == 12:  # 1010:437D
            mem.ww(ss, ((bp + -4) & 0xFFFF), (0x64) & 0xFFFF)
            _cost += 1
            bb = 13
            continue
        if bb == 13:  # 1010:4382
            mem.ww(ss, ((bp + -14) & 0xFFFF), (0x31A8) & 0xFFFF)
            bx = mem.rw(ss, ((bp + 4) & 0xFFFF))
            ax = mem.rw(ds, ((bx) & 0xFFFF))
            mem.ww(ss, ((bp + -6) & 0xFFFF), (ax) & 0xFFFF)
            mem.ww(ss, ((bp + -8) & 0xFFFF), (0x0) & 0xFFFF)
            bx = mem.rw(ss, ((bp + 6) & 0xFFFF))
            ax = mem.rw(ds, ((bx) & 0xFFFF))
            mem.ww(ss, ((bp + -10) & 0xFFFF), (ax) & 0xFFFF)
            mem.ww(ss, ((bp + -12) & 0xFFFF), (0x0) & 0xFFFF)
            mem.ww(ss, ((bp + -2) & 0xFFFF), (0x0) & 0xFFFF)
            _cost += 11
            bb = 15
            continue
        if bb == 14:  # 1010:43A9
            ax = mem.rw(ss, ((bp + -2) & 0xFFFF))
            _a = mem.rw(ss, ((bp + -2) & 0xFFFF))
            _b = 0x1
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            mem.ww(ss, ((bp + -2) & 0xFFFF), (_t) & 0xFFFF)
            mem.ww(ss, ((bp + -16) & 0xFFFF), (ax) & 0xFFFF)
            ax = mem.rw(ss, ((bp + -14) & 0xFFFF))
            _a = mem.rw(ss, ((bp + -14) & 0xFFFF))
            _b = 0x1
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            mem.ww(ss, ((bp + -14) & 0xFFFF), (_t) & 0xFFFF)
            mem.ww(ss, ((bp + -18) & 0xFFFF), (ax) & 0xFFFF)
            ax = mem.rw(ss, ((bp + -8) & 0xFFFF))
            es = mem.rw(ss, ((bp + -6) & 0xFFFF))
            _a = mem.rw(ss, ((bp + -8) & 0xFFFF))
            _b = 0x1
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            mem.ww(ss, ((bp + -8) & 0xFFFF), (_t) & 0xFFFF)
            dx = (es) & 0xFFFF
            mem.ww(ss, ((bp + -22) & 0xFFFF), (ax) & 0xFFFF)
            mem.ww(ss, ((bp + -20) & 0xFFFF), (dx) & 0xFFFF)
            ax = mem.rw(ss, ((bp + -12) & 0xFFFF))
            es = mem.rw(ss, ((bp + -10) & 0xFFFF))
            _a = mem.rw(ss, ((bp + -12) & 0xFFFF))
            _b = 0x1
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            mem.ww(ss, ((bp + -12) & 0xFFFF), (_t) & 0xFFFF)
            dx = (es) & 0xFFFF
            _cost += 16
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 15
            continue
        if bb == 15:  # 1010:43DB
            ax = mem.rw(ss, ((bp + -2) & 0xFFFF))
            mem.ww(ss, ((bp + -16) & 0xFFFF), (ax) & 0xFFFF)
            ax = 0x3
            bx = mem.rw(ss, ((bp + 4) & 0xFFFF))
            _b = mem.rw(ds, ((bx + 4) & 0xFFFF))
            _sa = ax - 0x10000 if ax & 0x8000 else ax
            _sb = _b - 0x10000 if _b & 0x8000 else _b
            _t = _sa * _sb
            ax = _t & 0xFFFF
            dx = (_t >> 16) & 0xFFFF
            cf = of = not (-32768 <= _t <= 32767)
            cx = mem.rw(ss, ((bp + -16) & 0xFFFF))
            _a = cx
            _b = ax
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 8
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if cf:
                bb = 17
                continue
            bb = 16
            continue
        if bb == 16:  # 1010:43F1
            _cost += 1
            bb = 18
            continue
        if bb == 17:  # 1010:43F4
            _o = ((bp + -8) & 0xFFFF)
            bx = mem.rw(ss, _o)
            es = mem.rw(ss, (_o + 2) & 0xFFFF)
            ax = (ax & 0xFF00) | ((mem.rb(es, ((bx) & 0xFFFF))) & 0xFF)
            _a = ax
            _b = 0xFF
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = _t & 0xFFFF
            _o = ((bp + -12) & 0xFFFF)
            bx = mem.rw(ss, _o)
            es = mem.rw(ss, (_o + 2) & 0xFFFF)
            mem.ww(ss, ((bp + -16) & 0xFFFF), (ax) & 0xFFFF)
            ax = (ax & 0xFF00) | ((mem.rb(es, ((bx) & 0xFFFF))) & 0xFF)
            _a = ax
            _b = 0xFF
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = _t & 0xFFFF
            cx = mem.rw(ss, ((bp + -16) & 0xFFFF))
            _a = ax
            _b = cx
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            ax = _t & 0xFFFF
            _b = mem.rw(ss, ((bp + -4) & 0xFFFF))
            _sa = ax - 0x10000 if ax & 0x8000 else ax
            _sb = _b - 0x10000 if _b & 0x8000 else _b
            _t = _sa * _sb
            ax = _t & 0xFFFF
            dx = (_t >> 16) & 0xFFFF
            cf = of = not (-32768 <= _t <= 32767)
            cx = 0x64
            dx = 0xFFFF if ax & 0x8000 else 0
            _b = cx
            if _b == 0:
                raise ZeroDivisionError('idiv by zero (recovered)')
            _d = (dx << 16) | ax
            if _d & 0x80000000: _d -= 0x100000000
            _v = _b - 0x10000 if _b & 0x8000 else _b
            _q = int(_d / _v); _r = _d - _q * _v
            if _q < -32768 or _q > 32767:
                raise OverflowError('16-bit idiv quotient overflow')
            ax = _q & 0xFFFF
            dx = _r & 0xFFFF
            _o = ((bp + -8) & 0xFFFF)
            bx = mem.rw(ss, _o)
            es = mem.rw(ss, (_o + 2) & 0xFFFF)
            mem.ww(ss, ((bp + -18) & 0xFFFF), (ax) & 0xFFFF)
            ax = (ax & 0xFF00) | ((mem.rb(es, ((bx) & 0xFFFF))) & 0xFF)
            _a = ax
            _b = 0xFF
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = _t & 0xFFFF
            cx = mem.rw(ss, ((bp + -18) & 0xFFFF))
            _a = ax
            _b = cx
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            ax = _t & 0xFFFF
            bx = mem.rw(ss, ((bp + -14) & 0xFFFF))
            mem.wb(ds, ((bx) & 0xFFFF), ((ax & 0xFF)) & 0xFF)
            _cost += 22
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 14
            continue
        if bb == 18:  # 1010:4430
            ax = 0x31A8
            dx = (ds) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, dx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            bx = mem.rw(ss, ((bp + 4) & 0xFFFF))
            _t = mem.rw(ds, ((bx + 4) & 0xFFFF))
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, _t)
            bx = mem.rw(ss, ((bp + 4) & 0xFFFF))
            _t = mem.rw(ds, ((bx + 2) & 0xFFFF))
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, _t)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x4446)
            _o, _c = func_1010_6168(mem, plat, _base=_base + _cost + 9, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x8
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x444C)
            _o, _c = func_1010_4153(mem, plat, _base=_base + _cost + 11, _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = mem.rw(ss, ((bp + -4) & 0xFFFF))
            _b = 0x64
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 13
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 20
                continue
            bb = 19
            continue
        if bb == 19:  # 1010:4452
            _cost += 1
            bb = 4
            continue
        if bb == 20:  # 1010:4455
            di = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            si = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            sp = bp
            bp = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 4
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

