"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:1218. DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from skyroads.recovered.func_1010_1191 import func_1010_1191
from skyroads.recovered.func_1010_11d3 import func_1010_11d3

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000


def func_1010_1218(mem, *, bp=0, bx=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 1010:1218 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:1218
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bp)
            bp = sp
            sp = (sp - 6) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            ax = mem.rw(ss, ((bp + 4) & 0xFFFF))
            _a = ax
            _b = 0x2A
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            ax = _t & 0xFFFF
            si = ax
            di = 0x8F
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x122E)
            _o, _c = func_1010_1191(mem, ax=ax, bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x4
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            mem.ww(ss, ((bp + -6) & 0xFFFF), (ax) & 0xFFFF)
            _cost += 12
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 1
            continue
        if bb == 1:  # 1010:1234
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x1239)
            _o, _c = func_1010_1191(mem, ax=ax, bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x4
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            _a = ax
            _b = mem.rw(ss, ((bp + -6) & 0xFFFF))
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 6
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 3
                continue
            bb = 2
            continue
        if bb == 2:  # 1010:1241
            _cost += 1
            bb = 4
            continue
        if bb == 3:  # 1010:1244
            _a = di
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 1
            continue
        if bb == 4:  # 1010:124A
            _a = di
            _b = 0x1
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            ax = di
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x1254)
            _o, _c = func_1010_1191(mem, ax=ax, bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x4
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            _a = ax
            _b = mem.rw(ss, ((bp + -6) & 0xFFFF))
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 8
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 6
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:125C
            _cost += 1
            bb = 11
            continue
        if bb == 6:  # 1010:125F
            _a = mem.rw(ds, 0x3C)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 8
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:1266
            _cost += 1
            bb = 9
            continue
        if bb == 8:  # 1010:1269
            ax = 0x60
            _cost += 2
            bb = 10
            continue
        if bb == 9:  # 1010:126F
            ax = 0x6
            _cost += 1
            bb = 10
            continue
        if bb == 10:  # 1010:1272
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x1278)
            _o, _c = func_1010_11d3(mem, ax=ax, bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x6
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            _cost += 6
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 4
            continue
        if bb == 11:  # 1010:127E
            di = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            si = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            sp = bp
            bp = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 4
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

