"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:3F91. DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from skyroads.recovered.func_1010_6490 import func_1010_6490
from skyroads.recovered.func_1010_6576 import func_1010_6576
from skyroads.recovered.func_1010_6595 import func_1010_6595

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000


def func_1010_3f91(mem, plat, *, _base=0, _df=0, _flags_in=2, bp=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compatibility input)
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 1010:3F91 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:3F91
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bp)
            bp = sp
            sp = (sp - 2) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x3F9A)
            _o, _c = func_1010_6576(mem, plat, _base=_base + _cost + 4, _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), bp=bp, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x3F9D)
            _o, _c = func_1010_6576(mem, plat, _base=_base + _cost + 5, _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), bp=bp, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x3FA0)
            _o, _c = func_1010_6490(mem, plat, _base=_base + _cost + 6, _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), bp=bp, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            si = ax
            _a = mem.rw(ds, 0x41AA)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 9
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 2
                continue
            bb = 1
            continue
        if bb == 1:  # 1010:3FA9
            _cost += 1
            bb = 3
            continue
        if bb == 2:  # 1010:3FAC
            ax = 0x3
            _b = si
            _sa = ax - 0x10000 if ax & 0x8000 else ax
            _sb = _b - 0x10000 if _b & 0x8000 else _b
            _t = _sa * _sb
            ax = _t & 0xFFFF
            dx = (_t >> 16) & 0xFFFF
            cf = of = not (-32768 <= _t <= 32767)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            ax = 0x3
            _b = mem.rw(ss, ((bp + 6) & 0xFFFF))
            _sa = ax - 0x10000 if ax & 0x8000 else ax
            _sb = _b - 0x10000 if _b & 0x8000 else _b
            _t = _sa * _sb
            ax = _t & 0xFFFF
            dx = (_t >> 16) & 0xFFFF
            cf = of = not (-32768 <= _t <= 32767)
            cx = mem.rw(ss, ((bp + 4) & 0xFFFF))
            _a = cx
            _b = ax
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            cx = _t & 0xFFFF
            dx = (ds) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, dx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, cx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x3FC4)
            _o, _c = func_1010_6595(mem, plat, _base=_base + _cost + 11, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x6
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            _cost += 12
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 3
            continue
        if bb == 3:  # 1010:3FC7
            ax = si
            _n = 1
            _a = ax
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                ax = (_t) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            ax = 0xAF3C
            dx = (ds) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, dx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x3FD6)
            _o, _c = func_1010_6595(mem, plat, _base=_base + _cost + 8, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x6
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            ax = si
            _cost += 11
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 4
            continue
        if bb == 4:  # 1010:3FDE
            di = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            si = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            sp = bp
            bp = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 4
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

