"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:3BCC (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000


def func_1010_3bcc(mem, plat, *, _base=0, ax=0, bp=0, bx=0, cx=0, di=0, ds=0, dx=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 1010:3BCC (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:3BCC
            _sp0 = sp
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, cx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, dx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, _sp0)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bp)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ds)
            ds = mem.rw(cs, 0x3ACA)
            _pv = plat.inp(0x60, 1, _base + _cost + 3)
            ax = (ax & 0xFF00) | ((_pv) & 0xFF)
            bx = 0xBD2
            _cost += 5
            bb = 1
            continue
        if bb == 1:  # 1010:3BD8
            _a = (ax & 0xFF)
            _b = mem.rb(ds, ((bx) & 0xFFFF))
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 3
                continue
            bb = 2
            continue
        if bb == 2:  # 1010:3BDC
            _a = bx
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            bx = _t & 0xFFFF
            _t = (mem.rb(ds, ((bx) & 0xFFFF))) & 0x7F
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 1
                continue
            bb = 3
            continue
        if bb == 3:  # 1010:3BE2
            _a = mem.rb(ds, ((bx) & 0xFFFF))
            _b = 0x7F
            _t = _a & _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            mem.wb(ds, ((bx) & 0xFFFF), (_t) & 0xFF)
            _a = (ax & 0xFF)
            _b = 0x80
            _t = _a & _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _a = (ax & 0xFF)
            _b = 0x80
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _a = mem.rb(ds, ((bx) & 0xFFFF))
            _b = (ax & 0xFF)
            _t = _a | _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            mem.wb(ds, ((bx) & 0xFFFF), (_t) & 0xFF)
            _pv = plat.inp(0x61, 1, _base + _cost + 4)
            ax = (ax & 0xFF00) | ((_pv) & 0xFF)
            ax = (ax & 0x00FF) | ((((ax & 0xFF)) & 0xFF) << 8)
            _a = (ax & 0xFF)
            _b = 0x80
            _t = _a | _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            plat.outp(0x61, (ax & 0xFF), 1, _base + _cost + 7)
            ax = (ax & 0xFF00) | ((((ax >> 8) & 0xFF)) & 0xFF)
            plat.outp(0x61, (ax & 0xFF), 1, _base + _cost + 9)
            ax = (ax & 0xFF00) | ((0x20) & 0xFF)
            plat.outp(0x20, (ax & 0xFF), 1, _base + _cost + 11)
            ds = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            di = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            si = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            bp = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            sp = (sp + 2) & 0xFFFF
            bx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            dx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            cx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            ax = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 15
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

