"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:0F8C (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from skyroads.cpuless_standalone.func_1010_0f62 import func_1010_0f62
from skyroads.cpuless_standalone.func_1010_3c9a import func_1010_3c9a
from skyroads.cpuless_standalone.func_1010_417e import func_1010_417e
from skyroads.cpuless_standalone.func_1010_4201 import func_1010_4201

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))


def func_1010_0f8c(mem, plat, *, _base=0, _df=0, bp=0, di=0, ds=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 1010:0F8C (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:0F8C
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bp)
            bp = sp
            sp = (sp - 14) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            _a = mem.rw(ds, 0x3C)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 5
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 2
                continue
            bb = 1
            continue
        if bb == 1:  # 1010:0F99
            _cost += 1
            bb = 11
            continue
        if bb == 2:  # 1010:0F9C
            _a = mem.rw(ss, ((bp + 8) & 0xFFFF))
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 4
                continue
            bb = 3
            continue
        if bb == 3:  # 1010:0FA2
            _cost += 1
            bb = 5
            continue
        if bb == 4:  # 1010:0FA5
            ax = 0x5E
            _cost += 2
            bb = 6
            continue
        if bb == 5:  # 1010:0FAB
            ax = 0x5C
            _cost += 1
            bb = 6
            continue
        if bb == 6:  # 1010:0FAE
            si = ax
            _a = mem.rw(ss, ((bp + 8) & 0xFFFF))
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 8
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:0FB6
            _cost += 1
            bb = 9
            continue
        if bb == 8:  # 1010:0FB9
            ax = 0x5F
            _cost += 2
            bb = 10
            continue
        if bb == 9:  # 1010:0FBF
            ax = 0x5D
            _cost += 1
            bb = 10
            continue
        if bb == 10:  # 1010:0FC2
            di = ax
            _cost += 2
            bb = 16
            continue
        if bb == 11:  # 1010:0FC7
            si = 0x0
            _a = mem.rw(ss, ((bp + 8) & 0xFFFF))
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 13
                continue
            bb = 12
            continue
        if bb == 12:  # 1010:0FD0
            _cost += 1
            bb = 14
            continue
        if bb == 13:  # 1010:0FD3
            ax = 0x5
            _cost += 2
            bb = 15
            continue
        if bb == 14:  # 1010:0FD9
            ax = 0x8
            _cost += 1
            bb = 15
            continue
        if bb == 15:  # 1010:0FDC
            di = ax
            _cost += 1
            bb = 16
            continue
        if bb == 16:  # 1010:0FDE
            ax = mem.rw(ds, 0xAF2A)
            mem.ww(ss, ((bp + -14) & 0xFFFF), (ax) & 0xFFFF)
            _o = ((bp + 4) & 0xFFFF)
            bx = mem.rw(ss, _o)
            es = mem.rw(ss, (_o + 2) & 0xFFFF)
            ax = mem.rw(es, ((bx) & 0xFFFF))
            mem.ww(ss, ((bp + -12) & 0xFFFF), (ax) & 0xFFFF)
            _o = ((bp + 4) & 0xFFFF)
            bx = mem.rw(ss, _o)
            es = mem.rw(ss, (_o + 2) & 0xFFFF)
            ax = (ax & 0xFF00) | ((mem.rb(es, ((bx + 2) & 0xFFFF))) & 0xFF)
            _a = ax
            _b = 0xFF
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = _t & 0xFFFF
            mem.ww(ss, ((bp + -8) & 0xFFFF), (ax) & 0xFFFF)
            _o = ((bp + 4) & 0xFFFF)
            bx = mem.rw(ss, _o)
            es = mem.rw(ss, (_o + 2) & 0xFFFF)
            ax = (ax & 0xFF00) | ((mem.rb(es, ((bx + 3) & 0xFFFF))) & 0xFF)
            _a = ax
            _b = 0xFF
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = _t & 0xFFFF
            mem.ww(ss, ((bp + -10) & 0xFFFF), (ax) & 0xFFFF)
            ax = mem.rw(ss, ((bp + -8) & 0xFFFF))
            _b = mem.rw(ss, ((bp + -10) & 0xFFFF))
            _sa = ax - 0x10000 if ax & 0x8000 else ax
            _sb = _b - 0x10000 if _b & 0x8000 else _b
            _t = _sa * _sb
            ax = _t & 0xFFFF
            dx = (_t >> 16) & 0xFFFF
            cf = of = not (-32768 <= _t <= 32767)
            mem.ww(ss, ((bp + -6) & 0xFFFF), (ax) & 0xFFFF)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            _t = mem.rw(ss, ((bp + -6) & 0xFFFF))
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, _t)
            ax = mem.rw(ss, ((bp + 4) & 0xFFFF))
            dx = mem.rw(ss, ((bp + 6) & 0xFFFF))
            _a = ax
            _b = 0x4
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            ax = _t & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, dx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x1023)
            _o, _c = func_1010_0f62(mem, _df=(1 if df else 0), ax=ax, bp=bp, di=di, ds=ds, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0xA
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            _a = mem.rw(ds, 0x3C)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 28
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 18
                continue
            bb = 17
            continue
        if bb == 17:  # 1010:102D
            _cost += 1
            bb = 19
            continue
        if bb == 18:  # 1010:1030
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x1033)
            _o, _c = func_1010_3c9a(mem, plat, _base=_base + _cost, ax=ax, ds=ds, dx=dx, ss=ss)
            ax = _o['ax']
            dx = _o['dx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 1
            bb = 19
            continue
        if bb == 19:  # 1010:1033
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x1)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x0)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xA000)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x0)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x103F)
            _o, _c = func_1010_417e(mem, bp=bp, di=di, ds=ds, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            di = _o['di']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x8
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            ax = ((bp + -14) & 0xFFFF) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x1049)
            _o, _c = func_1010_4201(mem, _df=(1 if df else 0), bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x2
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            _a = mem.rw(ds, 0x3C)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 12
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 21
                continue
            bb = 20
            continue
        if bb == 20:  # 1010:1053
            _cost += 1
            bb = 22
            continue
        if bb == 21:  # 1010:1056
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x1)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x0)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xA200)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x0)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x1062)
            _o, _c = func_1010_417e(mem, bp=bp, di=di, ds=ds, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            di = _o['di']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x8
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            ax = ((bp + -14) & 0xFFFF) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x106C)
            _o, _c = func_1010_4201(mem, _df=(1 if df else 0), bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = sp
            _b = 0x2
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            sp = (_t) & 0xFFFF
            _cost += 10
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 22
            continue
        if bb == 22:  # 1010:106F
            di = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            si = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            sp = bp
            bp = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 4
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

