"""Regenerate the STANDALONE CPUless corpus + its function manifest.

This is the TRUE no-CPU corpus (distinct from the hybrid overlay that
``build_cpuless_corpus.py`` produces).  Every function the game runs at runtime
is a pure-Python recovered module; the standalone runner (``play_cpuless.py``)
drives it through ``CPUlessPlatformRuntime`` with NO interpreter, NO lifted
graph, NO CPU object.

WHAT IS SOURCE vs GENERATED
  * SOURCE (committed): the census inputs under ``artifacts/codemap/``
    (recovery_ir.json, observed.json, boundary_heads.txt, dispatch tables) and
    the address-keyed manual overrides under ``skyroads/cpuless_overrides/``.
  * GENERATED (NOT committed; regenerated by this one command): the recovered
    package ``skyroads/cpuless_standalone/`` (gitignored, deterministic).
  * COMMITTED RECORD: ``artifacts/codemap/cpuless_manifest.json`` -- the
    persistent per-function status manifest this script writes, so a clean
    checkout can inspect the result without running the build.

THE STANDALONE PROMOTION CONFIG (differs from the hybrid on purpose):
  --boundary-heads   emit ``plat.boundary`` observers (standalone-only) instead
                     of --exclude (which keeps boundary functions lifted).
  --dyn-evidence     per-site dispatch targets filtered to OBSERVED selections
                     (find_dispatch_evidence --observed): an unselected table
                     entry becomes a fail-loud UnknownDispatchTarget.
  --observed         runtime-dead near CALLS and runtime-dead EXITS become
                     fail-loud stubs/raises (the hard wall, not a fallback).
  --desmc            runtime-patched operands (incl. the timer-ISR far chain)
                     read from live code memory.

Usage:
    python scripts/build_cpuless_standalone.py            # regenerate + manifest
    python scripts/build_cpuless_standalone.py --print-manifest
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CODEMAP = ROOT / "artifacts" / "codemap"
STANDALONE_DIR = ROOT / "skyroads" / "cpuless_standalone"
OVERRIDES_DIR = ROOT / "skyroads" / "cpuless_overrides"
IMPORT_BASE = "skyroads.cpuless_standalone"
MANIFEST = CODEMAP / "cpuless_manifest.json"
CANONICAL_ENTRY = "1010:61F3"          # the boot far-jump target (C startup)

IR = CODEMAP / "recovery_ir.json"
OBSERVED = CODEMAP / "observed.json"
BOUNDARY_HEADS = CODEMAP / "boundary_heads.txt"
DYN_OBS = CODEMAP / "dispatch_evidence_observed.json"   # generated, observed-only
CENSUS = CODEMAP / "cpuless_standalone_census.json"     # generated


def _load_pairs(path: Path) -> set[str]:
    out: set[str] = set()
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            out.add(line.upper())
    return out


def _closure_roots() -> str:
    obs = json.loads(OBSERVED.read_text(encoding="utf-8"))
    roots = {CANONICAL_ENTRY}
    roots |= {v.upper() for v in (obs.get("ivt_game_vectors") or {}).values()}
    roots |= {v.upper() for v in (obs.get("int_entries") or [])}
    for f in ("dispatch_extra.txt", "boundary_heads.txt", "snapshot_entries.txt"):
        roots |= _load_pairs(CODEMAP / f)
    return ",".join(sorted(roots))


def _override_keys() -> set[str]:
    """Address-keyed manual overrides: func_CCCC_IIII.py -> 'CCCC:IIII'."""
    out: set[str] = set()
    if not OVERRIDES_DIR.exists():
        return out
    for p in OVERRIDES_DIR.glob("func_*.py"):
        _, cs, ip = p.stem.split("_")
        out.add(f"{int(cs, 16):04X}:{int(ip, 16):04X}")
    return out


def _write_manifest(overrides: set[str]) -> dict:
    """Build the persistent per-function status manifest from the census +
    runtime closure + the generated corpus + the overrides."""
    sys.path.insert(0, str(ROOT / "dos_re"))
    from tools.cpuless_closure import walk_closure  # noqa: E402

    ir = json.loads(IR.read_text(encoding="utf-8"))
    all_keys = {k.upper() for k in ir["functions"]}
    promoted = {f"{int(cs, 16):04X}:{int(ip, 16):04X}"
                for cs, ip in (p.stem.split("_")[1:]
                               for p in STANDALONE_DIR.glob("func_*.py"))}
    census = json.loads(CENSUS.read_text(encoding="utf-8"))
    refused = {k.upper(): reason
               for reason, keys in census.get("refused", {}).items()
               for k in keys}

    dyn = {}
    for site in json.loads(DYN_OBS.read_text(encoding="utf-8")).get("sites", []):
        dyn[site["site"].upper()] = sorted(k.upper()
                                           for k in site.get("targets", {}))
    observed = {a.upper() for a in
                json.loads(OBSERVED.read_text(encoding="utf-8")).get("executed", ())
                if isinstance(a, str)}
    roots = [r.strip().upper() for r in _closure_roots().split(",") if r.strip()]
    rep = walk_closure(ir, roots, promoted, refused, dyn, observed)
    runtime_frontier = set(rep["runtime_frontier"])
    static_only = set(rep["static_only_frontier"])

    entries = {}
    for key in sorted(all_keys):
        rec = ir["functions"].get(key) or ir["functions"].get(key.lower(), {})
        is_data = bool(rec) and not rec.get("blocks")
        if key in overrides:
            status = "manual-cpuless-override"
        elif key in promoted:
            status = "generated-cpuless"
        elif is_data:
            status = "data-non-function"
        elif key in runtime_frontier:
            status = "fail-loud-unsupported"      # reachable but not promoted
        elif key in static_only or key in refused:
            status = "dead-unreachable"           # no runtime evidence it runs
        else:
            status = "dead-unreachable"
        entry = {"status": status}
        if key in refused:
            entry["refusal"] = refused[key]
        entries[key] = entry

    counts = Counter(e["status"] for e in entries.values())
    manifest = {
        "_notice": "GENERATED by scripts/build_cpuless_standalone.py -- the "
                   "persistent per-function status manifest for the STANDALONE "
                   "CPUless corpus. Regenerate with that script; do not "
                   "hand-edit. Statuses: generated-cpuless | "
                   "manual-cpuless-override | native-platform-replacement | "
                   "fail-loud-unsupported | dead-unreachable | data-non-function.",
        "import_base": IMPORT_BASE,
        "canonical_entry": CANONICAL_ENTRY,
        "counts": dict(sorted(counts.items())),
        "runtime_frontier": sorted(runtime_frontier),
        "runtime_closure_complete": bool(rep["closure_complete"]),
        # non-function addresses reached only via an UNTAKEN static call (no
        # runtime evidence they execute): resume points / external targets, not
        # IR functions. Reported, never dropped -- coverage is not proof of
        # deadness (docs/dead_code_analysis.md).
        "static_only_addresses": sorted(static_only),
        "functions": entries,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=1) + "\n", encoding="utf-8")
    return manifest


def build() -> int:
    # 1. per-site dispatch evidence, OBSERVED-filtered (standalone corpus).
    subprocess.run([sys.executable, str(ROOT / "scripts/find_dispatch_evidence.py"),
                    "--observed", str(OBSERVED), "--out", str(DYN_OBS)], check=True)

    # 2. fresh recovered package each build (a stale module for a since-refused
    #    function would import-resolve to dead code).
    if STANDALONE_DIR.exists():
        shutil.rmtree(STANDALONE_DIR)
    STANDALONE_DIR.mkdir(parents=True)
    (STANDALONE_DIR / "__init__.py").write_text(
        '"""GENERATED standalone CPUless corpus (dos_re stage 2).\n\n'
        "Build artifact -- regenerate with scripts/build_cpuless_standalone.py,\n"
        "do not hand-edit. Manual fixes go in skyroads/cpuless_overrides/ as\n"
        'address-keyed func_CCCC_IIII.py modules, layered on top here."""\n',
        encoding="utf-8")

    # 3. the STANDALONE promotion config (see the module docstring).
    # the CPU-ABI adapters are a HYBRID artifact (they bridge the interpreter to
    # a recovered body); the standalone runner calls recovered functions
    # directly, so route them to a throwaway dir OUTSIDE the pure corpus package
    # -- else the recovered-purity lint (rightly) flags their make_cpu_platform
    # import.
    adapters = ROOT / "artifacts" / "cpuless_standalone_adapters"
    if adapters.exists():
        shutil.rmtree(adapters)
    cmd = [sys.executable, str(ROOT / "dos_re/tools/cpuless_promote.py"),
           "--ir", str(IR),
           "--recovered-dir", str(STANDALONE_DIR),
           "--adapter-dir", str(adapters),
           "--import-base", IMPORT_BASE,
           "--boundary-heads", f"@{BOUNDARY_HEADS}",
           "--dyn-evidence", str(DYN_OBS),
           "--desmc",
           "--observed", str(OBSERVED),
           "--census-out", str(CENSUS),
           "--apply"]
    print("[standalone] " + " ".join(str(c) for c in cmd))
    r = subprocess.run(cmd, text=True)
    if r.returncode != 0:
        return r.returncode

    # 4. layer address-keyed manual overrides on top of the generated bodies.
    overrides = _override_keys()
    for p in OVERRIDES_DIR.glob("func_*.py") if OVERRIDES_DIR.exists() else ():
        shutil.copy2(p, STANDALONE_DIR / p.name)
    if overrides:
        print(f"[standalone] layered {len(overrides)} manual override(s): "
              + ", ".join(sorted(overrides)))

    # 5. the persistent status manifest.
    manifest = _write_manifest(overrides)
    n_rec = len(list(STANDALONE_DIR.glob("func_*.py")))
    print(f"\n[standalone] corpus ready: {n_rec} recovered modules -> "
          f"{STANDALONE_DIR}")
    print("[standalone] manifest: " + ", ".join(
        f"{k}={v}" for k, v in manifest["counts"].items()))
    print(f"[standalone] runtime frontier: {len(manifest['runtime_frontier'])} "
          f"(closure complete: {manifest['runtime_closure_complete']})")
    print(f"[standalone] wrote {MANIFEST.relative_to(ROOT)}")
    print("[standalone]   play:   python scripts/play_cpuless.py --headless")
    print("[standalone]   purity: python tools/lint_cpuless.py")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--print-manifest", action="store_true",
                    help="print the manifest counts and exit (no rebuild)")
    args = ap.parse_args(argv)
    if args.print_manifest:
        m = json.loads(MANIFEST.read_text(encoding="utf-8"))
        print(json.dumps(m["counts"], indent=1))
        print("runtime frontier:", m["runtime_frontier"])
        return 0
    return build()


if __name__ == "__main__":
    raise SystemExit(main())
