"""Regenerate the generated ABI-recovered corpus and its diagnostic manifest.

``skyroads/recovered/`` is one generated representation of the SkyRoads
program: pure Python over DOS-layout memory and platform services, with no CPU
object or instruction interpreter.  It is selected through
``skyroads.execution`` like every other implementation provider; this script
does not select or install handwritten overrides.

The committed ``recovery/recovery_ir.json`` is the Recovery IR input.
Generation also consumes local observed-transfer, boundary, and dynamic
dispatch facts under ``artifacts/codemap/``.  Those facts specialize this
particular generated corpus; they are not the project's coverage or release
authority.  The persistent Execution Atlas remains the planner's sole
closed-world coverage source.

The generated package is committed and regenerated in place so drift is
visible in git. CPU adapters, the generation census, and
``cpuless_manifest.json`` are local diagnostics under ``artifacts/``.

Usage:
    python scripts/build_recovered.py            # regenerate + manifest
    python scripts/build_recovered.py --print-manifest
"""
from __future__ import annotations

import argparse
import ast
import json
import shutil
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CODEMAP = ROOT / "artifacts" / "codemap"
RECOVERED_DIR = ROOT / "skyroads" / "recovered"
IMPORT_BASE = "skyroads.recovered"
MANIFEST = CODEMAP / "cpuless_manifest.json"
CANONICAL_ENTRY = "1010:61F3"          # the boot far-jump target (C startup)

IR = ROOT / "recovery" / "recovery_ir.json"
OBSERVED = CODEMAP / "observed.json"
BOUNDARY_HEADS = CODEMAP / "boundary_heads.txt"
DYN_OBS = CODEMAP / "dispatch_evidence_observed.json"   # generated, observed-only
CENSUS = CODEMAP / "recovered_census.json"     # generated


def _staticize_dynamic_dispatch() -> None:
    """Replace generator-time importlib dispatch with a closed-world resolver."""
    dispatch_path = RECOVERED_DIR / "dispatch.py"
    tree = ast.parse(dispatch_path.read_text(encoding="utf-8"))
    tables = {}
    for node in tree.body:
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id in {"DISPATCH", "HANDLERS"}
        ):
            tables[node.targets[0].id] = ast.literal_eval(node.value)
    implementations = sorted({
        (entry[0], entry[1])
        for table in tables.values()
        for entry in table.values()
    })
    resolver = []
    for index, (module, function) in enumerate(implementations):
        relative = module.rsplit(".", 1)[-1]
        keyword = "if" if index == 0 else "elif"
        resolver.extend((
            f"    {keyword} module == {module!r} and name == {function!r}:",
            f"        from .{relative} import {function}",
            f"        return {function}",
        ))
    resolver.append(
        "    raise RuntimeError(f'undeclared recovered dispatch: {module}:{name}')")
    source = '''"""AUTOGENERATED closed-world dynamic-transfer dispatch.

Every reachable target is an explicit import edge. Unknown selectors fail loud;
there is no importlib, interpreter, lifted graph, or runtime discovery.
"""
from .dispatch import DISPATCH, HANDLERS


class UnknownDispatchTarget(RuntimeError):
    def __init__(self, key, regs, base):
        super().__init__(
            "dynamic dispatch to %s: no recovered implementation" % key)
        self.key = key
        self.regs = dict(regs)
        self.base = base


def _resolve(module, name):
''' + "\n".join(resolver) + '''


_cache = {}


def _exec(table, kind, key, mem, plat, base, regs):
    ent = table.get(key)
    if ent is None:
        raise UnknownDispatchTarget(kind + " " + key, regs, base)
    fn = _cache.get((kind, key))
    if fn is None:
        module, name, entry_ip, inputs, needs_plat, df_livein, fl_livein = ent
        implementation = _resolve(module, name)

        def fn(mem, plat, base, regs, _f=implementation, _e=entry_ip,
               _ins=inputs, _np=needs_plat, _dfl=df_livein, _fl=fl_livein):
            kw = {register: regs[register] for register in _ins}
            if _e is not None:
                kw["_entry_ip"] = _e
            if _dfl:
                kw["_df"] = regs.get("_df", 0)
            if _fl:
                kw["_flags_in"] = regs.get("_flags_in", 2)
            if _np:
                out, compat = _f(mem, plat, _base=base, **kw)
            else:
                out, compat = _f(mem, **kw)
            merged = dict(regs)
            merged.update(out)
            return merged, compat

        _cache[(kind, key)] = fn
    return fn(mem, plat, base, regs)


def dyn_exec(key, mem, plat, base, regs):
    return _exec(DISPATCH, "dyn", key, mem, plat, base, regs)


def ivec_exec(key, mem, plat, base, regs):
    if key not in HANDLERS:
        service = getattr(plat, "ivec", None)
        if service is not None:
            out = service(key, base, regs)
            if out is not None:
                return out
    return _exec(HANDLERS, "ivec", key, mem, plat, base, regs)
'''
    (RECOVERED_DIR / "_dyncall.py").write_text(source, encoding="utf-8")


def _load_pairs(path: Path) -> set[str]:
    out: set[str] = set()
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            out.add(line.upper())
    return out


def _closure_roots() -> str:
    obs = json.loads(OBSERVED.read_text(encoding="utf-8"))
    roots = {CANONICAL_ENTRY}
    roots |= {v.upper() for v in (obs.get("ivt_game_vectors") or {}).values()}
    roots |= {v.upper() for v in (obs.get("int_entries") or [])}
    for f in ("dispatch_extra.txt", "boundary_heads.txt",
              "replay_base_entries.txt"):
        roots |= _load_pairs(CODEMAP / f)
    return ",".join(sorted(roots))


def _write_manifest() -> dict:
    """Describe this generated corpus against its local generation evidence."""
    sys.path.insert(0, str(ROOT / "dos_re"))
    from tools.cpuless_closure import walk_closure  # noqa: E402

    ir = json.loads(IR.read_text(encoding="utf-8"))
    all_keys = {k.upper() for k in ir["functions"]}
    promoted = {f"{int(cs, 16):04X}:{int(ip, 16):04X}"
                for cs, ip in (p.stem.split("_")[1:]
                               for p in RECOVERED_DIR.glob("func_*.py"))}
    census = json.loads(CENSUS.read_text(encoding="utf-8"))
    refused = {k.upper(): reason
               for reason, keys in census.get("refused", {}).items()
               for k in keys}

    dyn = {}
    for site in json.loads(DYN_OBS.read_text(encoding="utf-8")).get("sites", []):
        dyn[site["site"].upper()] = sorted(k.upper()
                                           for k in site.get("targets", {}))
    observed = {a.upper() for a in
                json.loads(OBSERVED.read_text(encoding="utf-8")).get("executed", ())
                if isinstance(a, str)}
    roots = [r.strip().upper() for r in _closure_roots().split(",") if r.strip()]
    rep = walk_closure(ir, roots, promoted, refused, dyn, observed)
    runtime_frontier = set(rep["runtime_frontier"])
    static_only = set(rep["static_only_frontier"])

    entries = {}
    for key in sorted(all_keys):
        rec = ir["functions"].get(key) or ir["functions"].get(key.lower(), {})
        is_data = bool(rec) and not rec.get("blocks")
        if key in promoted:
            status = "generated-cpuless"
        elif is_data:
            status = "data-non-function"
        elif key in runtime_frontier:
            status = "not-emitted-observed-frontier"
        elif key in static_only or key in refused:
            status = "not-emitted-no-observed-evidence"
        else:
            status = "not-emitted-no-observed-evidence"
        entry = {"status": status}
        if key in refused:
            entry["refusal"] = refused[key]
        entries[key] = entry

    counts = Counter(e["status"] for e in entries.values())
    manifest = {
        "_notice": "GENERATED by scripts/build_recovered.py -- the "
                   "local diagnostic manifest for the generated ABI-recovered "
                   "corpus. It describes the inputs used for this generation "
                   "and is not a coverage or release-readiness authority. "
                   "Regenerate with that script; do not hand-edit.",
        "import_base": IMPORT_BASE,
        "canonical_entry": CANONICAL_ENTRY,
        "evidence_scope": "local-observed-generation-inputs",
        "atlas_release_authority": False,
        "counts": dict(sorted(counts.items())),
        "observed_generation_frontier": sorted(runtime_frontier),
        "observed_generation_closed": bool(rep["closure_complete"]),
        "unobserved_or_static_only_addresses": sorted(static_only),
        "functions": entries,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=1) + "\n", encoding="utf-8")
    return manifest


def build() -> int:
    if not IR.exists():
        raise SystemExit(
            f"retained Recovery IR is missing: {IR}\n"
            "run: python scripts/build_atlas.py --snapshot artifacts/SNAPSHOT_DIR")
    for local_input in (OBSERVED, BOUNDARY_HEADS):
        if not local_input.exists():
            raise SystemExit(
                f"generated-ABI build input is missing: {local_input}\n"
                "Record or regenerate the local observation inputs before "
                "rebuilding this optional representation.")

    # Per-site dispatch evidence specialized by the local observed selections.
    subprocess.run([sys.executable, str(ROOT / "scripts/find_dispatch_evidence.py"),
                    "--observed", str(OBSERVED), "--out", str(DYN_OBS)], check=True)

    # Recreate the package so a stale module cannot survive a changed IR.
    if RECOVERED_DIR.exists():
        shutil.rmtree(RECOVERED_DIR)
    RECOVERED_DIR.mkdir(parents=True)
    (RECOVERED_DIR / "__init__.py").write_text(
        '"""Generated ABI-recovered SkyRoads implementation corpus.\n\n'
        "Build artifact -- regenerate with scripts/build_recovered.py,\n"
        "do not hand-edit. Authored implementations are declared separately in\n"
        'the skyroads.execution ImplementationCatalog."""\n',
        encoding="utf-8")

    # CPU-ABI adapters bridge the interpreter to a recovered body. The generated
    # ABI provider calls recovered functions
    # directly, so route them to a throwaway dir OUTSIDE the pure corpus package
    # -- else the recovered-purity lint (rightly) flags their make_cpu_platform
    # import.
    adapters = ROOT / "artifacts" / "recovered_adapters"
    if adapters.exists():
        shutil.rmtree(adapters)
    cmd = [sys.executable, str(ROOT / "dos_re/tools/cpuless_promote.py"),
           "--ir", str(IR),
           "--recovered-dir", str(RECOVERED_DIR),
           "--adapter-dir", str(adapters),
           "--import-base", IMPORT_BASE,
           "--boundary-heads", f"@{BOUNDARY_HEADS}",
           "--dyn-evidence", str(DYN_OBS),
           "--desmc",
           "--observed", str(OBSERVED),
           "--census-out", str(CENSUS),
           "--apply"]
    print("[generated-abi] " + " ".join(str(c) for c in cmd))
    r = subprocess.run(cmd, text=True)
    if r.returncode != 0:
        return r.returncode
    _staticize_dynamic_dispatch()

    manifest = _write_manifest()
    n_rec = len(list(RECOVERED_DIR.glob("func_*.py")))
    print(f"\n[generated-abi] corpus ready: {n_rec} recovered modules -> "
          f"{RECOVERED_DIR}")
    print("[generated-abi] manifest: " + ", ".join(
        f"{k}={v}" for k, v in manifest["counts"].items()))
    print(
        "[generated-abi] observed generation frontier: "
        f"{len(manifest['observed_generation_frontier'])} "
        f"(closed for these inputs: {manifest['observed_generation_closed']})")
    print(f"[generated-abi] wrote {MANIFEST.relative_to(ROOT)}")
    print("[generated-abi]   play:   python scripts/play.py --profile development "
          "--composition generated-detached --headless")
    print("[generated-abi]   purity: python tools/lint_cpuless.py")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--print-manifest", action="store_true",
                    help="print the manifest counts and exit (no rebuild)")
    args = ap.parse_args(argv)
    if args.print_manifest:
        m = json.loads(MANIFEST.read_text(encoding="utf-8"))
        print(json.dumps(m["counts"], indent=1))
        print("observed generation frontier:", m["observed_generation_frontier"])
        return 0
    return build()


if __name__ == "__main__":
    raise SystemExit(main())
