"""AUTOGENERATED by dos_re.lift — literal lift. DO NOT hand-edit in place.

Function 1010:5D80  (6 instructions, 3 basic blocks)

Refactor freely: the oracle tests are the contract, not this text. Lines
marked "(interpreter fallback)" are instructions the emitter has no native
form for yet — they are exact, but they are also the to-do list.
"""
from __future__ import annotations

from dos_re.cpu import AF, CF, DF, IF, OF, PF, SF, ZF
from dos_re.hooks import self_disable_if_patched
from dos_re.lift.runtime import (LiftRuntimeError, emulate_call, emulate_far_call,
                                 emulate_int, interp_one)

ENTRY = (0x1010, 0x5D80)
SIGNATURE = bytes.fromhex('32ede306')
MAX_ITERATIONS = 30000  # runaway guard: fail loud, never hang

BLOCK_COUNT = 3
BLOCKS_SEEN = set()  # basic blocks that actually executed


def coverage():
    """(len(seen), total) — how much of the function a verify run exercised."""
    return len(BLOCKS_SEEN), BLOCK_COUNT


def lifted_1010_5d80(cpu):
    """Lifted replacement for 1010:5D80."""
    # Fail loud if the entry bytes no longer match what was lifted
    # (self-modifying code / overlay swap): raises rather than running a
    # replacement for code that is no longer there.
    self_disable_if_patched(cpu, 0x5D80, SIGNATURE, 'lifted_1010_5d80')
    s, mem = cpu.s, cpu.mem
    bb = 0
    # A lifted function runs SYNCHRONOUSLY to completion — unlike the
    # interpreter, no external I/O/timing advances between its blocks. A
    # loop that waits on hardware state (retrace/timer polls) would spin
    # forever here, so bound it and fail loud (such env-waits are poor lift
    # targets — hook them by hand instead).
    for _guard in range(MAX_ITERATIONS):
        if bb == 0:
            BLOCKS_SEEN.add(0)
            # 1010:5D80  32ed         xor
            _a = cpu.get_reg8(5)
            _b = cpu.get_reg8(5)
            _r = _a ^ _b
            cpu.set_logic_flags(_r, 8)
            cpu.set_reg8(5, _r & 0xFF)
            # 1010:5D82  e306         jcxz
            bb = 2 if (s.cx == 0) else 1
        elif bb == 1:
            BLOCKS_SEEN.add(1)
            # 1010:5D84  d1e0         shift
            _r = cpu.shift(4, s.ax, 1, 16)
            s.ax = (_r) & 0xFFFF
            # 1010:5D86  d1d2         shift
            _r = cpu.shift(2, s.dx, 1, 16)
            s.dx = (_r) & 0xFFFF
            # 1010:5D88  e2fa         loop
            s.cx = (s.cx - 1) & 0xFFFF
            bb = 1 if (s.cx != 0) else 2
        elif bb == 2:
            BLOCKS_SEEN.add(2)
            # 1010:5D8A  c3           ret
            s.ip = cpu.pop()
            return
    raise LiftRuntimeError(
        'lifted_1010_5d80' + ' exceeded MAX_ITERATIONS (unbounded internal loop -- likely an environment wait; hook it by hand)')

